
--INSERT DEL REPORTE DE PLANIFICACION DE NECESIDADES
INSERT INTO REPORTING (ID,VNAME,IDACCESSGROUP,BACTIVE) VALUES (9, 'PLANIFICACION DE NECESIDADES',67,1);

COLUMNA AGREGADA PARA INSERTAR EL TRANSITO DE FIGO EN LA TABLA PART 
ALTER TABLE PART ADD TRAFFIC INT NULL DEFAULT 0;

--TABLA PARA INSERTAR LAS VENTAS TRAIDAS DE FIGO
CREATE TABLE SALESFIGO (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    INVOICENUMBER VARCHAR(100) NOT NULL,
    DINVOICEDATE DATETIME NOT NULL,           
    VVAT VARCHAR(50) NOT NULL,
    VINNERCODE VARCHAR(50) NOT NULL,
    IQUANTITY INT NOT NULL,
    DCREATED DATETIME NOT NULL DEFAULT GETDATE()
);


--FUNCION PARA MOSTRAR LOS NOMBRE DE LOS MESES EN EL REPORTE
USE [SODA]
GO
ALTER FUNCTION dbo.fn_GetMonthYear (@OffsetMonths INT)
RETURNS VARCHAR(20)
AS
BEGIN
    DECLARE @Result VARCHAR(20)
    DECLARE @MonthName VARCHAR(10)
    
    SELECT @MonthName = 
        CASE MONTH(DATEADD(MONTH, @OffsetMonths, GETDATE()))
            WHEN 1 THEN 'ENERO'
            WHEN 2 THEN 'FEBRERO'
            WHEN 3 THEN 'MARZO'
            WHEN 4 THEN 'ABRIL'
            WHEN 5 THEN 'MAYO'
            WHEN 6 THEN 'JUNIO'
            WHEN 7 THEN 'JULIO'
            WHEN 8 THEN 'AGOSTO'
            WHEN 9 THEN 'SEPTIEMBRE'
            WHEN 10 THEN 'OCTUBRE'
            WHEN 11 THEN 'NOVIEMBRE'
            WHEN 12 THEN 'DICIEMBRE'
        END
    
    SELECT @Result = @MonthName + '_' + CAST(YEAR(DATEADD(MONTH, @OffsetMonths, GETDATE())) AS VARCHAR(4))
    RETURN @Result
END
GO