ALTER TABLE VEHICLE ADD VNUMBERTXT VARCHAR(10) NULL

INSERT INTO MODULE (VNAME,BGET,BGENERATE,BEXPORT) VALUES ('REPORTES-INTT',1,1,1);

INSERT INTO [SECUENCE](VCODE,INUMBER) VALUES('INTTT',100)

DECLARE @INUMERO INT
EXEC USP_ACT_SECUENCE 'INTTT',@INUMERO OUT