DROP INDEX [IND_POLICY_01] ON [dbo].[POLICY]
GO

CREATE NONCLUSTERED INDEX [IND_POLICY_01] ON [dbo].[POLICY]
(
	[DINVOICEDATE] ASC,
	[IESTATUS] ASC
)
INCLUDE([ID],[IDVEHICLE],[VINVOICENUMBER]) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO


