DROP INDEX [IND_SALEORDERDETAIL_03] ON [dbo].[SALEORDERDETAIL]
GO

CREATE NONCLUSTERED INDEX [IND_SALEORDERDETAIL_03] ON [dbo].[SALEORDERDETAIL]
(
	[IDSALEORDER] ASC,
	[IDPART] ASC
)
INCLUDE([IREQUIRED]) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO


