DROP INDEX [IND_SALEORDER_02] ON [dbo].[SALEORDER]
GO

CREATE NONCLUSTERED INDEX [IND_SALEORDER_02] ON [dbo].[SALEORDER]
(
	[IDSUPPLIER] ASC,
	[IDDEALER] ASC,
	[DCREATED] ASC
)
INCLUDE([ID],[IDESTATUS],[IDTYPE]) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO


