DROP INDEX [IND_DISPATCHEDCONTROL_01] ON [dbo].[DISPATCHEDCONTROL]
GO

CREATE NONCLUSTERED INDEX [IND_DISPATCHEDCONTROL_01] ON [dbo].[DISPATCHEDCONTROL]
(
	[IDSUPPLIER] ASC,
	[IESTATUS] ASC,
	[IDSALEORDER] ASC,
	[IDCUSTOMER] ASC,
	[IDPART] ASC,
	[IDINVOICE] ASC
)
INCLUDE([IINVOICED]) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO


