DROP INDEX [IND_CONTACT_01] ON [dbo].[CONTACT]
GO

SET ANSI_PADDING ON
GO

CREATE UNIQUE NONCLUSTERED INDEX [IND_CONTACT_01] ON [dbo].[CONTACT]
(
	[VVAT] ASC
)
INCLUDE([ID],[VFIRSTNAME],[VLASTNAME],[VADDRESS],[IDCITY],[VPHONE1],[VPHONE2]) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO


