DROP INDEX [IND_PART_01] ON [dbo].[PART]
GO

SET ANSI_PADDING ON
GO

CREATE NONCLUSTERED INDEX [IND_PART_01] ON [dbo].[PART]
(
	[IDSUPPLIER] ASC,
	[VINNERCODE] ASC,
	[VDESCRIPTION] ASC
)
INCLUDE([VMASTERCODE],[VALTERCODE],[VBARCODE],[NPRICE],[NCOST],[NDISCOUNT],[VSIZE],[BSELL],[IDBRAND],[IDTAX],[BACTIVE]) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO


