DROP INDEX [IND_KARDEX_01] ON [dbo].[KARDEX]
GO

CREATE NONCLUSTERED INDEX [IND_KARDEX_01] ON [dbo].[KARDEX]
(
	[IDSUPPLIER] ASC,
	[DCREATED] ASC
)
INCLUDE([ID],[IDPART],[VTYPE],[IQTY],[IQTYOLD],[IQTYNEW],[NCOST],[IDUSER],[IREFERENCE]) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO


