DROP INDEX [IND_VEHICLE_01] ON [dbo].[VEHICLE]
GO

SET ANSI_PADDING ON
GO

CREATE NONCLUSTERED INDEX [IND_VEHICLE_01] ON [dbo].[VEHICLE]
(
	[VVIN] ASC,
	[VPLATE] ASC,
	[VENGINESERIAL] ASC
)
INCLUDE([ID],[IDMODEL],[IDCOLOR],[IYEAR],[IDSUPPLIER],[IDDEALER],[IDCUSTOMER],[BACTIVE],[IESTATUS],[ILASTKM]) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO


