GO
/****** Object:  StoredProcedure [dbo].[USP_CHECK_IMPORTVEHICLES]    Script Date: 18/08/2025 8:46:26 ******/
SET ANSI_NULLS ON

GO
SET QUOTED_IDENTIFIER ON
GO
IF  NOT EXISTS (SELECT * FROM SYS.OBJECTS

                WHERE OBJECT_ID = OBJECT_ID(N'[DBO].[USP_CHECK_IMPORTVEHICLES]')

                AND TYPE IN (N'P', N'PC', N'TF', N'FN'))
EXEC('CREATE PROCEDURE [DBO].[USP_CHECK_IMPORTVEHICLES] AS BEGIN SET NOCOUNT ON  END')
GO
ALTER PROCEDURE [dbo].[USP_CHECK_IMPORTVEHICLES]  
 @DATA NVARCHAR(MAX),
 @IDUSER INT
AS
/* '===============================================================          
  '   NOMBRE                : 
  '   FECHA CREACIÓN        : 
  '   CREADO POR            : JUAN GUARECUCO
  '   CREADO PARA           : 
  '   FUNCIÓN               :  
  '   VERSIÓN               : 
  '   MODIFICADO EN         : 
  '   MODIFICADO POR        :  
  '   RAZÓN DE MODIFICACIÓN : 
  '===============================================================*/

SET XACT_ABORT ON               
SET NOCOUNT ON
SET LOCK_TIMEOUT 180000


			--DECLARA UNA VARIABLE @TDATA
				DECLARE @TDATA AS TABLE
				(
					ID INT,
					VVIN VARCHAR(20),
					VENGINESERIAL VARCHAR(20),
					VPLATE VARCHAR(10),
					IDMODEL INT,
					IDCOLOR INT,
					IDSUPPLIER INT,
					IDDEALER INT,
					VROWREFERENCE VARCHAR(5)
				);

				INSERT INTO @TDATA
				SELECT V.Id,V.Vin,V.EngineSerial,V.Plate,V.ModelId,V.ColorId,
				V.SupplierId,V.DealerId,V.RowReference
				FROM OPENJSON(@DATA)
				WITH (
						Id int,Vin varchar(20),EngineSerial varchar(20),Plate varchar(10), 
						ModelId int,ColorId int,Year int,SupplierId int,DealerId int, CustomerId int, IsActive bit,RowReference VARCHAR(5)
					  ) AS V;

			--VALIDACIONES

			DECLARE @MENSAJE VARCHAR(100)
			SET @MENSAJE=NULL
			DECLARE @IDVEHICLE INT
			DECLARE @IDDEALEAR INT
			SELECT TOP 1 @IDDEALEAR = IDDEALER FROM @TDATA
			DECLARE @IDBRAND INT
			SELECT TOP 1 @IDBRAND = IDBRAND FROM V_DEALERS WHERE IDDEALER=@IDDEALEAR
            DECLARE @SERIAL VARCHAR(20)=NULL
			DECLARE @VROWREF VARCHAR(5)


			     -----------------------------VALIDACION MARCA PLANTA-------------------------------------------
			     IF EXISTS ( SELECT * FROM @TDATA A
							INNER JOIN MODEL M ON M.ID=A.IDMODEL
							INNER JOIN V_SUPPLIERS S ON S.IDSUPPLIER=A.IDSUPPLIER
							WHERE S.IDBRAND <> M.IDBRAND
							)
				BEGIN
				SELECT TOP 1 @SERIAL=A.VVIN,@VROWREF=A.VROWREFERENCE FROM @TDATA A
							INNER JOIN MODEL M ON M.ID=A.IDMODEL
							INNER JOIN V_SUPPLIERS S ON S.IDSUPPLIER=A.IDSUPPLIER
							WHERE S.IDBRAND <> M.IDBRAND
					SET @MENSAJE= 'EXISTEN VEHICULOS CON MODELOS NO ACORDE A LA MARCA DE LA PLANTA: '+ @SERIAL; 
				END

				-----------------------------VALIDACION MARCA-CONCESIONARIO-------------------------------------------
				IF  @MENSAJE IS NULL AND EXISTS (SELECT * FROM @TDATA D
							INNER JOIN V_SUPPLIERS S ON S.IDSUPPLIER=D.IDSUPPLIER
							WHERE S.IDBRAND <> @IDBRAND)
				BEGIN
				    SELECT TOP 1 @SERIAL=D.VVIN,@VROWREF=D.VROWREFERENCE FROM @TDATA D
							INNER JOIN V_SUPPLIERS S ON S.IDSUPPLIER=D.IDSUPPLIER
							WHERE S.IDBRAND <> @IDBRAND
					SET @MENSAJE='VEHICULO QUE NO CORRESPONDEN A LA MARCA DEL CONCESIONARIO ASIGNADO'+@SERIAL
				END
				-----------------------------VALIDACION PARA VIN-------------------------------------------
				IF @MENSAJE IS NULL AND EXISTS ( SELECT * FROM @TDATA A
							INNER JOIN VEHICLE V WITH (NOLOCK) ON A.VVIN = V.VVIN 
							)
				BEGIN 
				   SELECT TOP 1 @SERIAL=A.VVIN,@VROWREF=A.VROWREFERENCE FROM @TDATA A
							INNER JOIN VEHICLE V WITH (NOLOCK) ON A.VVIN = V.VVIN 
					SET @MENSAJE= 'EL REGISTRO QUE INTENTAS CREAR YA EXISTE: '+ @SERIAL;
				END
				-----------------------------VALIDACION PARA PLACA-------------------------------------------
				
				IF @MENSAJE IS NULL AND EXISTS ( SELECT * FROM @TDATA A
							INNER JOIN VEHICLE V WITH (NOLOCK) ON LTRIM(RTRIM(A.VPLATE)) = LTRIM(RTRIM(V.VPLATE)) 
							)
				BEGIN
				     SELECT TOP 1 @SERIAL=A.VPLATE,@VROWREF=A.VROWREFERENCE FROM @TDATA A
					 INNER JOIN VEHICLE V WITH (NOLOCK) ON LTRIM(RTRIM(A.VPLATE)) = LTRIM(RTRIM(V.VPLATE))
					SET @MENSAJE= 'EL REGISTRO QUE INTENTAS CREAR YA EXISTE: '+ @SERIAL;
				END

				-----------------------------VALIDACION PARA SERIAL DE MOTOR-------------------------------------------
				IF @MENSAJE IS NULL AND EXISTS ( SELECT * FROM @TDATA A
							INNER JOIN VEHICLE V WITH (NOLOCK) ON LTRIM(RTRIM(A.VENGINESERIAL)) = LTRIM(RTRIM(V.VENGINESERIAL))  
							)
				BEGIN
				     SELECT TOP 1 @SERIAL=A.VENGINESERIAL,@VROWREF=A.VROWREFERENCE FROM @TDATA A
					 INNER JOIN VEHICLE V WITH (NOLOCK) ON LTRIM(RTRIM(A.VENGINESERIAL)) = LTRIM(RTRIM(V.VENGINESERIAL))
					SET @MENSAJE= 'EL REGISTRO QUE INTENTAS CREAR YA EXISTE: '+ @SERIAL; 
				END

			-- Lanzar error si se detectó alguno
				IF @MENSAJE IS NOT NULL
				BEGIN
					IF @VROWREF IS NOT NULL AND LTRIM(RTRIM(@VROWREF)) <> ''
						SET @MENSAJE = @MENSAJE + ' -FILA: ' + @VROWREF

					RAISERROR(@MENSAJE, 16, 1)
					RETURN
				END



				


			

					
				

