GO
/** Object:  StoredProcedure [dbo].[USP_POST_ADJUSTMENTDETAILS]    Script Date: 18/08/2025 8:46:26 **/
SET ANSI_NULLS ON

GO
SET QUOTED_IDENTIFIER ON
GO
IF  NOT EXISTS (SELECT * FROM SYS.OBJECTS

                WHERE OBJECT_ID = OBJECT_ID(N'[DBO].[USP_POST_ADJUSTMENTDETAILS]')

                AND TYPE IN (N'P', N'PC', N'TF', N'FN'))
EXEC('CREATE PROCEDURE [DBO].[USP_POST_ADJUSTMENTDETAILS] AS BEGIN SET NOCOUNT ON  END')
GO


ALTER PROCEDURE [dbo].[USP_POST_ADJUSTMENTDETAILS]
    @DATA NVARCHAR(MAX),
    @IDUSER INT 
AS
/* '===============================================================          
  '   NOMBRE                : 
  '   FECHA CREACIÓN        : 
  '   CREADO POR            : SARAHY CHIRINOS
  '   CREADO PARA           : 
  '   FUNCIÓN               :  
  '   VERSIÓN               : 
  '   MODIFICADO EN         : 
  '   MODIFICADO POR        :  
  '   RAZÓN DE MODIFICACIÓN : 
  '===============================================================*/

SET XACT_ABORT ON               
SET NOCOUNT ON
SET LOCK_TIMEOUT 180000

BEGIN 
	BEGIN TRY
		BEGIN TRAN  
				DECLARE @TDATA AS TABLE
				( 
					ID INT,
					IDADJUSTMENT INT,
					IDLOCATION INT,
					IDPART INT,
					ISTOCK INT,
					IDREASON INT,
					CTYPE CHAR(1)
				);

				INSERT INTO @TDATA
				SELECT 
					L.Id, 
					L.AdjustmentId, 
					L.LocationId, 
					L.PartId, 
					L.Stock, 
					L.ReasonId,
					L.AdjustmentType
				FROM OPENJSON(@DATA)
				WITH (
					Id int, 
					AdjustmentId int, 
					LocationId int,
					PartId int,
					Stock int,
					ReasonId int,
					AdjustmentType char(1)
				) AS L
			  
				DECLARE @IID INT
				DECLARE @IINSERTED INT
				DECLARE @IUPDATED INT

				DECLARE @IDPART INT
				DECLARE @IDLOCATION INT
				DECLARE @IDADJUSTMENT INT 
				SELECT TOP 1 @IDPART=IDPART, @IDLOCATION=IDLOCATION , @IDADJUSTMENT = IDADJUSTMENT FROM @TDATA

				-- VALIDAR QUE PARTE, UBICACIÓN Y ADJUSTMENT PERTENEZCAN A LA MISMA PLANTA/SUPPLIER
				IF EXISTS (
					SELECT 1 
					FROM @TDATA D
					INNER JOIN PART P WITH (NOLOCK) ON D.IDPART = P.ID
					INNER JOIN V_LOCATION VL WITH (NOLOCK) ON D.IDLOCATION = VL.ID
					INNER JOIN ADJUSTMENT A WITH (NOLOCK) ON D.IDADJUSTMENT = A.ID
					WHERE P.IDSUPPLIER <> VL.IDSUPPLIER 
					   OR P.IDSUPPLIER <> A.IDSUPPLIER
					   OR VL.IDSUPPLIER <> A.IDSUPPLIER
				)
				BEGIN
					RAISERROR('PARTE, UBICACIÓN Y AJUSTE DEBEN PERTENECER A LA MISMA PLANTA', 16, 1)
					RETURN
				END

				INSERT INTO ADJUSTMENTDETAILS( 
					IDADJUSTMENT,
					IDLOCATION,
					IDPART,
					ISTOCK,
					IDREASON,
					CTYPE  
					)
				SELECT	 
					D.IDADJUSTMENT,
					D.IDLOCATION,
					D.IDPART,
					D.ISTOCK,
					D.IDREASON,
					D.CTYPE 
				FROM @TDATA D 
				WHERE NOT EXISTS (SELECT * FROM ADJUSTMENTDETAILS OD WITH (NOLOCK) 
								  WHERE OD.IDADJUSTMENT=@IDADJUSTMENT AND OD.IDPART=@IDPART AND OD.IDLOCATION=@IDLOCATION)

				SELECT @IINSERTED=@@ROWCOUNT
				SELECT @IID=SCOPE_IDENTITY()

				-- PARTE Y UBICACIÓN DEBEN SER DE LA MISMA PLANTA
				IF EXISTS (
					SELECT 1 
					FROM @TDATA D
					INNER JOIN PART P WITH (NOLOCK) ON D.IDPART = P.ID
					INNER JOIN V_LOCATION VL WITH (NOLOCK) ON D.IDLOCATION = VL.ID
					INNER JOIN ADJUSTMENT A WITH (NOLOCK) ON D.IDADJUSTMENT = A.ID
					WHERE P.IDSUPPLIER <> VL.IDSUPPLIER 
					   OR P.IDSUPPLIER <> A.IDSUPPLIER
					   OR VL.IDSUPPLIER <> A.IDSUPPLIER
				)
				BEGIN
					RAISERROR('PARTE, UBICACIÓN Y AJUSTE DEBEN PERTENECER A LA MISMA PLANTA', 16, 1)
					RETURN
				END
				UPDATE OD
					SET
						OD.ISTOCK = D.ISTOCK,
						OD.IDREASON = D.IDREASON,
						OD.CTYPE = D.CTYPE
				FROM ADJUSTMENTDETAILS OD
				INNER JOIN @TDATA D ON D.IDADJUSTMENT=OD.IDADJUSTMENT AND D.IDPART=OD.IDPART AND D.IDLOCATION= D.IDLOCATION 


				SELECT @IUPDATED=@@ROWCOUNT

				SELECT
				ISNULL(@IID,0) AS IID , 
				ISNULL(@IINSERTED,0) AS IINSERTED,
				ISNULL(@IUPDATED,0) AS IUPDATED

 		COMMIT TRAN
	END TRY
	BEGIN CATCH
		IF XACT_STATE() <> 0
			ROLLBACK TRAN
		DECLARE @ErrorMessage NVARCHAR(4000) 
		SELECT  @ErrorMessage = ERROR_PROCEDURE() + ' : ' + ERROR_MESSAGE()
		RAISERROR ( @ErrorMessage , 16,1) 
	END CATCH 
END
GO


