ALTER TABLE PAYMENT
ADD NALTERRATE NUMERIC(18,4)

ALTER TABLE PAYMENT
ADD IDUSER INT

ALTER TABLE PAYMENT
ADD IDCURRENCY INT

ALTER TABLE PAYMENT
DROP COLUMN VCONCEPT

ALTER TABLE PAYMENT
DROP COLUMN VTYPE

UPDATE P
SET  P.NALTERRATE=R.NALTERRATE
FROM PAYMENT P 
INNER JOIN RATE R ON CAST(P.DDATERATE AS DATE) = CAST(R.DDATE AS DATE)
