ALTER TABLE [dbo].[DISPATCHEDCONTROL]
ADD  VTYPE VARCHAR(1)
ALTER TABLE [dbo].[INVOICECONTROL]
ADD  VTYPE VARCHAR(1)

UPDATE DISPATCHEDCONTROL
SET VTYPE='A'
WHERE IESTATUS<>2

UPDATE INVOICECONTROL
SET VTYPE='A'
WHERE ISNULL(IDCONTROL,0)<>0