USE [FIGO]
GO

/****** Object:  View [dbo].[V_PARALYZEDUNIT]    Script Date: 17/08/2026 11:03:04 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


ALTER VIEW [dbo].[V_PARALYZEDUNIT]
AS
WITH 
-- 1. Vista/CTE equivalente a la tabla #CUSTOMER
CTE_CUSTOMER AS (
    SELECT 
        ID, 
        (VFIRSTNAME + ' ' + ISNULL(VLASTNAME, '')) AS VNAME 
    FROM CONTACT
),

-- 2. CTE equivalente a la tabla #SALEORDER
CTE_SALEORDER AS (
    SELECT 
        -- Lista de Pedidos ÚNICOS
        STUFF((
            SELECT DISTINCT ', PEDIDO NUM: ' + CAST(S2.ID AS VARCHAR(10))
            FROM [dbo].[SALEORDER] S2
            WHERE S2.VREFERENCE = S.VREFERENCE 
              AND S2.BPARALYZED = 1 
              AND S2.IDTYPE IN (1, 2, 7)
            FOR XML PATH(''), TYPE
        ).value('.', 'NVARCHAR(MAX)'), 1, 2, '') AS Pedidos,

        -- Estatus del pedido MÁS RECIENTE
        EstatusReciente.VDISPLAYESTATUS AS STATUSNAME,

        S.VREFERENCE AS IDREFERENCE, 
        MAX(S.DCREATED) AS UltimaFecha,

        -- Lista de Partes ÚNICAS con salto de línea
        STUFF((
            SELECT DISTINCT ';' + CHAR(13) + CHAR(10) + 'PEDIDO ' + CAST(S2.ID AS VARCHAR(10)) + ' :' + P2.VDESCRIPTION + ' CANT: ' + CAST(SD2.IREQUIRED AS VARCHAR(20))
            FROM [dbo].[SALEORDER] S2
            INNER JOIN SALEORDERDETAIL SD2 WITH (NOLOCK) ON S2.ID = SD2.IDSALEORDER
            INNER JOIN PART P2 ON P2.ID = SD2.IDPART
            WHERE S2.VREFERENCE = S.VREFERENCE 
              AND S2.BPARALYZED = 1 
              AND S2.IDTYPE IN (1, 2, 7)
            FOR XML PATH(''), TYPE
        ).value('.', 'NVARCHAR(MAX)'), 1, 3, '') AS VDESCRIPCION,

        -- Comentarios ÚNICOS por pedido con salto de línea
        STUFF((
            SELECT DISTINCT ';' + CHAR(13) + CHAR(10) + 'PEDIDO ' + CAST(S3.ID AS VARCHAR(10)) + ' - ' + ISNULL(S3.VCOMMENT, '')
            FROM [dbo].[SALEORDER] S3
            WHERE S3.VREFERENCE = S.VREFERENCE 
              AND S3.BPARALYZED = 1 
              AND S3.IDTYPE IN (1, 2, 7)
            FOR XML PATH(''), TYPE
        ).value('.', 'NVARCHAR(MAX)'), 1, 3, '') AS VCOMMENT

    FROM [dbo].[SALEORDER] S
    INNER JOIN SALEORDERDETAIL SD WITH (NOLOCK) ON S.ID = SD.IDSALEORDER
    INNER JOIN PART P ON P.ID = SD.IDPART
    INNER JOIN V_DEALERS D ON D.IDDEALER = S.IDDEALER

    OUTER APPLY (
        SELECT TOP 1 A2.VDISPLAYESTATUS
        FROM [dbo].[SALEORDER] S2
        INNER JOIN ACTION A2 ON A2.ID = S2.IDESTATUS
        WHERE S2.VREFERENCE = S.VREFERENCE 
          AND S2.BPARALYZED = 1 
          AND S2.IDTYPE IN (1, 2, 7)
        ORDER BY S2.DCREATED DESC
    ) EstatusReciente

    WHERE S.BPARALYZED = 1
      AND S.IDTYPE IN (1, 2, 7)
    GROUP BY 
        S.VREFERENCE,
        EstatusReciente.VDISPLAYESTATUS
),

-- 3. CTE equivalente a la tabla #TMP_PARALYZEDUNITS
CTE_TMP_PARALYZEDUNITS AS (
    SELECT 
        D.IDSUPPLIER,
        S.IDDEALER AS IDDEALER,
        S.IDVEHICLE,
        S.ID AS DOCUMENTID,
        S.DCREATED AS DOCUMENTDATE,
        CASE 
            WHEN S.IDSERVICETYPE = 1 THEN 'MANTENIMIENTO'
            WHEN S.IDSERVICETYPE = 2 THEN 'ASISTENCIA TECNICA' 
            ELSE 'REPORTE FALLA' 
        END AS CASETYPE,
        RT.VNAME AS DOCUMENTTYPE,
        CASE 
            WHEN S.IESTATUS IN (DBO.UFN_GET_ISTATUS('CREATE'), DBO.UFN_GET_ISTATUS('TOVALIDATE')) THEN 'POR DIAGNOSTICO'
            WHEN S.IESTATUS IN (DBO.UFN_GET_ISTATUS('VALIDATE'), DBO.UFN_GET_ISTATUS('TOAPPROVE'), DBO.UFN_GET_ISTATUS('APPROVE')) THEN 'POR APROBACION DE PRESUPUESTO'
            WHEN S.IESTATUS IN (DBO.UFN_GET_ISTATUS('GENERATE')) AND ISNULL(SO.STATUSNAME, '') = 'PROCESADO' THEN 'EN REPARACION'
            WHEN S.IESTATUS IN (DBO.UFN_GET_ISTATUS('GENERATE')) AND ISNULL(SO.STATUSNAME, '') <> 'PROCESADO' THEN 'ESPERA DE REPUESTO'
            ELSE 'NO DEFINIDO' 
        END AS DOCUMENTSTATUS,
        ISNULL(SO.Pedidos, '') AS REFERENCEID,
        ISNULL(SO.STATUSNAME, '') AS REFERENCESTATUS,
        SO.UltimaFecha AS SALERORDERDATE,
        SO.VDESCRIPCION AS VDESCRIPTIONSALEORDER,
        SO.VCOMMENT AS VCOMMENTSALEORDER,
        CASE 
            WHEN S.IDSERVICETYPE = 2 THEN S.VSUPPLIERDECISION 
            ELSE S.VTECHNICALSOLUTION 
        END AS VTECHNICALSOLUTION
    FROM [dbo].[MAINTENANCE] S
    INNER JOIN V_DEALERS D ON D.IDDEALER = S.IDDEALER
    INNER JOIN REPORTTYPE RT ON RT.ID = S.IDREPORTTYPE
    INNER JOIN ACTION A ON A.ID = S.IESTATUS
    LEFT JOIN CTE_SALEORDER SO ON CAST(S.ID AS VARCHAR(20)) = SO.IDREFERENCE
    WHERE S.BPARALYZED = 1
      AND S.IDSERVICETYPE IN (2, 3)
      AND S.IESTATUS NOT IN (18, 19)
)

-- 4. Consulta final de la Vista
SELECT 
    D.DEALER AS [CONCESIONARIO],
    T.[DOCUMENTID] AS [NRO DE REPORTE/ASISTENCIA],
    V.VVIN AS [VIN],
    V.VPLATE AS [PLACA],
    (M.VDESCRIPTION + ' - ' + M.VNAME) AS [SUP-MODELO],
    T.[CASETYPE] AS [TIPO DE SOLICITUD],
    ISNULL(C.VNAME, '') AS [PROPIETARIO],
    T.VTECHNICALSOLUTION AS [DIAGNOSTICO],
    T.[DOCUMENTSTATUS] AS [ESTATUS],
    'SI' AS [PARALIZADA],
    T.[DOCUMENTTYPE] AS [TIPO DE REPORTE],
    T.DOCUMENTDATE AS [FECHA DE INGRESO],
    DATEDIFF(day, T.[DOCUMENTDATE], GETDATE()) AS [TIEMPO DE PARALIZACION],
    ISNULL(T.[REFERENCEID], '') AS [NRO DE PEDIDO],
    ISNULL(T.[REFERENCESTATUS], '') AS [ESTATUS DE PEDIDO],
    T.[SALERORDERDATE] AS [FECHA ORDEN DE PEDIDO],
    ISNULL(T.VDESCRIPTIONSALEORDER, '') AS [REPUESTOS ORDENADOS],
    ISNULL(T.VCOMMENTSALEORDER, '') AS [OBSERVACION],
    COUNT(*) OVER() AS [TOTAL],
	P.VSUPPLIER AS [PLANTA]
FROM CTE_TMP_PARALYZEDUNITS T
INNER JOIN VEHICLE V WITH (NOLOCK) ON V.ID = T.IDVEHICLE
INNER JOIN MODEL M WITH (NOLOCK) ON M.ID = V.IDMODEL
INNER JOIN V_DEALERS D ON D.IDDEALER = T.IDDEALER
INNER JOIN V_SUPPLIERS P ON D.IDSUPPLIER=P.IDSUPPLIER
LEFT JOIN CTE_CUSTOMER C ON V.IDCUSTOMER = C.ID;
GO


