

INSERT INTO REASON(VDESCRIPTION,CTYPE,BCLAIM)
VALUES ('MAL DESPACHO','C',1)

UPDATE REASON
SET CTYPE='C'
WHERE ID=13
	   
ALTER TABLE dbo.REASON 
DROP CONSTRAINT CK_REASON_TYPE;

-- 2. Crear la restricción con los nuevos valores permitidos
ALTER TABLE dbo.REASON 
ADD CONSTRAINT CK_REASON_TYPE 
CHECK (CTYPE IN ('E', 'S', 'C'));