GO
/****** Object:  StoredProcedure [dbo].[USP_GET_VEHICLES_INVOICE]    Script Date: 18/08/2025 8:46:26 ******/
SET ANSI_NULLS ON

GO
SET QUOTED_IDENTIFIER ON
GO
IF  NOT EXISTS (SELECT * FROM SYS.OBJECTS

                WHERE OBJECT_ID = OBJECT_ID(N'[DBO].[USP_GET_VEHICLES_INVOICE]')

                AND TYPE IN (N'P', N'PC', N'TF', N'FN'))
EXEC('CREATE PROCEDURE [DBO].[USP_GET_VEHICLES_INVOICE] AS BEGIN SET NOCOUNT ON  END')
GO

ALTER PROCEDURE [dbo].[USP_GET_VEHICLES_INVOICE] -- USP_GET_VEHICLES_INVOICE 1,NULL,5111,'4T1BK1EB9EU453127',0
(
@IDUSER INT,
@IDSUPPLIER INT=NULL,
@IDDEALER INT = NULL,
@VFILTER VARCHAR(20) = NULL,
@IROWFROM INT = NULL
)
AS
/* '===============================================================          
  '   NOMBRE                : 
  '   FECHA CREACIÓN        : 
  '   CREADO POR            : JUAN GUARECUCO
  '   CREADO PARA           : 
  '   FUNCIÓN               :  
  '   VERSIÓN               : 
  '   MODIFICADO EN         : 
  '   MODIFICADO POR        :  
  '   RAZÓN DE MODIFICACIÓN : 
  '===============================================================*/

SET XACT_ABORT ON               
SET NOCOUNT ON
SET LOCK_TIMEOUT 180000


BEGIN
	
	DECLARE @TOPE INT

	IF @IROWFROM IS NULL
	BEGIN
		SET @TOPE=1000000
		SET @IROWFROM=0
	END
	ELSE
	BEGIN
		SET @TOPE=100
	END

		   BEGIN

			   WITH  T1 AS (
				
					SELECT 
					V.*,
					P.ID AS IDPOLICYTYPE, 
					P.VDESCRIPTION AS VPOLICYTYPE,
					VC.VLASTNAME AS VCUSTOMERLASTNAME,
					VC.VVAT,
					VC.VPHONE1,
					VC.VEMAIL,
					PQ.ID AS IDPOLICY,
					PQ.VNUMBER,
					PQ.IESTATUS AS IESTATUSPOLICY,
					AC.VDISPLAYESTATUS AS VESTATUSPOLICY
					FROM V_VEHICLES V
					INNER JOIN MODEL M ON M.ID=V.IDMODEL
					INNER JOIN POLICYTYPE P ON P.ID=M.IDPOLICYTYPE
					INNER JOIN V_CONTACTS VC ON  V.IDCUSTOMER=VC.ID
					INNER JOIN POLICY PQ WITH (NOLOCK) ON V.ID=PQ.IDVEHICLE
					INNER JOIN ACTION AC WITH (NOLOCK) ON PQ.IESTATUS=AC.ID
					WHERE 
					V.IESTATUS = DBO.UFN_GET_ISTATUS('BINVOICE') AND
					V.IDDEALER = CASE WHEN ISNULL(@IDDEALER,0) = 0 THEN v.IDDEALER ELSE @IDDEALER END and
					(
						(VVIN LIKE CASE WHEN ISNULL(@VFILTER,'')='' THEN '%'+VVIN+'%' ELSE '%'+@VFILTER+'%'  END) OR 
						(VENGINESERIAL LIKE CASE WHEN ISNULL(@VFILTER,'')='' THEN '%'+VENGINESERIAL+'%' ELSE '%'+@VFILTER+'%'  END) OR 
						(VMODEL LIKE CASE WHEN ISNULL(@VFILTER,'')='' THEN '%'+VMODEL+'%' ELSE '%'+@VFILTER+'%'  END) OR 
						(VPLATE  LIKE CASE WHEN ISNULL(@VFILTER,'')='' THEN '%'+VPLATE+'%' ELSE '%'+@VFILTER+'%'  END)
					)

				),
				T2 AS (SELECT COUNT(*) AS TOTAL FROM T1),
				
				T3 AS (

						SELECT * FROM T1
						ORDER BY T1.VVIN
						OFFSET @IROWFROM ROWS  --Indica la posicion del registro Inicial...(el resultado de ..(1))
						FETCH NEXT @TOPE ROWS ONLY
					   )
				SELECT T3.*,T2.* FROM T3,T2;


		   END
		 

END
