UPDATE MAINTENANCE
SET IDREPORTTYPE=3
WHERE IDSERVICETYPE=1 AND IDREPORTTYPE=1 AND EXISTS(SELECT PD.* FROM POLICYDETAILS PD WHERE MAINTENANCE.ID=pd.IDMAINTENANCE)

UPDATE MAINTENANCE
SET IDREPORTTYPE=2
WHERE IDSERVICETYPE=1 AND NOT EXISTS(SELECT PD.* FROM POLICYDETAILS PD WHERE MAINTENANCE.ID=pd.IDMAINTENANCE)