
CREATE TABLE SODA.dbo.REPORTFIGO (
	ID int IDENTITY(1,1) PRIMARY KEY,
	VNAME varchar(200) COLLATE Modern_Spanish_CI_AS NOT NULL,
	VCONTENT TEXT,
	IDACCESSGROUP int NOT NULL,
	DCREATED datetime NULL,
	DUPDATED datetime NULL,
	VUPDATEDBY varchar(30) COLLATE Modern_Spanish_CI_AS NULL,
	BACTIVE bit NULL,
	BPDFREPORT BIT
);


CREATE TABLE SODA.dbo.FILTERREPORT (
	ID int IDENTITY(1,1) PRIMARY KEY,
	VFIELD varchar(50) NULL,
	VFIELDTYPE VARCHAR(1),
	VACTIONTYPE VARCHAR(1),
	IDREPORTFIGO INT,
	DCREATED datetime NULL,
	DUPDATED datetime NULL,
	VUPDATEDBY varchar(30) COLLATE Modern_Spanish_CI_AS NULL,
	BACTIVE bit NULL,
	FOREIGN KEY (IDREPORTFIGO) REFERENCES REPORTFIGO(ID) 
);