USE [FIGO]
GO

/****** Object:  View [dbo].[V_PAYMENTDETAILS]    Script Date: 12/06/2026 12:26:13 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO





ALTER VIEW [dbo].[V_PAYMENTDETAILS]
AS
SELECT P.ID AS IDPAYMENT,P.IDSUPPLIER,P.IDDEALER,
D.ID AS IDPAYMENTDETAIL,
CONVERT(VARCHAR(10),D.DDATE,120) AS DTRANSDATE,
B.VCODE AS VBANKCODE,  (B.VCODE+  A.VCODE) AS VBANKACCOUNT, D.VREFERENCE,D.NAMOUNT,
D.IDSTATUS
FROM PAYMENTDETAILS D WITH (NOLOCK)
INNER JOIN PAYMENT P WITH (NOLOCK) ON P.ID=D.IDPAYMENT
INNER JOIN BANKACCOUNT A WITH (NOLOCK) ON A.ID=D.IDBANKACCOUNT
INNER JOIN DESTINYBANK B WITH (NOLOCK) ON B.ID = A.IDBANK

GO


