SELECT * FROM REPORTFIGO


-- TABLA PARA INSERTAR LAS DEVOLUCIONES DE VENTAS TRAIDAS DE FIGO
CREATE TABLE RETURNSFIGO (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    VNOTENUMBER VARCHAR(50) NOT NULL,         
    DNOTEDATE DATETIME NOT NULL,                 
    VDESCRIPTION VARCHAR(200) NOT NULL,         
    VINNERCODE VARCHAR(25) NOT NULL,            
    IQUANTITY INT NOT NULL,                     
    VREASON VARCHAR(100) NOT NULL,              
    VINVOICENUMBER VARCHAR(50) NOT NULL,        
    DINVOICEDATE DATETIME NOT NULL,              
    IDSUPPLIER INT NOT NULL,                   
    DCREATED DATETIME NOT NULL DEFAULT GETDATE()
);


-- Insertar el query de devoluciones en tu tabla de configuración
INSERT INTO REPORTFIGO (VNAME, VCONTENT, BACTIVE, BPDFREPORT, BREPORT, IDACCESSGROUP, DCREATED)
VALUES (
    'ExtractReturnsRepuestos',
    'SELECT
    tndc.NU_NOTA_DEBITO_CREDITO 	NRO_NOTA,
    tndc.FE_EMISION					EMISION_NOTA,
    tp.NB_PRODUCTO					VDESCRIPTION,
    tp.CO_PRODUCTO                  VINNERCODE,  
    tdndc.CA_PRODUCTO				IQUANTITY,
    tctv.DE_OCURRENCIA				VREASON,
    tf.NU_FACTURA 					NRO_FACTURA,
    tf.FE_EMISION 					FE_FACTURA,
    CASE WHEN tf.EMP_ID_EMPRESA = 6354886 THEN 4069
    WHEN tf.EMP_ID_EMPRESA = 6569364 THEN 4076 
    ELSE tf.EMP_ID_EMPRESA END AS IDSUPPLIER
FROM T06_NOTA_DEBITO_CREDITO tndc
INNER JOIN T06_DETALLE_NOTA_DEB_CRED tdndc ON tdndc.NDC_ID_NOTA_DEBITO_CREDITO = tndc.ID_REGISTRO
INNER JOIN T03_PRODUCTO tp ON tp.ID_REGISTRO = tdndc.PRD_ID_PRODUCTO
INNER JOIN T03_GRUPO_PRODUCTO tgp ON tgp.ID_REGISTRO = tp.GRP_ID_GRUPO_PRODUCTO
INNER JOIN T04_FACTURA tf ON tndc.FAC_ID_FACTURA = tf.ID_REGISTRO
INNER JOIN T00_CONTENIDO_TABLA_VIRTUAL tctv ON tctv.ID_REGISTRO = tndc.CTV_ID_MOTIVO_NOTA
WHERE SUBSTR(tgp.CO_GRUPO_PRODUCTO, 1, 5) IN (''06-01'', ''06-02'')       
AND tgp.CO_GRUPO_PRODUCTO NOT IN (''06-01-91'', ''06-02-91'')      
AND tf.FE_EMISION >= TRUNC(SYSDATE) -2
ORDER BY tf.FE_EMISION ASC',
    1,
    0,
    0,
    1,
    GETDATE()
);
