
-- Insertar campo para PLANTA en la tabla vehicle 
ALTER TABLE VEHICLE ADD VNUMBERPLANTATXT VARCHAR(20) NULL

-- Modificar la cantidad de caracteres para el campo VCODE
ALTER TABLE SECUENCE
ALTER COLUMN VCODE VARCHAR(15) NOT NULL
GO

-- Insertar nueva secuencia para PLANTA
INSERT INTO SECUENCE (VCODE, INUMBER)
VALUES ('INTT_PLANTA', 0)

--Insert para el modulo de INTT-PLANTA
INSERT INTO MODULE (VNAME, BGET, BEXPORT,BGENERATE) VALUES('REPORTES-INTT-PLANTA',1,1,1)

