USE [OASIS]
GO
/****** Objeto: StoredProcedure [dbo].[USP_GET_INTT_PLANTA_EXPORT] Fecha de script: 17/8/2026 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

ALTER PROCEDURE [dbo].[USP_GET_INTT_PLANTA_EXPORT]--[USP_GET_INTT_PLANTA_EXPORT]1,4069,l
    @IDUSER INT,
    @IDSUPPLIER INT,
    @IDCONTROL INT
AS
/* '===============================================================          
  '   NOMBRE                : USP_GET_INTT_PLANTA_EXPORT
  '   FECHA CREACIÓN        :
  '   CREADO POR            : GERARDO JIMENEZ
  '   CREADO PARA           : 
  '   FUNCIÓN               : 
  '   VERSIÓN               : 
  '   MODIFICADO EN         : 
  '   MODIFICADO POR        : 
  '   RAZÓN DE MODIFICACIÓN : 
  '===============================================================*/
BEGIN
    SET XACT_ABORT ON;               
    SET NOCOUNT ON;
    SET LOCK_TIMEOUT 180000;

    DECLARE @TOPE INT = 1000000
    DECLARE @IROWFROM INT = NULL
    DECLARE @BTXT BIT = 1
    
    DECLARE @VVAT VARCHAR(10)
    DECLARE @VRAZON VARCHAR(50)
    DECLARE @VNROENVIO VARCHAR(07)
    DECLARE @VREGISTRO VARCHAR(08)
    DECLARE @VFECHAENVIO VARCHAR(14)

    SELECT @VVAT=VVAT, @VRAZON=VSUPPLIER,
           @VREGISTRO=CASE WHEN IDSUPPLIER=4069 THEN 'LRMSL106' ELSE 'YYMMM108' END
    FROM V_SUPPLIERS WHERE IDSUPPLIER = @IDSUPPLIER

    SELECT @VFECHAENVIO=REPLACE(REPLACE(REPLACE(CONVERT(VARCHAR(20),GETDATE(),120),'-',''),' ',''),':','')
      
    SELECT X.DATOS
    FROM (
        SELECT 
            1 AS ORDEN,
            REPLACE(CONVERT(VARCHAR(10),GETDATE(),120),'-','') AS FECHA,
            'RE'
            +CASE WHEN @IDSUPPLIER=4069 THEN 'EE' ELSE 'CO' END
            +RIGHT('0000000'+CAST(@IDCONTROL AS VARCHAR(07)), 07)
            +RIGHT('00000000000000'+@VFECHAENVIO, 14)
            +LEFT(@VRAZON + SPACE(50), 50)
            +RIGHT('00000000'+@VREGISTRO, 08)
            +REPLACE(CONVERT(VARCHAR(10),GETDATE(),120),'-','')
            +LEFT('' + SPACE(230), 230)
            +'*' AS DATOS
        UNION ALL
        SELECT 
            2 AS ORDEN,
            T.DSELLINVOICEDATE AS FECHA,
            UPPER(
            T.VTIPO_MOV+T.VRECORD_NUMBER+T.VUPDATE_NUMBER+T.VBRAND+
            T.VSERIE+T.VMODEL+T.VMODELYEAR+T.VVIN+T.VSERIAL+T.VPLATE+T.VCOLOR1+T.VCOLOR2+
            T.VWEIGHT+T.VCAPACITYTYPE+T.VCAPACITY+T.VAXLENUMBER+T.VWHEELDIAMETER+T.VCLASS+T.VTYPE+T.VUSE+T.VCERTIFICATEDATE+
            T.VRIF+T.VPORT+T.VFILENUMBER+T.DFILEDATE+T.VINVOICENUMBER+T.DINVOICEDATE+T.VCERTIFICATENUMBER+T.VMANUFACTUREYEAR+
            T.VSERIALVIN+T.VSERIALCHASIS+T.VSELLINVOICENUMBER+T.VSELLINVOICEDATE+T.VHOMONUMBER+
            T.VHOMODATE+T.VSERVICE+T.VSEATSNUMBER+T.VRAFANUMBER+T.VRAFADATE+T.VRAFASEC+T.VSERIALCARRO+T.VFUELTYPE
            ) AS DATOS
        FROM V_TXTSUPPLIER T
        INNER JOIN VEHICLE VEH WITH (NOLOCK) ON VEH.VVIN = T.VVIN AND VEH.IDSUPPLIER = T.IDSUPPLIER
        WHERE T.IDSUPPLIER = @IDSUPPLIER
            AND VEH.VNUMBERPLANTATXT = RIGHT('0000000000' + CAST(@IDCONTROL AS VARCHAR), 10)
            AND EXISTS (SELECT 1 FROM V_SUPPLIERS_USER R WHERE R.IDUSER = @IDUSER AND R.IDSUPPLIER = T.IDSUPPLIER)
        UNION ALL
        SELECT 
            3 AS ORDEN,
            REPLACE(CONVERT(VARCHAR(10),GETDATE(),120),'-','') AS FECHA,
            'RC'+RIGHT('0000000' + CAST(T.TOTAL AS VARCHAR(5)), 07)+'00000000000000' AS DATOS
        FROM (
            SELECT COUNT(*) AS TOTAL
            FROM V_TXTSUPPLIER T
            INNER JOIN VEHICLE VEH WITH (NOLOCK) ON VEH.VVIN = T.VVIN AND VEH.IDSUPPLIER = T.IDSUPPLIER
            WHERE T.IDSUPPLIER = @IDSUPPLIER
                AND VEH.VNUMBERPLANTATXT = RIGHT('0000000000' + CAST(@IDCONTROL AS VARCHAR), 10)
                AND EXISTS (SELECT 1 FROM V_SUPPLIERS_USER R WHERE R.IDUSER = @IDUSER AND R.IDSUPPLIER = T.IDSUPPLIER)
        ) T
    ) X
    ORDER BY X.ORDEN, X.FECHA
END
GO