USE [SODA]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

ALTER VIEW [dbo].[V_SALESFIGO]
AS
SELECT 
    VINNERCODE,
    IDSUPPLIER,
    SUM(IQUANTITY) AS NET_SALES
FROM (
    -- Ventas 
    SELECT 
        VINNERCODE,
        IDSUPPLIER,
        IQUANTITY 
    FROM SALESFIGO WITH (NOLOCK)
    WHERE DINVOICEDATE >= DATEADD(MONTH, -12, GETDATE())
    UNION ALL
    -- Devoluciones 
    SELECT 
        VINNERCODE,
        IDSUPPLIER,
        -IQUANTITY 
    FROM RETURNSFIGO WITH (NOLOCK)
    WHERE DINVOICEDATE >= DATEADD(MONTH, -12, GETDATE())
) DATOS
GROUP BY VINNERCODE, IDSUPPLIER;
GO