ALTER TABLE SALEORDER
ADD IDCUSTOMERINVOCE INT

ALTER TABLE DISPATCHEDCONTROL
ADD IDCUSTOMERINVOICE INT 

ALTER TABLE INVOICECONTROL
ADD IDCUSTOMERINVOICE INT 

UPDATE S
SET S.IDCUSTOMERINVOICE=S.IDDEALER
FROM SALEORDER S

UPDATE S
SET S.IDCUSTOMERINVOICE=S.IDCUSTOMER
FROM DISPATCHEDCONTROL S

UPDATE S
SET S.IDCUSTOMERINVOICE=S.IDCUSTOMER
FROM INVOICECONTROL S


UPDATE CONTACT
SET VVATINVOICE='J504039039'
WHERE ID=15489

INSERT INTO [GROUP](ID,VNAME,BDEALER)
VALUES(3,'VIRTUAL',1)


UPDATE CONTACT
SET IDGROUP=3
WHERE ID IN (21307,21308,21318,21319,21320,21321,21330,21331)