USE [SODA]
GO

/****** Object:  View [dbo].[V_DEALERS]    Script Date: 06/07/2026 11:35:23 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO






ALTER VIEW [dbo].[V_DEALERS]
AS


SELECT D.ID AS IDDEALER, D.VFIRSTNAME AS DEALER, S.ID AS IDSUPPLIER, S.VFIRSTNAME AS SUPPLIER, S.IDBRAND , B.VNAME AS VBRAND,
D.VREFERENCE AS VREFERENCEDEALER,S.VREFERENCE AS VREFERENCESUPPLIER,D.VVATINVOICE, D.IDGROUP
FROM RELATED UC WITH (NOLOCK)
INNER JOIN CONTACT S WITH (NOLOCK) ON S.ID=UC.IDCONTACT
INNER JOIN CONTACT D WITH (NOLOCK) ON D.ID=UC.IDUSER
INNER JOIN BRAND B WITH (NOLOCK) ON B.ID=S.IDBRAND
WHERE 
D.BDEALER=1 AND D.BUSER=0 AND-- CONCESIONARIO
S.BSUPPLIER=1 AND S.BUSER=0 -- PLANTA RELACIONADO AL CONCESIONARIO

	
GO


