USE [SODA]
GO

/****** Object:  View [dbo].[V_SALEORDER]    Script Date: 06/07/2026 14:22:36 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO





ALTER   VIEW [dbo].[V_SALEORDER]
AS


SELECT 
S.ID,
CAST ( S.ID AS VARCHAR(10)) AS VID,
S.IDDEALER,
S.IDSUPPLIER,
S.IDESTATUS,
ISNULL(S.VREFERENCE,'') VREFERENCE,
ISNULL(S.VCOMMENT,'') VCOMMENT,
CONVERT(VARCHAR(20),S.DCREATED,120) VCREATED,
S.DUPDATED,
ISNULL(S.VCREATEDBY,'') VCREATEDBY,
S.VUPDATEDBY,
ISNULL(S.IDTYPE,0) IDTYPE,
S.BCLAIM,
S.IDVEHICLE,
S.BPARALYZED,
CASE WHEN A.VDISPLAYESTATUS = 'Asignado' THEN 'PREPARACION' 
     WHEN A.VDISPLAYESTATUS = 'Aprobado' THEN 'TRANSITO' 
     WHEN T.VNAME NOT LIKE '%RECLAMO%' AND A.VDISPLAYESTATUS = 'Procesado' AND S.BCOMPLETED=0 THEN 'RECIBIDO PARCIAL' 
     WHEN T.VNAME NOT LIKE '%RECLAMO%' AND A.VDISPLAYESTATUS = 'Procesado' AND S.BCOMPLETED=1 THEN 'RECIBIDO' 
     ELSE A.VDISPLAYESTATUS END
AS VESTATUS, 
ISNULL(T.VNAME,'') AS VTYPE,
D.DEALER AS VDEALER,X.VSUPPLIER,
S.IDCUSTOMERINVOICE,
(C.VFIRSTNAME + ISNULL(C.VLASTNAME,'')) AS VCUSTOMERINVOICE,
C.VVAT AS VCUSTOMERVAT,
D.IDGROUP
FROM SALEORDER S WITH (NOLOCK)
INNER JOIN SALEORDERTYPE T WITH (NOLOCK) ON T.ID=S.IDTYPE
INNER JOIN ACTION A WITH (NOLOCK) ON A.ID=S.IDESTATUS
INNER JOIN V_DEALERS D ON D.IDDEALER=S.IDDEALER
INNER JOIN V_SUPPLIERS X ON X.IDSUPPLIER=S.IDSUPPLIER
LEFT JOIN CONTACT C WITH (NOLOCK) ON S.IDCUSTOMERINVOICE=C.ID
GO


