CREATE TABLE RECORD 
(	
	ID INT PRIMARY KEY IDENTITY(1,1),
	VNUMBERSRAN INT,
    VVIN VARCHAR(20),
	IDMAINTENANCE INT,
	VSERVICENUMBER INT,
	IDDEALER INT,
	IESTATUS INT,
	IDSERVICETYPE INT,
	IDREPORTTYPE INT,
	KM INT,
	VSRGNUMBER VARCHAR(20),
	DCREATED DATETIME,
	DMAINTENANCEDATE INT,
	NINVOICEAMOUNT NUMERIC(10,2)
)




