USE OASIS
GO

/****** Object:  Table [dbo].[CLAIM]    Script Date: 2/5/2026 8:53:34 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[CLAIM](
	[ID] [int] IDENTITY(100,1) NOT NULL,
	[IDSUPPLIER] [int] NOT NULL,
	[IDDEALER] [int] NOT NULL,
	[IDUSER] [int] NOT NULL,
	[IDSTATUS] [int] NULL,
	[VREFERENCE] [varchar](50) NULL,
	[VNOTE] [varchar](500) NULL,
	[VCOMMENT] [varchar](max) NULL,
	[DCREATED] [datetime] NULL,
	[DUPDATED] [datetime] NULL,
	[VINVOICE] [varchar](50) NULL,
	[VGUIDE] [varchar](50) NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

ALTER TABLE [dbo].[CLAIM] ADD  CONSTRAINT [DF_CLAIM_IDSTATUS]  DEFAULT ((2)) FOR [IDSTATUS]
GO

ALTER TABLE [dbo].[CLAIM] ADD  DEFAULT (getdate()) FOR [DCREATED]
GO


