USE OASIS
GO

/****** Object:  Table [dbo].[CLAIMREASON]    Script Date: 2/5/2026 8:56:37 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[CLAIMREASON](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[VDESCRIPTION] [varchar](100) NOT NULL,
	[CTYPE] [varchar](1) NULL,
 CONSTRAINT [PK_CLAIM_REASON] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


