USE [OASIS]
GO

/****** Object:  Table [dbo].[CLAIM]    Script Date: 28/01/2026 14:30:44 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[CLAIM](
	[ID] [int] IDENTITY(100,1) NOT NULL,
	[IDSUPPLIER] [int] NOT NULL,
	[IDDEALER] [int] NOT NULL,
	[IDUSER] [int] NOT NULL,
	[IDSTATUS] [int] NULL,
	[VREFERENCE] [varchar](50) NULL,
	[VNOTE] [varchar](500) NULL,
	[VCOMMENT] [varchar](max) NULL,
	[DCREATED] [datetime] NULL,
	[DUPDATED] [datetime] NULL,
	[VINVOICE] [varchar](50) NULL,
	[VGUIDE] [varchar](50) NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

ALTER TABLE [dbo].[CLAIM] ADD  CONSTRAINT [DF_CLAIM_IDSTATUS]  DEFAULT ((2)) FOR [IDSTATUS]
GO

ALTER TABLE [dbo].[CLAIM] ADD  DEFAULT (getdate()) FOR [DCREATED]
GO

ALTER TABLE [dbo].[CLAIM]  WITH CHECK ADD  CONSTRAINT [FK_CLAIM_DEALER] FOREIGN KEY([IDDEALER])
REFERENCES [dbo].[CONTACT] ([ID])
GO

ALTER TABLE [dbo].[CLAIM] CHECK CONSTRAINT [FK_CLAIM_DEALER]
GO

ALTER TABLE [dbo].[CLAIM]  WITH CHECK ADD  CONSTRAINT [FK_CLAIM_STATUS] FOREIGN KEY([IDSTATUS])
REFERENCES [dbo].[ACTION] ([ID])
GO

ALTER TABLE [dbo].[CLAIM] CHECK CONSTRAINT [FK_CLAIM_STATUS]
GO

ALTER TABLE [dbo].[CLAIM]  WITH CHECK ADD  CONSTRAINT [FK_CLAIM_SUPPLIER] FOREIGN KEY([IDSUPPLIER])
REFERENCES [dbo].[CONTACT] ([ID])
GO

ALTER TABLE [dbo].[CLAIM] CHECK CONSTRAINT [FK_CLAIM_SUPPLIER]
GO

ALTER TABLE [dbo].[CLAIM]  WITH CHECK ADD  CONSTRAINT [FK_CLAIM_USER] FOREIGN KEY([IDUSER])
REFERENCES [dbo].[CONTACT] ([ID])
GO

ALTER TABLE [dbo].[CLAIM] CHECK CONSTRAINT [FK_CLAIM_USER]
GO


