USE [OASIS]
GO

/****** Object:  Table [dbo].[CLAIMDETAIL]    Script Date: 28/01/2026 14:31:30 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[CLAIMDETAIL](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[IDCLAIM] [int] NOT NULL,
	[IDPART] [int] NOT NULL,
	[IQUANTITY] [int] NOT NULL,
	[IDSTATUS] [int] NULL,
	[IDREPLACEMENT_PART] [int] NULL,
	[IDREASON] [int] NULL,
	[VCOMMENT] [varchar](1000) NULL,
	[IAPPROVEDQUANTITY] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[CLAIMDETAIL] ADD  CONSTRAINT [DF_CLAIM_DETAIL_IDSTATUS]  DEFAULT ((16)) FOR [IDSTATUS]
GO

ALTER TABLE [dbo].[CLAIMDETAIL]  WITH CHECK ADD  CONSTRAINT [FK_CLAIM_DETAIL_CLAIM] FOREIGN KEY([IDCLAIM])
REFERENCES [dbo].[CLAIM] ([ID])
ON DELETE CASCADE
GO

ALTER TABLE [dbo].[CLAIMDETAIL] CHECK CONSTRAINT [FK_CLAIM_DETAIL_CLAIM]
GO

ALTER TABLE [dbo].[CLAIMDETAIL]  WITH CHECK ADD  CONSTRAINT [FK_CLAIM_DETAIL_CLAIM_REASON] FOREIGN KEY([IDREASON])
REFERENCES [dbo].[CLAIMREASON] ([ID])
GO

ALTER TABLE [dbo].[CLAIMDETAIL] CHECK CONSTRAINT [FK_CLAIM_DETAIL_CLAIM_REASON]
GO

ALTER TABLE [dbo].[CLAIMDETAIL]  WITH CHECK ADD  CONSTRAINT [FK_CLAIM_DETAIL_PART] FOREIGN KEY([IDPART])
REFERENCES [dbo].[PART] ([ID])
GO

ALTER TABLE [dbo].[CLAIMDETAIL] CHECK CONSTRAINT [FK_CLAIM_DETAIL_PART]
GO

ALTER TABLE [dbo].[CLAIMDETAIL]  WITH CHECK ADD  CONSTRAINT [FK_CLAIM_DETAIL_REPLACEMENT_PART] FOREIGN KEY([IDREPLACEMENT_PART])
REFERENCES [dbo].[PART] ([ID])
GO

ALTER TABLE [dbo].[CLAIMDETAIL] CHECK CONSTRAINT [FK_CLAIM_DETAIL_REPLACEMENT_PART]
GO

ALTER TABLE [dbo].[CLAIMDETAIL]  WITH CHECK ADD  CONSTRAINT [FK_CLAIM_DETAIL_STATUS] FOREIGN KEY([IDSTATUS])
REFERENCES [dbo].[ACTION] ([ID])
GO

ALTER TABLE [dbo].[CLAIMDETAIL] CHECK CONSTRAINT [FK_CLAIM_DETAIL_STATUS]
GO


