USE OASIS
GO

/****** Object:  Table [dbo].[CLAIMDETAIL]    Script Date: 2/5/2026 8:56:05 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[CLAIMDETAIL](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[IDCLAIM] [int] NOT NULL,
	[IDPART] [int] NOT NULL,
	[IQUANTITY] [int] NOT NULL,
	[IDSTATUS] [int] NULL,
	[IDREPLACEMENT_PART] [int] NULL,
	[IDREASON] [int] NULL,
	[VCOMMENT] [varchar](1000) NULL,
	[IAPPROVEDQUANTITY] [int] NULL,
	[ITRANSACTIONQUANTITY] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[CLAIMDETAIL] ADD  CONSTRAINT [DF_CLAIM_DETAIL_IDSTATUS]  DEFAULT ((16)) FOR [IDSTATUS]
GO


