USE [SODA]
GO

/****** Object:  Table [dbo].[DMS]    Script Date: 23/12/2025 10:47:12 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[DMS](
    [ID] [INT] PRIMARY KEY IDENTITY(1,1) ,
	[SRG]  [varchar](100) NOT NULL,
	[VCODITEM]  [varchar](100) NOT NULL,
	[NBASEAMOUNT] [NUMERIC](10,2) NOT NULL,
	[VDMS] [varchar](100) NULL,
	[DDATEDMS] [datetime] NULL,
	[VPREAPPROVAL] [varchar](100) NULL,
	[DDATEPREAPPROVAL] [datetime] NULL,
	[NPAIDAMOUNT] [NUMERIC](10,2) NOT NULL,
	[DDATEFINALAPPROVAL] [datetime] NULL,
	[DCREATED] [datetime] NULL,
	[DUPDATED] [datetime] NULL,
	[VUPDATEDBY] [varchar](30) NULL,
	[IESTATUS] [INT] NULL,
	[BACTIVE] [bit] NULL,
	[BCOMPLETED] [bit] NULL,
)


CREATE TABLE [dbo].[PAIDDETAILS](
    [ID] [INT] PRIMARY KEY IDENTITY(1,1),
	[IDDMS] [INT] NOT NULL, 
	[NAMOUNT] [NUMERIC](10,2) NOT NULL,
	[DPAIDDATE] [datetime] NULL,
	[DCREATED] [datetime] NULL,
	[VUPDATEDBY] [varchar](30) NULL
	FOREIGN KEY (IDDMS) REFERENCES DMS(ID) 
)


INSERT INTO MODULE(VNAME)
VALUES('SERVICIOS-CONCILIACION SRG')

UPDATE MODULE
  SET 
      BGET=1,
	  BCREATE=1,
	  BDECLINE=1,
	  BPROCESS=1
WHERE VNAME='SERVICIOS-CONCILIACION SRG'