CREATE NONCLUSTERED INDEX IND_SALEORDERDETAIL_02 ON [dbo].[SALEORDERDETAIL] ([IDSALEORDER]) INCLUDE ([IDPART],[IREQUIRED])

CREATE NONCLUSTERED INDEX IND_SALEORDER_02 
ON SALEORDER (DCREATED) 
INCLUDE (ID, IDDEALER, IDSUPPLIER, IDESTATUS, IDTYPE);