


INSERT INTO CLAIMREASON(VDESCRIPTION,CTYPE)
SELECT 'SOBRANTE','S'

INSERT INTO CLAIMREASON(VDESCRIPTION,CTYPE)
SELECT 'FALTANTE','F'

INSERT INTO CLAIMREASON(VDESCRIPTION,CTYPE)
SELECT 'MAL ESTADO','F'

INSERT INTO CLAIMREASON(VDESCRIPTION,CTYPE)
SELECT 'NO SOLICITADO','S'

