

ALTER TABLE MODULE ADD BPRIORITIZE BIT NOT NULL DEFAULT(0)

IF NOT EXISTS (SELECT * FROM DBO.ACTION WITH (NOLOCK)
				WHERE VNAME='PRIORITIZE')
BEGIN
	INSERT INTO DBO.ACTION(ID,VNAME,VDISPLAY,VDISPLAYESTATUS)
	SELECT 27,'PRIORITIZE','Priorizar','Priorizado'
END

UPDATE MODULE
SET BPRIORITIZE=1
WHERE VNAME='INVENTARIO-PROCESOS-RECOLECCION'