UPDATE MOVEMENT
SET DGENERATED=DCREATED
WHERE VTYPE='P'


UPDATE MOVEMENTDETAILS
SET IDSTATUS=DBO.UFN_GET_ISTATUS('PROCESS')
WHERE BPROCESSED=1


UPDATE MOVEMENTDETAILS
SET IDSTATUS=DBO.UFN_GET_ISTATUS('ASSIGN')
WHERE BPROCESSED=0
AND ISNULL(IDUSER,0)>0


UPDATE MOVEMENTDETAILS
SET IDSTATUS=DBO.UFN_GET_ISTATUS('GENERATE')
WHERE BPROCESSED=0
AND ISNULL(IDUSER,0)=0