USE [SODA]
GO

/****** Object:  View [dbo].[V_BACKORDER]    Script Date: 10/03/2026 03:44:10 p. m. ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO










ALTER  VIEW [dbo].[V_BACKORDER]

AS


SELECT A.ID AS IDBACKORDER,
A.IDSUPPLIER,A.IBACKORDER,A.DCREATED,A.IDSTATUS, A.DARRIVAL,
B.IDSALEORDER,C.IDDEALER,C.IDTYPE,D.VNAME AS VTYPE,
CASE 
    WHEN F.VDISPLAYESTATUS = 'NO DISPONIBLE' THEN 'BACKORDER'
    WHEN F.VDISPLAYESTATUS = 'BORRADOR' THEN 'PENDIENTE'
    ELSE F.VDISPLAYESTATUS 
END AS VDISPLAYESTATUS
,G.DEALER, G.VREFERENCEDEALER, G.VREFERENCESUPPLIER,  
H.VINNERCODE,H.VDESCRIPTION,H.ID AS IDPART,
CAST (B.IDSALEORDER AS VARCHAR(10)) AS VIDSALEORDER
FROM BACKORDER A WITH (NOLOCK)
INNER JOIN SALEORDERDETAIL B WITH (NOLOCK) ON B.ID=A.IDSALEORDERDETAIL
INNER JOIN SALEORDER C WITH (NOLOCK) ON C.ID=B.IDSALEORDER
INNER JOIN SALEORDERTYPE D WITH (NOLOCK) ON D.ID=C.IDTYPE
INNER JOIN ACTION F WITH (NOLOCK) ON F.ID=A.IDSTATUS
INNER JOIN V_DEALERS G ON G.IDDEALER=C.IDDEALER 
INNER JOIN PART H WITH (NOLOCK) ON H.ID=B.IDPART 
GO

