USE [SODA]
GO

/****** Object:  Table [dbo].[TEMPLATE]    Script Date: 25/08/2025 11:27:52 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[TEMPLATE](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[VDESCRIPTION] [varchar](50) NULL,
	[VCONTENT] [varchar](max) NULL,
	[DCREATED] [datetime] NULL,
	[DUPDATED] [datetime] NULL,
	[VUPDATEDBY] [varchar](20) NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO


