USE [OASIS]
GO

/****** Object:  Table [dbo].[BANK]    Script Date: 01/06/2026 11:03:56 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[DESTINYBANK](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[VCODE] [varchar](4) NULL,
	[VNAME] [varchar](50) NULL,
	[BACTIVE] [bit] NULL,
	[VVAT] [VARCHAR](20) NULL
 CONSTRAINT [PK_DESTINYBANK] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

