USE [FIGO]
GO
/****** Object:  StoredProcedure [dbo].[USP_GET_PAYMENTDETAILS_CONSOLIDATED]    Script Date: 02/06/2026 15:21:48 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

ALTER PROCEDURE [dbo].[USP_GET_PAYMENT_RECEIPT] -- [USP_GET_PAYMENT_RECEIPT] 'J500250495',1
@VSUPPLIERVAT VARCHAR(12),
@BPROFORMA BIT 
AS
/* '===============================================================          
  '   NOMBRE                : 
  '   FECHA CREACIÓN        : 
  '   CREADO POR            : JUAN GUARECUCO
  '   CREADO PARA           : 
  '   FUNCIÓN               :  
  '   VERSIÓN               : 
  '   MODIFICADO EN         : 
  '   MODIFICADO POR        :  
  '   RAZÓN DE MODIFICACIÓN : 
  '===============================================================*/

SET XACT_ABORT ON               
SET NOCOUNT ON
SET LOCK_TIMEOUT 180000

	DECLARE  @IDSUPPLIER INT

	SET @IDSUPPLIER= (SELECT IDSUPPLIER FROM V_SUPPLIERS WHERE VVAT=@VSUPPLIERVAT) 

	
  IF @BPROFORMA=0
BEGIN
	WITH 
		T1 AS (
			SELECT DISTINCT
				PM.IDPAYMENT,
				VS.VVAT AS VSUPPLIERVAT,
				V.VVATINVOICE AS VDEALERVAT,
				P.DCREATED AS DDATE,
				'USD' AS VCURRENCY,
				'RCO' AS VDOCUMENTTYPE 
			FROM PAYMENT P WITH (NOLOCK)
			INNER JOIN  PAYMENTDETAILS  PM WITH (NOLOCK) ON PM.IDPAYMENT=P.ID 
			INNER JOIN CURRENCY C WITH (NOLOCK) ON PM.IDCURRENCY=C.ID
			INNER JOIN PAYMENTTYPE PT WITH (NOLOCK) ON PM.IDTYPE=PT.ID
			LEFT JOIN BANKACCOUNT BA WITH (NOLOCK) ON PM.IDBANKACCOUNT=BA.ID
			LEFT JOIN DESTINYBANK B WITH (NOLOCK) ON BA.IDBANK=B.ID
			LEFT JOIN BANK BO WITH (NOLOCK) ON PM.IDBANKORIGIN=BO.ID
			INNER JOIN ACTION A WITH (NOLOCK) ON PM.IDSTATUS=A.ID
			INNER JOIN V_DEALERS V ON P.IDDEALER=V.IDDEALER
			INNER JOIN V_SUPPLIERS VS ON P.IDSUPPLIER=VS.IDSUPPLIER
			WHERE 
			P.IDSUPPLIER = @IDSUPPLIER
			AND P.BASINC=0
			AND P.VCONCEPT IN ('P','I','I-P','B')
			AND PM.IDSTATUS = DBO.UFN_GET_ISTATUS('APPROVE')
			AND P.VTYPE <>'P'
			AND NOT EXISTS (
			SELECT 1 
			FROM PAYMENTDETAILS PM2 WITH (NOLOCK)
			WHERE PM2.IDPAYMENT = PM.IDPAYMENT
			AND PM2.IDSTATUS  IN ( DBO.UFN_GET_ISTATUS('CREATE'),DBO.UFN_GET_ISTATUS('TOAPPROVE'))
    )
            
			
		)
		 -- 5. PAGINAR 
		SELECT T1.* 
		FROM T1
        ORDER BY T1.DDATE
END
ELSE 
	BEGIN
		WITH 
			T1 AS (
					SELECT DISTINCT
						PM.IDPAYMENT,
						VS.VVAT AS VSUPPLIERVAT,
						V.VVATINVOICE AS VDEALERVAT,
						P.DCREATED AS DDATE,
						'USD' AS VCURRENCY,
						'RCO' AS VDOCUMENTTYPE 
					FROM PAYMENTDETAILS PM WITH (NOLOCK)
					INNER JOIN PAYMENT P WITH (NOLOCK) ON PM.IDPAYMENT=P.ID
					INNER JOIN PAYMENTTYPE PT WITH (NOLOCK) ON PM.IDTYPE=PT.ID
					INNER JOIN V_DEALERS V ON P.IDDEALER=V.IDDEALER
					INNER JOIN V_SUPPLIERS VS ON P.IDSUPPLIER=VS.IDSUPPLIER
					WHERE 
					P.IDSUPPLIER = @IDSUPPLIER
					AND P.BASINC=0
					AND P.VCONCEPT IN ('B')
					AND P.VTYPE ='P'
					AND PM.IDSTATUS = DBO.UFN_GET_ISTATUS('APPROVE')
					AND NOT EXISTS (
					SELECT 1 
					FROM PAYMENTDETAILS PM2 WITH (NOLOCK)
					WHERE PM2.IDPAYMENT = PM.IDPAYMENT
					AND PM2.IDSTATUS  IN ( DBO.UFN_GET_ISTATUS('CREATE'),DBO.UFN_GET_ISTATUS('TOAPPROVE'))
			)
            
			
				)
					-- 5. PAGINAR 
				SELECT T1.* 
				FROM T1
				ORDER BY T1.DDATE
END