SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[BANKSTATEMENT](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[IDSUPPLIER] [int] NULL,
	[DTRANSDATE] [date] NULL,
	[VBANKCODE] [varchar](4) NULL,
	[VBANKACCOUNT] [varchar](25) NULL,
	[VREFERENCE] [varchar](10) NULL,
	[NAMOUNT] [decimal](18, 2) NULL,
	[IDPAYMENTDETAIL] [int] NOT NULL,
	[DCREATED] [datetime] NULL,
 CONSTRAINT [PK_BANKSTATEMENT] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[BANKSTATEMENT] ADD  CONSTRAINT [DF_BANKSTATEMENT_IDPAYMENTDETAIL]  DEFAULT ((0)) FOR [IDPAYMENTDETAIL]
GO


