SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[BANKSTATEMENT](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[IDSUPPLIER] [int] NULL,
	[DTRANSDATE] [datetime] NULL,
	[VBANKNAME] [varchar](50) NULL,
	[VBANKCODE] [varchar](25) NULL,
	[VREFERENCE] [varchar](10) NULL,
	[NAMOUNT] [decimal](18, 2) NULL,
	[IDPAYMENTDETAIL] [int] NULL,
 CONSTRAINT [PK_BANKSTATEMENT] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


