SET ANSI_PADDING ON
GO

CREATE NONCLUSTERED INDEX [IND_ACCOUNTRECEIVABLE_01] ON [dbo].[ACCOUNTRECEIVABLE]
(
	[IDSUPPLIER] ASC,
	[IDDEALER] ASC,
	[VTYPE] ASC,
	[VCONCEPT] ASC,
	[IDSTATUS] ASC,
	[DDATE] ASC,
	[VNUMBER] ASC
)
INCLUDE([VREFERENCE],[DDUEDATE],[NAMOUNT],[NBALANCE],[NRATE]) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO


