SET ANSI_PADDING ON
GO

CREATE NONCLUSTERED INDEX [IND_VEHICLE_02] ON [dbo].[VEHICLE]
(
	[VNUMBERTXT] ASC
)
INCLUDE([ID],[VVIN],[VENGINESERIAL],[VPLATE],[IDMODEL],[IDCOLOR],[IYEAR],[IDSUPPLIER],[IDDEALER],[IDCUSTOMER],[ICERTIFICATENUMBER]) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO


