SET ANSI_PADDING ON
GO

CREATE NONCLUSTERED INDEX [IND_DOCUMENTCONCEPT_01] ON [dbo].[DOCUMENTCONCEPT]
(
	[VCODE] ASC
)
INCLUDE([ID],[VNAME],[BEXCLUSIVE],[BACTIVE]) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO


