ALTER VIEW V_PAYMENTDETAILS
AS

SELECT P.ID AS IDPAYMENT,P.IDSUPPLIER,P.IDDEALER,
D.ID AS IDPAYMENTDETAIL,
CONVERT(VARCHAR(10),D.DDATE,120) AS DTRANSDATE,
B.VCODE AS VBANKCODE, A.VCODE AS VBANKACCOUNT, D.VREFERENCE,D.NAMOUNT,
D.IDSTATUS
FROM PAYMENTDETAILS D WITH (NOLOCK)
INNER JOIN PAYMENT P WITH (NOLOCK) ON P.ID=D.IDPAYMENT
INNER JOIN BANKACCOUNT A WITH (NOLOCK) ON A.ID=D.IDBANKACCOUNT
INNER JOIN BANK B WITH (NOLOCK) ON B.ID = A.IDBANK
