CREATE TABLE PAYMENT
(
	ID INT PRIMARY KEY IDENTITY,
	NAMOUNT NUMERIC (18,2),
	DCREATED DATETIME,
	VUPDATEDBY VARCHAR (12),
	IDSUPPLIER INT,
	IDDEALER INT 
);

CREATE TABLE PAYMENTDETAILS
(
	ID INT PRIMARY KEY IDENTITY,
	DDATE DATETIME,
	IDCURRENCY INT,
	IDTYPE INT,
	VREFERENCE VARCHAR (15),
	NAMOUNT NUMERIC (18,2),
	IDSTATUS INT,
	IDBANKACOUNT INT,
	IDPAYMENT INT,
	VUPDATEDBY VARCHAR (12),
	NRATE NUMERIC(18,2),
	DDATERATE DATETIME
	FOREIGN KEY (IDPAYMENT) REFERENCES PAYMENT(ID),
	FOREIGN KEY (IDTYPE) REFERENCES PAYMENTTYPE(ID),
	FOREIGN KEY (IDSTATUS) REFERENCES ACTION(ID),
);


CREATE TABLE SETTLEMENTS (
    ID INT PRIMARY KEY IDENTITY(1,1),
    IDACCOUNTRECEIVABLE INT,
    IDPAYMENT INT,
    NAMOUNTAPPLIED DECIMAL(18,2), -- La porción del pago usada para ESTA deuda
    FOREIGN KEY (IDACCOUNTRECEIVABLE) REFERENCES ACCOUNTRECEIVABLE(ID),
    FOREIGN KEY (IDPAYMENT) REFERENCES PAYMENT(ID)
);


