CREATE TABLE PAYMENT
(
	ID INT PRIMARY KEY IDENTITY,
	NAMOUNT NUMERIC (18,2),
	DCREATED DATETIME,
	VUPDATEDBY VARCHAR (12),
	IDSUPPLIER INT,
	IDDEALER INT,
	NRATE INT,
	DDATERATE DATETIME,
	VCONCEPT VARCHAR(3)
);

CREATE TABLE PAYMENTDETAILS
(
	ID INT PRIMARY KEY IDENTITY,
	DDATE DATETIME,
	IDCURRENCY INT,
	IDTYPE INT,
	VREFERENCE VARCHAR (15),
	NAMOUNT NUMERIC (18,2),
	IDSTATUS INT,
	IDBANKACOUNT INT,
	IDBANKORIGIN INT,
	IDPAYMENT INT,
	VUPDATEDBY VARCHAR (12),
	FOREIGN KEY (IDPAYMENT) REFERENCES PAYMENT(ID),
	FOREIGN KEY (IDTYPE) REFERENCES PAYMENTTYPE(ID),
	FOREIGN KEY (IDSTATUS) REFERENCES ACTION(ID),
);


CREATE TABLE SETTLEMENTS (
    ID INT PRIMARY KEY IDENTITY(1,1),
    IDACCOUNTRECEIVABLE INT,
    IDPAYMENT INT,
    FOREIGN KEY (IDACCOUNTRECEIVABLE) REFERENCES ACCOUNTRECEIVABLE(ID),
    FOREIGN KEY (IDPAYMENT) REFERENCES PAYMENT(ID)
);

INSERT INTO PAYMENTTYPE(VNAME,BACTIVE)
VALUES ('RETENCION',1)

INSERT INTO BANK(VCODE, VNAME,BACTIVE) VALUES 
('0102', 'BANCO DE VENEZUELA S.A.',1),
('0105', 'BANCO MERCANTIL, C.A.',1),
('0108', 'BBVA PROVINCIAL S.A.',1),
('0104', 'VENEZOLANO DE CREDITO S.A.',1),
('0114', 'BANCARIBE C.A.',1),
('0115', 'BANCO EXTERIOR C.A.',1),
('0128', 'BANCO CARONI C.A.',1),
('0134', 'BANESCO BANCO UNIVERSAL, C.A.',1),
('0137', 'BANCO SOFITASA C.A.',1),
('0138', 'BANCO PLAZA C.A.',1),
('0146', 'BANGENTE C.A.',1),
('0151', 'BFC BANCO FONDO COMUN C.A.',1),
('0156', '100% BANCO, C.A.',1),
('0157', 'DELSUR BANCO UNIVERSAL, C.A.',1),
('0163', 'BANCO DEL TESORO, C.A.',1),
('0166', 'BANCO AGRICOLA DE VENEZUELA, C.A.',1),
('0168', 'BANCRECER, S.A.',1),
('0169', 'MI BANCO, C.A.',1),
('0171', 'BANCO ACTIVO, C.A.',1),
('0172', 'BANCAMIGA BANCO UNIVERSAL, C.A.',1),
('0173', 'BANCO INTERNACIONAL DE DESARROLLO, C.A.',1),
('0174', 'BANPLUS BANCO UNIVERSAL, C.A.',1),
('0175', 'BANCO DIGITAL DE LOS TRABAJADORES (BDT)',1),
('0177', 'BANFANB',1),
('0178', 'N58 BANCO DIGITAL, C.A.',1),
('0191', 'BNC BANCO NACIONAL DE CREDITO, C.A.',1),
('0601', 'INSTITUTO MUNICIPAL DE CREDITO POPULAR',1);