CREATE TABLE DEMAND (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    IDPART INT NOT NULL,
    VINNERCODE VARCHAR(50) NOT NULL,
    VDESCRIPTION VARCHAR(100),
    IQUANTITY INT NOT NULL,
    DCREATED DATETIME NOT NULL,
    IDDEALER INT NOT NULL,
    IDMODEL INT NOT NULL,
    IDREASON INT NOT NULL,
);
