--AGREGAR EL CAMPO CROSDOCKING EN LA TABLA DE ZONE 
ALTER TABLE ZONE
ADD BCROSSDOCKING BIT NOT NULL;

--INSERTAR EL CAMPO SUGERIDO CROSSDOCKING PARA LOS REPORTES
SELECT * FROM REPORTING
INSERT INTO REPORTING (VNAME,IDACCESSGROUP,BACTIVE) VALUES('SUGERIDO CROSSDOCKING',1,1) 

--ACTUALIZACION PARA EL ROL DE REPORTE DE CROSSDOCKING
SELECT * FROM REPORTING
UPDATE REPORTING SET IDACCESSGROUP =56 WHERE ID = 5;


--INSERT PARA LOS MOTIVOS DE LA DEMANDA INSASTIFECHA 
INSERT INTO  DEMAND_REASON VALUES (1,'VENTA PERDIDA POR DISPONIBILIDAD'),(2,'VENTA PERDIDA POR PRECIO'); 