USE [SODA]
GO

/****** Object:  Table [dbo].[COUNTTYPE]    Script Date: 16/07/2026 11:30:29 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[COUNTTYPE](
	[ID] [int] NOT NULL,
	[VNAME] [varchar](20) NULL,
	[DCREATED] [datetime] NULL,
	[DUPDATED] [datetime] NULL,
	[VUPDATEDBY] [varchar](30) NULL,
	[BACTIVE] [bit] NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


