CREATE TABLE COUNTBYUSER
(
	ID INT IDENTITY(1,1),
	IDUSER INT,
	IDASSIGN INT,
	VASSIGNTYPE VARCHAR(1),
	IDINVENTORYCOUNT INT,
	DCREATED DATETIME,
	IDCOUNT INT,
	IDSUPPLIER INT,
    COUNTTYPE INT
)


CREATE TABLE INVENTORYCOUNT 
 (  
	ID INT IDENTITY(1,1),
    IDSUPPLIER INT,
    DPREINVENTORYDATE DATETIME,
	DINVENTORYDATE DATETIME,
	DFINISHDATE DATETIME, 
	VDESCRIPTION VARCHAR (150),
	DCREATED DATETIME,
	DPROCCESED DATETIME,
	IDCOUNTTYPE INT,
	INVENTORYCOUNTDETAIL INT,
	IDESTATUS INT,
	IDUSER INT
	)

CREATE TABLE INVENTORYCOUNTDETAIL
(
    ID  INT IDENTITY (1,1),
	IDINVENTORY INT,
	IDCOUNT INT ,
	IDLOCATION INT,
	IDPART INT,
	IQUANTITY_OLD INT,
	IQUANTITY_NEW INT,
	IDUSER INT,
	IDSTATUS INT,
	DCREATED DATETIME,
	DCOUNTDATE DATETIME,
    IDZONE INT ,
	IFORM INT,
    BBLOCK BIT
)



