INSERT INTO MODULE(VNAME,BGET,BCREATE,BEDIT,BEXPORT,BACTIVATE,BAPPROVE,BGENERATE,BPROCESS,BDECLINE)
VALUES ('INVENTARIO-CONTEO',1,1,1,1,1,1,1,1,1)

INSERT INTO COUNTTYPE(ID,VNAME,DCREATED,VUPDATEDBY,BACTIVE)
VALUES (1,'CICLICO',GETDATE(),'SYSTEM',1),
       (2,'FISICO',GETDATE(),'SYSTEM',1)

ALTER TABLE INVENTORYCOUNT 
ADD IDSUPPLIER INT,
    DPREINVENTORYDATE DATETIME,
	DINVENTORYDATE DATETIME,
	DFINISHDATE DATETIME, 
	VDESCRIPTION VARCHAR (150)