
SELECT 
    A.ID,
    CASE WHEN A.VNAME        <> B.VNAME        THEN CAST(A.VNAME        AS VARCHAR) ELSE 'OK' END AS VNAME_diff,
    CASE WHEN A.BGET         <> B.BGET         THEN CAST(A.BGET         AS VARCHAR) ELSE 'OK' END AS BGET_diff,
    CASE WHEN A.BCREATE      <> B.BCREATE      THEN CAST(A.BCREATE      AS VARCHAR) ELSE 'OK' END AS BCREATE_diff,
    CASE WHEN A.BEDIT        <> B.BEDIT        THEN CAST(A.BEDIT        AS VARCHAR) ELSE 'OK' END AS BEDIT_diff,
    CASE WHEN A.BIMPORT      <> B.BIMPORT      THEN CAST(A.BIMPORT      AS VARCHAR) ELSE 'OK' END AS BIMPORT_diff,
    CASE WHEN A.BEXPORT      <> B.BEXPORT      THEN CAST(A.BEXPORT      AS VARCHAR) ELSE 'OK' END AS BEXPORT_diff,
    CASE WHEN A.BACTIVATE    <> B.BACTIVATE    THEN CAST(A.BACTIVATE    AS VARCHAR) ELSE 'OK' END AS BACTIVATE_diff,
    CASE WHEN A.BDEACTIVATE  <> B.BDEACTIVATE  THEN CAST(A.BDEACTIVATE  AS VARCHAR) ELSE 'OK' END AS BDEACTIVATE_diff,
    CASE WHEN A.BASSIGN      <> B.BASSIGN      THEN CAST(A.BASSIGN      AS VARCHAR) ELSE 'OK' END AS BASSIGN_diff,
    CASE WHEN A.BUNASSIGN    <> B.BUNASSIGN    THEN CAST(A.BUNASSIGN    AS VARCHAR) ELSE 'OK' END AS BUNASSIGN_diff,
    CASE WHEN A.BLOCK        <> B.BLOCK        THEN CAST(A.BLOCK        AS VARCHAR) ELSE 'OK' END AS BLOCK_diff,
    CASE WHEN A.BUNLOCK      <> B.BUNLOCK      THEN CAST(A.BUNLOCK      AS VARCHAR) ELSE 'OK' END AS BUNLOCK_diff,
    CASE WHEN A.BRECEIVE     <> B.BRECEIVE     THEN CAST(A.BRECEIVE     AS VARCHAR) ELSE 'OK' END AS BRECEIVE_diff,
    CASE WHEN A.BGENERATE    <> B.BGENERATE    THEN CAST(A.BGENERATE    AS VARCHAR) ELSE 'OK' END AS BGENERATE_diff,
    CASE WHEN A.BTOVALIDATE  <> B.BTOVALIDATE  THEN CAST(A.BTOVALIDATE  AS VARCHAR) ELSE 'OK' END AS BTOVALIDATE_diff,
    CASE WHEN A.BVALIDATE    <> B.BVALIDATE    THEN CAST(A.BVALIDATE    AS VARCHAR) ELSE 'OK' END AS BVALIDATE_diff,
    CASE WHEN A.BTOAPPROVE   <> B.BTOAPPROVE   THEN CAST(A.BTOAPPROVE   AS VARCHAR) ELSE 'OK' END AS BTOAPPROVE_diff,
    CASE WHEN A.BAPPROVE     <> B.BAPPROVE     THEN CAST(A.BAPPROVE     AS VARCHAR) ELSE 'OK' END AS BAPPROVE_diff,
    CASE WHEN A.BPROCESS     <> B.BPROCESS     THEN CAST(A.BPROCESS     AS VARCHAR) ELSE 'OK' END AS BPROCESS_diff,
    CASE WHEN A.BDECLINE     <> B.BDECLINE     THEN CAST(A.BDECLINE     AS VARCHAR) ELSE 'OK' END AS BDECLINE_diff,
    CASE WHEN A.BAVAILABLE   <> B.BAVAILABLE   THEN CAST(A.BAVAILABLE   AS VARCHAR) ELSE 'OK' END AS BAVAILABLE_diff,
    CASE WHEN A.BUNAVAILABLE <> B.BUNAVAILABLE THEN CAST(A.BUNAVAILABLE AS VARCHAR) ELSE 'OK' END AS BUNAVAILABLE_diff,
    CASE WHEN A.BINVOICE     <> B.BINVOICE     THEN CAST(A.BINVOICE     AS VARCHAR) ELSE 'OK' END AS BINVOICE_diff,
    CASE WHEN A.BPRINT       <> B.BPRINT       THEN CAST(A.BPRINT       AS VARCHAR) ELSE 'OK' END AS BPRINT_diff
FROM SODA.dbo.MODULE A
JOIN OASIS.dbo.MODULE B ON A.ID = B.ID; 

