DELETE FROM [dbo].CONTACT 
WHERE ID NOT IN (1,
4069,4076)

UPDATE [ACCESSGROUPDETAIL] SET BASSIGN=1 WHERE IDACCESGROUP=1

-- ADJUSTMENTDETAILS
DELETE FROM [dbo].[ADJUSTMENTDETAILS];
DBCC CHECKIDENT ('ADJUSTMENTDETAILS', RESEED, 0);

-- ADJUSTMENT
DELETE FROM [dbo].[ADJUSTMENT];
DBCC CHECKIDENT ('ADJUSTMENT', RESEED, 0);

-- ATTACHMENT (manteniendo IDs específicos)
DELETE FROM [dbo].[ATTACHMENT] WHERE ID NOT IN (54,55,57,58);

-- AUDIT
DELETE FROM [dbo].[AUDIT];
DBCC CHECKIDENT ('AUDIT', RESEED, 0);

-- BACKORDER
DELETE FROM [dbo].[BACKORDER];
DBCC CHECKIDENT ('BACKORDER', RESEED, 0);

-- COMMENT
DELETE FROM [dbo].[COMMENT];
DBCC CHECKIDENT ('COMMENT', RESEED, 0);

-- DISPATCHEDCONTROL
DELETE FROM [dbo].[DISPATCHEDCONTROL];
DBCC CHECKIDENT ('DISPATCHEDCONTROL', RESEED, 0);

-- GUIDEDETAILS
DELETE FROM [dbo].[GUIDEDETAILS];
DBCC CHECKIDENT ('GUIDEDETAILS', RESEED, 0);

-- GUIDE
DELETE FROM [dbo].[GUIDE];
DBCC CHECKIDENT ('GUIDE', RESEED, 0);

-- INVENTORY
DELETE FROM [dbo].[INVENTORY];
DBCC CHECKIDENT ('INVENTORY', RESEED, 0);

-- INVOICECONTROL
DELETE FROM [dbo].[INVOICECONTROL];
DBCC CHECKIDENT ('INVOICECONTROL', RESEED, 0);

-- LABORTIME
DELETE FROM [dbo].[LABORTIME];
DBCC CHECKIDENT ('LABORTIME', RESEED, 0);

-- ITEM
DELETE FROM [dbo].[ITEM];
DBCC CHECKIDENT ('ITEM', RESEED, 0);

-- LEVELUSER (manteniendo IDUSER=1)
DELETE FROM [dbo].[LEVELUSER] WHERE IDUSER<>1;
DBCC CHECKIDENT ('LEVELUSER', RESEED, 0);

-- LICENSE
DELETE FROM [dbo].[LICENSE];
DBCC CHECKIDENT ('LICENSE', RESEED, 0);

-- LICENSEDETAILS
DELETE FROM [dbo].[LICENSEDETAILS];
DBCC CHECKIDENT ('LICENSEDETAILS', RESEED, 0);

-- LOCATION
DELETE FROM [dbo].[LOCATION];
DBCC CHECKIDENT ('LOCATION', RESEED, 0);

-- MAINTENANCEDETAILS
DELETE FROM [dbo].[MAINTENANCEDETAILS];
DBCC CHECKIDENT ('MAINTENANCEDETAILS', RESEED, 0);

-- MAINTENANCE
DELETE FROM [dbo].[MAINTENANCE];
DBCC CHECKIDENT ('MAINTENANCE', RESEED, 0);

-- MODEL
DELETE FROM [dbo].[MODEL];
DBCC CHECKIDENT ('MODEL', RESEED, 0);

-- MOVEMENTDETAILS
DELETE FROM [dbo].[MOVEMENTDETAILS];
DBCC CHECKIDENT ('MOVEMENTDETAILS', RESEED, 0);

-- MOVEMENT
DELETE FROM [dbo].[MOVEMENT];
DBCC CHECKIDENT ('MOVEMENT', RESEED, 0);

-- MOVEMENTDETAILSPACKAGED
DELETE FROM [dbo].[MOVEMENTDETAILSPACKAGED];
DBCC CHECKIDENT ('MOVEMENTDETAILSPACKAGED', RESEED, 0);

-- PACKAGE
DELETE FROM [dbo].[PACKAGE];
DBCC CHECKIDENT ('PACKAGE', RESEED, 0);

-- PACKAGEDETAIL
DELETE FROM [dbo].[PACKAGEDETAIL];
DBCC CHECKIDENT ('PACKAGEDETAIL', RESEED, 0);

-- PART
DELETE FROM [dbo].[PART];
DBCC CHECKIDENT ('PART', RESEED, 0);

-- PARTMODEL
DELETE FROM [dbo].[PARTMODEL];
DBCC CHECKIDENT ('PARTMODEL', RESEED, 0);

-- POLICYDETAILS
DELETE FROM [dbo].[POLICYDETAILS];
DBCC CHECKIDENT ('POLICYDETAILS', RESEED, 0);

-- POLICY
DELETE FROM [dbo].[POLICY];
DBCC CHECKIDENT ('POLICY', RESEED, 0);

-- POLICYTYPE
DELETE FROM [dbo].[POLICYTYPE];
DBCC CHECKIDENT ('POLICYTYPE', RESEED, 0);

-- PRINTQUEUE
DELETE FROM [dbo].[PRINTQUEUE];
DBCC CHECKIDENT ('PRINTQUEUE', RESEED, 0);

-- REMINDER
DELETE FROM [dbo].[REMINDER];
DBCC CHECKIDENT ('REMINDER', RESEED, 0);

-- SALEORDERDETAIL
DELETE FROM [dbo].[SALEORDERDETAIL];
DBCC CHECKIDENT ('SALEORDERDETAIL', RESEED, 0);

-- SALEORDER
DELETE FROM [dbo].[SALEORDER];
DBCC CHECKIDENT ('SALEORDER', RESEED, 0);

-- VEHICLE
DELETE FROM [dbo].[VEHICLE];
DBCC CHECKIDENT ('VEHICLE', RESEED, 0);

-- WAREHOUSE
DELETE FROM [dbo].[WAREHOUSE];
DBCC CHECKIDENT ('WAREHOUSE', RESEED, 0);

-- ZONE
DELETE FROM [dbo].[ZONE];
DBCC CHECKIDENT ('ZONE', RESEED, 0);


