-- 1. CATÁLOGO DE TIPOS (ya existe implícitamente, solo formalizarla)
CREATE TABLE [dbo].[FEATUREVALUETYPE] (
    [ID]    INT IDENTITY(1,1) NOT NULL,
    [VNAME] VARCHAR(50)       NOT NULL,   
    PRIMARY KEY ([ID])
)
INSERT INTO [dbo].[FEATUREVALUETYPE] VALUES ('Sí / No')             -- ID=1
INSERT INTO [dbo].[FEATUREVALUETYPE] VALUES ('Selección Simple')    -- ID=2 


-- 2. FEATURE (ya existe, solo agregar IDTYPE si no lo tienes)
ALTER TABLE FEATURE ADD IDFEATUREVALUETYPE INT 

ALTER TABLE [dbo].[FEATURE]
    ADD CONSTRAINT FK_FEATURE_VALUETYPE 
    FOREIGN KEY ([IDFEATUREVALUETYPE]) REFERENCES [dbo].[FEATUREVALUETYPE]([ID])
    

-- 3. OPCIONES DE LA FEATURE
CREATE TABLE [dbo].[FEATUREOPTION] (
    [ID]         INT IDENTITY(1,1) NOT NULL,
    [IDFEATURE]  INT          NOT NULL,
    [VNAME]      VARCHAR(100) NOT NULL,
    [IORDER]     INT          NOT NULL DEFAULT 0,
    [BACTIVE]    BIT          NOT NULL DEFAULT 1,
    [IDSUPPLIER] INT          NOT NULL,
    [IDDEALER]   INT          NULL,
    PRIMARY KEY ([ID]),
    FOREIGN KEY ([IDFEATURE])  REFERENCES [dbo].[FEATURE]([ID]),
    FOREIGN KEY ([IDSUPPLIER]) REFERENCES [dbo].[CONTACT]([ID]),
    FOREIGN KEY ([IDDEALER])   REFERENCES [dbo].[CONTACT]([ID])
)