--ALTERS
ALTER TABLE AREA ALTER COLUMN IDDEALER INT NULL
ALTER TABLE FASE ALTER COLUMN IDDEALER INT NULL
ALTER TABLE FEATURETYPE ALTER COLUMN IDDEALER INT NULL
ALTER TABLE FEATURE ALTER COLUMN IDDEALER INT NULL
ALTER TABLE AREA ADD IDACCESSGROUP INT, CONSTRAINT FK_AREA_ACCESSGROUP FOREIGN KEY (IDACCESSGROUP) REFERENCES ACCESSGROUP(ID);

--MODULO INSPECTION
INSERT INTO MODULE (VNAME, BGET, BCREATE, BEDIT, BACTIVATE, BDEACTIVATE) 
VALUES ('INSPECCION-AREA', 1, 1, 1, 1, 1);
INSERT INTO MODULE (VNAME, BGET, BCREATE, BEDIT, BACTIVATE, BDEACTIVATE) 
VALUES ('INSPECCION-FASE', 1, 1, 1, 1, 1);
INSERT INTO MODULE (VNAME, BGET, BCREATE, BEDIT, BACTIVATE, BDEACTIVATE) 
VALUES ('INSPECCION-TIPOS-CARACTERISTICAS', 1, 1, 1, 1, 1);
INSERT INTO MODULE (VNAME, BGET, BCREATE, BEDIT, BACTIVATE, BDEACTIVATE) 
VALUES ('INSPECCION-CARACTERISTICAS', 1, 1, 1, 1, 1);
INSERT INTO MODULE (VNAME, BGET) 
VALUES ('INSPECCION-INSPECCION', 1);


