CREATE TABLE FEATURE (
	ID INT IDENTITY(1,1) PRIMARY KEY,
	VNAME varchar(100) not null,
	BACTIVE BIT not null default 1,
	BDEFAULT BIT,
	IDFEATURETYPE int not null,
	IDMODEL int not null,
	DCREATED DATETIME NOT NULL DEFAULT GETDATE(),
	DUPDATED DATETIME NOT NULL DEFAULT GETDATE(),
	IDDEALER INT NOT NULL,
	IDSUPPLIER INT NOT NULL,
	VUPDATEDBY VARCHAR(20),
	-- LLAVES FORANEAS
	FOREIGN KEY (IDFEATURETYPE) REFERENCES FEATURETYPE(ID),
	FOREIGN KEY (IDMODEL) REFERENCES MODEL(ID),
	FOREIGN KEY ([IDSUPPLIER]) REFERENCES [dbo].[CONTACT]([ID]),
    FOREIGN KEY ([IDDEALER])   REFERENCES [dbo].[CONTACT]([ID])
);