CREATE TABLE FEATURETYPE (
	ID INT IDENTITY(1,1) PRIMARY KEY,
	VNAME VARCHAR(100) NOT NULL,
	BACTIVE BIT NOT NULL DEFAULT 1,
	IDFASE INT NOT NULL,
	DCREATED DATETIME NOT NULL DEFAULT GETDATE(),
	DUPDATED DATETIME NOT NULL DEFAULT GETDATE(),
	IDDEALER INT NOT NULL,
	IDSUPPLIER INT NOT NULL,
	VUPDATEDBY VARCHAR(20)
	-- LLAVES FORANEAS
	FOREIGN KEY (IDFASE) REFERENCES FASE(ID),
	FOREIGN KEY ([IDSUPPLIER]) REFERENCES [dbo].[CONTACT]([ID]),
    FOREIGN KEY ([IDDEALER])   REFERENCES [dbo].[CONTACT]([ID])
);