CREATE TABLE FASE (
	ID INT IDENTITY(1, 1) primary key,
	VNAME VARCHAR(100) not null,
	IORDERBY int not null,
	BACTIVE BIT NOT NULL DEFAULT 1,
	IDAREA INT NOT NULL,
	DCREATED DATETIME NOT NULL DEFAULT GETDATE(),
	DUPDATED DATETIME NOT NULL DEFAULT GETDATE(),
	IDDEALER INT NOT NULL,
	IDSUPPLIER INT NOT NULL,
	VUPDATEDBY VARCHAR(20)
	-- LLAVES FORANEAS
	FOREIGN KEY (IDAREA) REFERENCES AREA(ID),
	FOREIGN KEY ([IDSUPPLIER]) REFERENCES [dbo].[CONTACT]([ID]),
    FOREIGN KEY ([IDDEALER])   REFERENCES [dbo].[CONTACT]([ID])
);