CREATE TABLE AREA (
	ID INT IDENTITY (1,1) PRIMARY KEY,
	VNAME VARCHAR(100) NOT NULL,
	BACTIVE BIT NOT NULL DEFAULT 1,
	DCREATED DATETIME NOT NULL DEFAULT GETDATE(),
	DUPDATED DATETIME NOT NULL DEFAULT GETDATE(),
	IDDEALER INT NOT NULL,
	IDSUPPLIER INT NOT NULL,
	VUPDATEDBY VARCHAR(20),
	FOREIGN KEY ([IDSUPPLIER]) REFERENCES [dbo].[CONTACT]([ID]),
    FOREIGN KEY ([IDDEALER])   REFERENCES [dbo].[CONTACT]([ID])
);