
--AGREGAR CAMPO DEL ID DE MUNICIPIO EN LA TABLA DE CIUDAD
ALTER TABLE CITY ADD ID_MUNICIPALITY INT NULL;


--MODIFICACIONDES DE LA TABLA CIUDAD PARA AGREGAR CIDADES FALTANTES Y ASIGNAR LOS VALORES CORRESPONDIENTES A CADA CIUDAD EXISTENTENTE EN LA TABLA

--AMAZONAS
UPDATE CITY SET ID_MUNICIPALITY = 3 WHERE ID = 1;

INSERT INTO CITY (VNAME, VSTATE, ID_MUNICIPALITY, DCREATED, DUPDATED) VALUES ('LA ESMERALDA', 'AMAZONAS', 1, GETDATE(), GETDATE());
INSERT INTO CITY (VNAME, VSTATE, ID_MUNICIPALITY, DCREATED, DUPDATED) VALUES ('SAN FERNANDO DE APURE', 'AMAZONAS', 2, GETDATE(), GETDATE());
INSERT INTO CITY (VNAME, VSTATE, ID_MUNICIPALITY, DCREATED, DUPDATED) VALUES ('ISLA RATON', 'AMAZONAS', 4, GETDATE(), GETDATE());
INSERT INTO CITY (VNAME, VSTATE, ID_MUNICIPALITY, DCREATED, DUPDATED) VALUES ('SAN JUAN DE MANAPIARE', 'AMAZONAS', 5, GETDATE(), GETDATE());
INSERT INTO CITY (VNAME, VSTATE, ID_MUNICIPALITY, DCREATED, DUPDATED) VALUES ('MAROA', 'AMAZONAS', 6, GETDATE(), GETDATE());
INSERT INTO CITY (VNAME, VSTATE, ID_MUNICIPALITY, DCREATED, DUPDATED) VALUES ('SAN CARLOS DE RIO NEGRO', 'AMAZONAS', 7, GETDATE(), GETDATE());

--ANZOATEGUI
UPDATE CITY SET ID_MUNICIPALITY = 27 WHERE ID = 2;
UPDATE CITY SET ID_MUNICIPALITY = 17 WHERE ID = 3;
UPDATE CITY SET ID_MUNICIPALITY = 28 WHERE ID = 4;
UPDATE CITY SET ID_MUNICIPALITY = 8 WHERE ID = 5;
UPDATE CITY SET ID_MUNICIPALITY = 10 WHERE ID = 6;
UPDATE CITY SET ID_MUNICIPALITY = 22 WHERE ID = 7;

INSERT INTO CITY (VNAME, VSTATE, ID_MUNICIPALITY, DCREATED, DUPDATED) VALUES ('ARAGUA DE BARCELONA', 'ANZO�TEGUI', 9, GETDATE(), GETDATE());
INSERT INTO CITY (VNAME, VSTATE, ID_MUNICIPALITY, DCREATED, DUPDATED) VALUES ('PARIAGUAN', 'ANZO�TEGUI', 11, GETDATE(), GETDATE());
INSERT INTO CITY (VNAME, VSTATE, ID_MUNICIPALITY, DCREATED, DUPDATED) VALUES ('VALLE DE GUANAPE', 'ANZO�TEGUI', 12, GETDATE(), GETDATE());
INSERT INTO CITY (VNAME, VSTATE, ID_MUNICIPALITY, DCREATED, DUPDATED) VALUES ('EL CHAPARRO', 'ANZO�TEGUI', 13, GETDATE(), GETDATE());
INSERT INTO CITY (VNAME, VSTATE, ID_MUNICIPALITY, DCREATED, DUPDATED) VALUES ('GAUNTA', 'ANZO�TEGUI', 14, GETDATE(), GETDATE());
INSERT INTO CITY (VNAME, VSTATE, ID_MUNICIPALITY, DCREATED, DUPDATED) VALUES ('SOLEDAD', 'ANZO�TEGUI', 15, GETDATE(), GETDATE());
INSERT INTO CITY (VNAME, VSTATE, ID_MUNICIPALITY, DCREATED, DUPDATED) VALUES ('MAPIRE', 'ANZO�TEGUI', 16, GETDATE(), GETDATE());
INSERT INTO CITY (VNAME, VSTATE, ID_MUNICIPALITY, DCREATED, DUPDATED) VALUES ('ONOTO', 'ANZO�TEGUI', 18, GETDATE(), GETDATE());
INSERT INTO CITY (VNAME, VSTATE, ID_MUNICIPALITY, DCREATED, DUPDATED) VALUES ('SAN MATEO', 'ANZO�TEGUI', 19, GETDATE(), GETDATE());
INSERT INTO CITY (VNAME, VSTATE, ID_MUNICIPALITY, DCREATED, DUPDATED) VALUES ('CALRINES', 'ANZO�TEGUI', 20, GETDATE(), GETDATE());
INSERT INTO CITY (VNAME, VSTATE, ID_MUNICIPALITY, DCREATED, DUPDATED) VALUES ('CANTAURA', 'ANZO�TEGUI', 21, GETDATE(), GETDATE());
INSERT INTO CITY (VNAME, VSTATE, ID_MUNICIPALITY, DCREATED, DUPDATED) VALUES ('PIRITU', 'ANZO�TEGUI', 23, GETDATE(), GETDATE());
INSERT INTO CITY (VNAME, VSTATE, ID_MUNICIPALITY, DCREATED, DUPDATED) VALUES ('SAN JOSE DE GUANIPA', 'ANZO�TEGUI', 24, GETDATE(), GETDATE());
INSERT INTO CITY (VNAME, VSTATE, ID_MUNICIPALITY, DCREATED, DUPDATED) VALUES ('BOCA DE UCHIRE', 'ANZO�TEGUI', 25, GETDATE(), GETDATE());
INSERT INTO CITY (VNAME, VSTATE, ID_MUNICIPALITY, DCREATED, DUPDATED) VALUES ('SANTA ANA', 'ANZO�TEGUI', 26, GETDATE(), GETDATE());


--APURE
UPDATE CITY SET ID_MUNICIPALITY = 35 WHERE ID = 8;
UPDATE CITY SET ID_MUNICIPALITY = 32 WHERE ID = 9;

INSERT INTO CITY (VNAME, VSTATE, ID_MUNICIPALITY, DCREATED, DUPDATED) VALUES ('ACHAGUAS', 'APURE', 29, GETDATE(), GETDATE());
INSERT INTO CITY (VNAME, VSTATE, ID_MUNICIPALITY, DCREATED, DUPDATED) VALUES ('BIRUACA', 'APURE', 30, GETDATE(), GETDATE());
INSERT INTO CITY (VNAME, VSTATE, ID_MUNICIPALITY, DCREATED, DUPDATED) VALUES ('BRUZUAL', 'APURE', 31, GETDATE(), GETDATE());
INSERT INTO CITY (VNAME, VSTATE, ID_MUNICIPALITY, DCREATED, DUPDATED) VALUES ('SAN JUAN DE PAYARA', 'APURE', 33, GETDATE(), GETDATE());
INSERT INTO CITY (VNAME, VSTATE, ID_MUNICIPALITY, DCREATED, DUPDATED) VALUES ('ELORZA', 'APURE', 34, GETDATE(), GETDATE());

--ARAGUA	
UPDATE CITY SET ID_MUNICIPALITY = 48 WHERE ID = 10;
UPDATE CITY SET ID_MUNICIPALITY = 41 WHERE ID = 11;
UPDATE CITY SET ID_MUNICIPALITY = 39 WHERE ID = 12;
UPDATE CITY SET ID_MUNICIPALITY = 43 WHERE ID = 13;
UPDATE CITY SET ID_MUNICIPALITY = 53 WHERE ID = 14;
UPDATE CITY SET ID_MUNICIPALITY = 50 WHERE ID = 15;
UPDATE CITY SET ID_MUNICIPALITY = 44 WHERE ID = 16;
UPDATE CITY SET ID_MUNICIPALITY = 36 WHERE ID = 17;
UPDATE CITY SET ID_MUNICIPALITY = 40 WHERE ID = 18;

INSERT INTO CITY (VNAME, VSTATE, ID_MUNICIPALITY, DCREATED, DUPDATED) VALUES ('SAN MATEO', 'ARAGUA', 37, GETDATE(), GETDATE());
INSERT INTO CITY (VNAME, VSTATE, ID_MUNICIPALITY, DCREATED, DUPDATED) VALUES ('CAMATAGUA', 'ARAGUA', 38, GETDATE(), GETDATE());
INSERT INTO CITY (VNAME, VSTATE, ID_MUNICIPALITY, DCREATED, DUPDATED) VALUES ('EL CONSEJO', 'ARAGUA', 42, GETDATE(), GETDATE());
INSERT INTO CITY (VNAME, VSTATE, ID_MUNICIPALITY, DCREATED, DUPDATED) VALUES ('OCUMARE DE LA COSTA', 'ARAGUA', 45, GETDATE(), GETDATE());
INSERT INTO CITY (VNAME, VSTATE, ID_MUNICIPALITY, DCREATED, DUPDATED) VALUES ('SAN CASIMIRO', 'ARAGUA', 46, GETDATE(), GETDATE());
INSERT INTO CITY (VNAME, VSTATE, ID_MUNICIPALITY, DCREATED, DUPDATED) VALUES ('SAN SEBASTIAN DE LOS REYES', 'ARAGUA', 47, GETDATE(), GETDATE());
INSERT INTO CITY (VNAME, VSTATE, ID_MUNICIPALITY, DCREATED, DUPDATED) VALUES ('LAS TEJERIAS', 'ARAGUA', 49, GETDATE(), GETDATE());
INSERT INTO CITY (VNAME, VSTATE, ID_MUNICIPALITY, DCREATED, DUPDATED) VALUES ('COLONIA TOVAR', 'ARAGUA', 51, GETDATE(), GETDATE());
INSERT INTO CITY (VNAME, VSTATE, ID_MUNICIPALITY, DCREATED, DUPDATED) VALUES ('BARBACOAS', 'ARAGUA', 52, GETDATE(), GETDATE());

--BARINAS
UPDATE CITY SET ID_MUNICIPALITY = 58 WHERE ID = 19;
UPDATE CITY SET ID_MUNICIPALITY = 56 WHERE ID = 20;

INSERT INTO CITY (VNAME, VSTATE, ID_MUNICIPALITY, DCREATED, DUPDATED) VALUES ('SABANETA', 'BARINAS', 54, GETDATE(), GETDATE());
INSERT INTO CITY (VNAME, VSTATE, ID_MUNICIPALITY, DCREATED, DUPDATED) VALUES ('EL CANTON', 'BARINAS', 55, GETDATE(), GETDATE());
INSERT INTO CITY (VNAME, VSTATE, ID_MUNICIPALITY, DCREATED, DUPDATED) VALUES ('ARISMENDI', 'BARINAS', 57, GETDATE(), GETDATE());
INSERT INTO CITY (VNAME, VSTATE, ID_MUNICIPALITY, DCREATED, DUPDATED) VALUES ('BARINITAS', 'BARINAS', 59, GETDATE(), GETDATE());
INSERT INTO CITY (VNAME, VSTATE, ID_MUNICIPALITY, DCREATED, DUPDATED) VALUES ('BARRANCAS', 'BARINAS', 60, GETDATE(), GETDATE());
INSERT INTO CITY (VNAME, VSTATE, ID_MUNICIPALITY, DCREATED, DUPDATED) VALUES ('SANTA BARBARA', 'BARINAS', 61, GETDATE(), GETDATE());
INSERT INTO CITY (VNAME, VSTATE, ID_MUNICIPALITY, DCREATED, DUPDATED) VALUES ('OBISPOS', 'BARINAS', 62, GETDATE(), GETDATE());
INSERT INTO CITY (VNAME, VSTATE, ID_MUNICIPALITY, DCREATED, DUPDATED) VALUES ('CIUDAD BOLIVIA', 'BARINAS', 63, GETDATE(), GETDATE());
INSERT INTO CITY (VNAME, VSTATE, ID_MUNICIPALITY, DCREATED, DUPDATED) VALUES ('LIBERTAD', 'BARINAS', 64, GETDATE(), GETDATE());
INSERT INTO CITY (VNAME, VSTATE, ID_MUNICIPALITY, DCREATED, DUPDATED) VALUES ('CIUDAD DE NUTRIAS', 'BARINAS', 65, GETDATE(), GETDATE());

--BOLIVAR
UPDATE CITY SET ID_MUNICIPALITY = 67 WHERE ID = 21;
UPDATE CITY SET ID_MUNICIPALITY = 71 WHERE ID = 22;

INSERT INTO CITY (VNAME, VSTATE, ID_MUNICIPALITY, DCREATED, DUPDATED) VALUES ('CIUDAD PIAR', 'BOLÍVAR', 66, GETDATE(), GETDATE());
INSERT INTO CITY (VNAME, VSTATE, ID_MUNICIPALITY, DCREATED, DUPDATED) VALUES ('CAICARA DEL ORINOCO', 'BOLÍVAR', 68, GETDATE(), GETDATE());
INSERT INTO CITY (VNAME, VSTATE, ID_MUNICIPALITY, DCREATED, DUPDATED) VALUES ('EL CALLAO', 'BOLÍVAR', 69, GETDATE(), GETDATE());
INSERT INTO CITY (VNAME, VSTATE, ID_MUNICIPALITY, DCREATED, DUPDATED) VALUES ('SANTA ELENA DE UAIREN', 'BOLÍVAR', 70, GETDATE(), GETDATE());
INSERT INTO CITY (VNAME, VSTATE, ID_MUNICIPALITY, DCREATED, DUPDATED) VALUES ('EL PALMAR', 'BOLÍVAR', 72, GETDATE(), GETDATE());
INSERT INTO CITY (VNAME, VSTATE, ID_MUNICIPALITY, DCREATED, DUPDATED) VALUES ('UPATA', 'BOLÍVAR', 73, GETDATE(), GETDATE());
INSERT INTO CITY (VNAME, VSTATE, ID_MUNICIPALITY, DCREATED, DUPDATED) VALUES ('GUASIPATI', 'BOLÍVAR', 74, GETDATE(), GETDATE());
INSERT INTO CITY (VNAME, VSTATE, ID_MUNICIPALITY, DCREATED, DUPDATED) VALUES ('TUMEREMO', 'BOLÍVAR', 75, GETDATE(), GETDATE());
INSERT INTO CITY (VNAME, VSTATE, ID_MUNICIPALITY, DCREATED, DUPDATED) VALUES ('MARIPA', 'BOLÍVAR', 76, GETDATE(), GETDATE());

--CARABOBO
UPDATE CITY SET ID_MUNICIPALITY = 90 WHERE ID = 23;
UPDATE CITY SET ID_MUNICIPALITY = 87 WHERE ID = 24;
UPDATE CITY SET ID_MUNICIPALITY = 80 WHERE ID = 25;
UPDATE CITY SET ID_MUNICIPALITY = 82 WHERE ID = 26;
UPDATE CITY SET ID_MUNICIPALITY = 88 WHERE ID = 27;
UPDATE CITY SET ID_MUNICIPALITY = 83 WHERE ID = 28;
UPDATE CITY SET ID_MUNICIPALITY = 86 WHERE ID = 29;
UPDATE CITY SET ID_MUNICIPALITY = 79 WHERE ID = 30;

INSERT INTO CITY (VNAME, VSTATE, ID_MUNICIPALITY, DCREATED, DUPDATED) VALUES ('BEJUMA', 'CARABOBO', 77, GETDATE(), GETDATE());
INSERT INTO CITY (VNAME, VSTATE, ID_MUNICIPALITY, DCREATED, DUPDATED) VALUES ('GUIGUE', 'CARABOBO', 78, GETDATE(), GETDATE());
INSERT INTO CITY (VNAME, VSTATE, ID_MUNICIPALITY, DCREATED, DUPDATED) VALUES ('MORON', 'CARABOBO', 81, GETDATE(), GETDATE());
INSERT INTO CITY (VNAME, VSTATE, ID_MUNICIPALITY, DCREATED, DUPDATED) VALUES ('MIRANDA', 'CARABOBO', 84, GETDATE(), GETDATE());
INSERT INTO CITY (VNAME, VSTATE, ID_MUNICIPALITY, DCREATED, DUPDATED) VALUES ('MONTALBAN', 'CARABOBO', 85, GETDATE(), GETDATE());
INSERT INTO CITY (VNAME, VSTATE, ID_MUNICIPALITY, DCREATED, DUPDATED) VALUES ('SAN JOAQUIN', 'CARABOBO', 89, GETDATE(), GETDATE());

--COJEDES
UPDATE CITY SET ID_MUNICIPALITY = 92 WHERE ID = 31;
UPDATE CITY SET ID_MUNICIPALITY = 99 WHERE ID = 32;

INSERT INTO CITY (VNAME, VSTATE, ID_MUNICIPALITY, DCREATED, DUPDATED) VALUES ('COJEDES', 'COJEDES', 91, GETDATE(), GETDATE());
INSERT INTO CITY (VNAME, VSTATE, ID_MUNICIPALITY, DCREATED, DUPDATED) VALUES ('EL BAUL', 'COJEDES', 93, GETDATE(), GETDATE());
INSERT INTO CITY (VNAME, VSTATE, ID_MUNICIPALITY, DCREATED, DUPDATED) VALUES ('MACAPO', 'COJEDES', 94, GETDATE(), GETDATE());
INSERT INTO CITY (VNAME, VSTATE, ID_MUNICIPALITY, DCREATED, DUPDATED) VALUES ('EL PAO', 'COJEDES', 95, GETDATE(), GETDATE());
INSERT INTO CITY (VNAME, VSTATE, ID_MUNICIPALITY, DCREATED, DUPDATED) VALUES ('LIBERTAD', 'COJEDES', 96, GETDATE(), GETDATE());
INSERT INTO CITY (VNAME, VSTATE, ID_MUNICIPALITY, DCREATED, DUPDATED) VALUES ('LAS VEGAS', 'COJEDES', 97, GETDATE(), GETDATE());
INSERT INTO CITY (VNAME, VSTATE, ID_MUNICIPALITY, DCREATED, DUPDATED) VALUES ('TINACO', 'COJEDES', 98, GETDATE(), GETDATE());

--DELTA AMACURO
UPDATE CITY SET ID_MUNICIPALITY = 103 WHERE ID = 33;

INSERT INTO CITY (VNAME, VSTATE, ID_MUNICIPALITY, DCREATED, DUPDATED) VALUES ('SIERRA IMATACA', 'DELTA AMACURO', 101, GETDATE(), GETDATE());
INSERT INTO CITY (VNAME, VSTATE, ID_MUNICIPALITY, DCREATED, DUPDATED) VALUES ('CURIAPO', 'DELTA AMACURO', 100, GETDATE(), GETDATE());
INSERT INTO CITY (VNAME, VSTATE, ID_MUNICIPALITY, DCREATED, DUPDATED) VALUES ('PEDERNALES', 'DELTA AMACURO', 102, GETDATE(), GETDATE());

--FALCÓN
UPDATE CITY SET ID_MUNICIPALITY = 108 WHERE ID = 35;
UPDATE CITY SET ID_MUNICIPALITY = 118 WHERE ID = 36;

INSERT INTO CITY (VNAME, VSTATE, ID_MUNICIPALITY, DCREATED, DUPDATED) VALUES ('SAN JUAN DE LOS CAYOS', 'FALCÓN', 104, GETDATE(), GETDATE());
INSERT INTO CITY (VNAME, VSTATE, ID_MUNICIPALITY, DCREATED, DUPDATED) VALUES ('SAN LUIS', 'FALCÓN', 105, GETDATE(), GETDATE());
INSERT INTO CITY (VNAME, VSTATE, ID_MUNICIPALITY, DCREATED, DUPDATED) VALUES ('CAPATARIDA', 'FALCÓN', 106, GETDATE(), GETDATE());
INSERT INTO CITY (VNAME, VSTATE, ID_MUNICIPALITY, DCREATED, DUPDATED) VALUES ('YARACAL', 'FALCÓN', 107, GETDATE(), GETDATE());
INSERT INTO CITY (VNAME, VSTATE, ID_MUNICIPALITY, DCREATED, DUPDATED) VALUES ('LA VELA DE CORO', 'FALCÓN', 109, GETDATE(), GETDATE());
INSERT INTO CITY (VNAME, VSTATE, ID_MUNICIPALITY, DCREATED, DUPDATED) VALUES ('DABAJURO', 'FALCÓN', 110, GETDATE(), GETDATE());
INSERT INTO CITY (VNAME, VSTATE, ID_MUNICIPALITY, DCREATED, DUPDATED) VALUES ('PEDREGAL', 'FALCÓN', 111, GETDATE(), GETDATE());
INSERT INTO CITY (VNAME, VSTATE, ID_MUNICIPALITY, DCREATED, DUPDATED) VALUES ('PUEBLO NUEVO', 'FALCÓN', 112, GETDATE(), GETDATE());
INSERT INTO CITY (VNAME, VSTATE, ID_MUNICIPALITY, DCREATED, DUPDATED) VALUES ('CHURUGUARA', 'FALCÓN', 113, GETDATE(), GETDATE());
INSERT INTO CITY (VNAME, VSTATE, ID_MUNICIPALITY, DCREATED, DUPDATED) VALUES ('JACURA', 'FALCÓN', 114, GETDATE(), GETDATE());
INSERT INTO CITY (VNAME, VSTATE, ID_MUNICIPALITY, DCREATED, DUPDATED) VALUES ('TUCACAS', 'FALCÓN', 115, GETDATE(), GETDATE());
INSERT INTO CITY (VNAME, VSTATE, ID_MUNICIPALITY, DCREATED, DUPDATED) VALUES ('SANTA CRUZ DE LOS TAQUES', 'FALCÓN', 116, GETDATE(), GETDATE());
INSERT INTO CITY (VNAME, VSTATE, ID_MUNICIPALITY, DCREATED, DUPDATED) VALUES ('MENES DE MAUROA', 'FALCÓN', 117, GETDATE(), GETDATE());
INSERT INTO CITY (VNAME, VSTATE, ID_MUNICIPALITY, DCREATED, DUPDATED) VALUES ('CHICHIRIVICHE', 'FALCÓN', 119, GETDATE(), GETDATE());
INSERT INTO CITY (VNAME, VSTATE, ID_MUNICIPALITY, DCREATED, DUPDATED) VALUES ('PALMASOLA', 'FALCÓN', 120, GETDATE(), GETDATE());
INSERT INTO CITY (VNAME, VSTATE, ID_MUNICIPALITY, DCREATED, DUPDATED) VALUES ('CABURE', 'FALCÓN', 121, GETDATE(), GETDATE());
INSERT INTO CITY (VNAME, VSTATE, ID_MUNICIPALITY, DCREATED, DUPDATED) VALUES ('PIRITU', 'FALCÓN', 122, GETDATE(), GETDATE());
INSERT INTO CITY (VNAME, VSTATE, ID_MUNICIPALITY, DCREATED, DUPDATED) VALUES ('MIRIMIRE', 'FALCÓN', 123, GETDATE(), GETDATE());
INSERT INTO CITY (VNAME, VSTATE, ID_MUNICIPALITY, DCREATED, DUPDATED) VALUES ('LA CRUZ DE TARATARA', 'FALCÓN', 124, GETDATE(), GETDATE());
INSERT INTO CITY (VNAME, VSTATE, ID_MUNICIPALITY, DCREATED, DUPDATED) VALUES ('TOCOPERO', 'FALCÓN', 125, GETDATE(), GETDATE());
INSERT INTO CITY (VNAME, VSTATE, ID_MUNICIPALITY, DCREATED, DUPDATED) VALUES ('SANTA CRUZ DE BUCARAL', 'FALCÓN', 126, GETDATE(), GETDATE());
INSERT INTO CITY (VNAME, VSTATE, ID_MUNICIPALITY, DCREATED, DUPDATED) VALUES ('URUMACO', 'FALCÓN', 127, GETDATE(), GETDATE());
INSERT INTO CITY (VNAME, VSTATE, ID_MUNICIPALITY, DCREATED, DUPDATED) VALUES ('PUERTO CUMAREBO', 'FALCÓN', 128, GETDATE(), GETDATE());


--GUARICO
UPDATE CITY SET ID_MUNICIPALITY = 143 WHERE ID = 37;
UPDATE CITY SET ID_MUNICIPALITY = 137 WHERE ID = 38;
UPDATE CITY SET ID_MUNICIPALITY = 134 WHERE ID = 39;

INSERT INTO CITY (VNAME, VSTATE, ID_MUNICIPALITY, DCREATED, DUPDATED) VALUES ('CHAMAGUAN', 'GUÁRICO', 129, GETDATE(), GETDATE());
INSERT INTO CITY (VNAME, VSTATE, ID_MUNICIPALITY, DCREATED, DUPDATED) VALUES ('CHAGUARAMAS', 'GUÁRICO', 130, GETDATE(), GETDATE());
INSERT INTO CITY (VNAME, VSTATE, ID_MUNICIPALITY, DCREATED, DUPDATED) VALUES ('EL SOCORRO', 'GUÁRICO', 131, GETDATE(), GETDATE());
INSERT INTO CITY (VNAME, VSTATE, ID_MUNICIPALITY, DCREATED, DUPDATED) VALUES ('TUCUPIDO', 'GUÁRICO', 132, GETDATE(), GETDATE());
INSERT INTO CITY (VNAME, VSTATE, ID_MUNICIPALITY, DCREATED, DUPDATED) VALUES ('ALTAGRACIA DE ORITUCO', 'GUÁRICO', 133, GETDATE(), GETDATE());
INSERT INTO CITY (VNAME, VSTATE, ID_MUNICIPALITY, DCREATED, DUPDATED) VALUES ('EL SOMBRERO', 'GUÁRICO', 135, GETDATE(), GETDATE());
INSERT INTO CITY (VNAME, VSTATE, ID_MUNICIPALITY, DCREATED, DUPDATED) VALUES ('LAS MERCEDES', 'GUÁRICO', 136, GETDATE(), GETDATE());
INSERT INTO CITY (VNAME, VSTATE, ID_MUNICIPALITY, DCREATED, DUPDATED) VALUES ('ORTIZ', 'GUÁRICO', 138, GETDATE(), GETDATE());
INSERT INTO CITY (VNAME, VSTATE, ID_MUNICIPALITY, DCREATED, DUPDATED) VALUES ('ZARAZA', 'GUÁRICO', 139, GETDATE(), GETDATE());
INSERT INTO CITY (VNAME, VSTATE, ID_MUNICIPALITY, DCREATED, DUPDATED) VALUES ('GUAYABAL', 'GUÁRICO', 140, GETDATE(), GETDATE());
INSERT INTO CITY (VNAME, VSTATE, ID_MUNICIPALITY, DCREATED, DUPDATED) VALUES ('SAN JOSE DE GUARIBE', 'GUÁRICO', 141, GETDATE(), GETDATE());
INSERT INTO CITY (VNAME, VSTATE, ID_MUNICIPALITY, DCREATED, DUPDATED) VALUES ('SANTA MARIA DE IPIRE', 'GUÁRICO', 142, GETDATE(), GETDATE());	

--LARA
UPDATE CITY SET ID_MUNICIPALITY = 146 WHERE ID = 42;
UPDATE CITY SET ID_MUNICIPALITY = 151 WHERE ID = 43;
UPDATE CITY SET ID_MUNICIPALITY = 147 WHERE ID = 44;
UPDATE CITY SET ID_MUNICIPALITY = 149 WHERE ID = 45;

INSERT INTO CITY (VNAME, VSTATE, ID_MUNICIPALITY, DCREATED, DUPDATED) VALUES ('SANARE', 'LARA', 144, GETDATE(), GETDATE());
INSERT INTO CITY (VNAME, VSTATE, ID_MUNICIPALITY, DCREATED, DUPDATED) VALUES ('DUACA', 'LARA', 145, GETDATE(), GETDATE());
INSERT INTO CITY (VNAME, VSTATE, ID_MUNICIPALITY, DCREATED, DUPDATED) VALUES ('EL TOCUYO', 'LARA', 148, GETDATE(), GETDATE());
INSERT INTO CITY (VNAME, VSTATE, ID_MUNICIPALITY, DCREATED, DUPDATED) VALUES ('SARARE', 'LARA', 150, GETDATE(), GETDATE());
INSERT INTO CITY (VNAME, VSTATE, ID_MUNICIPALITY, DCREATED, DUPDATED) VALUES ('SIQUISIQUE', 'LARA', 152, GETDATE(), GETDATE());

--MÉRIDA
UPDATE CITY SET ID_MUNICIPALITY = 164 WHERE ID = 46;
UPDATE CITY SET ID_MUNICIPALITY = 153 WHERE ID = 47;

INSERT INTO CITY (VNAME, VSTATE, ID_MUNICIPALITY, DCREATED, DUPDATED) VALUES ('LA AZULITA', 'MÉRIDA', 154, GETDATE(), GETDATE());
INSERT INTO CITY (VNAME, VSTATE, ID_MUNICIPALITY, DCREATED, DUPDATED) VALUES ('SANTA CRUZ DE MORA', 'MÉRIDA', 155, GETDATE(), GETDATE());
INSERT INTO CITY (VNAME, VSTATE, ID_MUNICIPALITY, DCREATED, DUPDATED) VALUES ('ARICAGUAS', 'MÉRIDA', 156, GETDATE(), GETDATE());
INSERT INTO CITY (VNAME, VSTATE, ID_MUNICIPALITY, DCREATED, DUPDATED) VALUES ('CANAGUA', 'MÉRIDA', 157, GETDATE(), GETDATE());
INSERT INTO CITY (VNAME, VSTATE, ID_MUNICIPALITY, DCREATED, DUPDATED) VALUES ('EJIDO', 'MÉRIDA', 158, GETDATE(), GETDATE());
INSERT INTO CITY (VNAME, VSTATE, ID_MUNICIPALITY, DCREATED, DUPDATED) VALUES ('TUCANI', 'MÉRIDA', 159, GETDATE(), GETDATE());
INSERT INTO CITY (VNAME, VSTATE, ID_MUNICIPALITY, DCREATED, DUPDATED) VALUES ('SANTO DOMINGO', 'MÉRIDA', 160, GETDATE(), GETDATE());
INSERT INTO CITY (VNAME, VSTATE, ID_MUNICIPALITY, DCREATED, DUPDATED) VALUES ('GUARAQUE', 'MÉRIDA', 161, GETDATE(), GETDATE());
INSERT INTO CITY (VNAME, VSTATE, ID_MUNICIPALITY, DCREATED, DUPDATED) VALUES ('ARAPUEY', 'MÉRIDA', 162, GETDATE(), GETDATE());
INSERT INTO CITY (VNAME, VSTATE, ID_MUNICIPALITY, DCREATED, DUPDATED) VALUES ('TORONDOY', 'MÉRIDA', 163, GETDATE(), GETDATE());
INSERT INTO CITY (VNAME, VSTATE, ID_MUNICIPALITY, DCREATED, DUPDATED) VALUES ('TIMOTES', 'MÉRIDA', 165, GETDATE(), GETDATE());
INSERT INTO CITY (VNAME, VSTATE, ID_MUNICIPALITY, DCREATED, DUPDATED) VALUES ('SANTA ELENA DE ARENALES', 'MÉRIDA', 166, GETDATE(), GETDATE());
INSERT INTO CITY (VNAME, VSTATE, ID_MUNICIPALITY, DCREATED, DUPDATED) VALUES ('SANTA MARIA DE CAPARO', 'MÉRIDA', 167, GETDATE(), GETDATE());
INSERT INTO CITY (VNAME, VSTATE, ID_MUNICIPALITY, DCREATED, DUPDATED) VALUES ('PUEBLO LLANO', 'MÉRIDA', 168, GETDATE(), GETDATE());
INSERT INTO CITY (VNAME, VSTATE, ID_MUNICIPALITY, DCREATED, DUPDATED) VALUES ('MUCUCHIES', 'MÉRIDA', 169, GETDATE(), GETDATE());
INSERT INTO CITY (VNAME, VSTATE, ID_MUNICIPALITY, DCREATED, DUPDATED) VALUES ('BAILADORES', 'MÉRIDA', 170, GETDATE(), GETDATE());
INSERT INTO CITY (VNAME, VSTATE, ID_MUNICIPALITY, DCREATED, DUPDATED) VALUES ('TABAY', 'MÉRIDA', 171, GETDATE(), GETDATE());
INSERT INTO CITY (VNAME, VSTATE, ID_MUNICIPALITY, DCREATED, DUPDATED) VALUES ('LAGUNILLAS', 'MÉRIDA', 172, GETDATE(), GETDATE());
INSERT INTO CITY (VNAME, VSTATE, ID_MUNICIPALITY, DCREATED, DUPDATED) VALUES ('TOVAR', 'MÉRIDA', 173, GETDATE(), GETDATE());
INSERT INTO CITY (VNAME, VSTATE, ID_MUNICIPALITY, DCREATED, DUPDATED) VALUES ('NUEVA BOLIVIA', 'MÉRIDA', 174, GETDATE(), GETDATE());
INSERT INTO CITY (VNAME, VSTATE, ID_MUNICIPALITY, DCREATED, DUPDATED) VALUES ('ZEA', 'MÉRIDA', 175, GETDATE(), GETDATE());

--MIRANDA
UPDATE CITY SET ID_MUNICIPALITY = 186 WHERE ID = 48;
UPDATE CITY SET ID_MUNICIPALITY = 194 WHERE ID = 49;
UPDATE CITY SET ID_MUNICIPALITY = 185 WHERE ID = 50;
UPDATE CITY SET ID_MUNICIPALITY = 178 WHERE ID = 51;
UPDATE CITY SET ID_MUNICIPALITY = 195 WHERE ID = 52;
UPDATE CITY SET ID_MUNICIPALITY = 192 WHERE ID = 53;
UPDATE CITY SET ID_MUNICIPALITY = 196 WHERE ID = 54;
UPDATE CITY SET ID_MUNICIPALITY = 187 WHERE ID = 55;
UPDATE CITY SET ID_MUNICIPALITY = 183 WHERE ID = 56;
UPDATE CITY SET ID_MUNICIPALITY = 190 WHERE ID = 57;
UPDATE CITY SET ID_MUNICIPALITY = 188 WHERE ID = 58;
UPDATE CITY SET ID_MUNICIPALITY = 182 WHERE ID = 59;
UPDATE CITY SET ID_MUNICIPALITY = 184 WHERE ID = 60;

INSERT INTO CITY (VNAME, VSTATE, ID_MUNICIPALITY, DCREATED, DUPDATED) VALUES ('CAUCAGUA', 'MIRANDA', 176, GETDATE(), GETDATE());
INSERT INTO CITY (VNAME, VSTATE, ID_MUNICIPALITY, DCREATED, DUPDATED) VALUES ('SAN JOSE DE BARLOVENTO', 'MIRANDA', 177, GETDATE(), GETDATE());
INSERT INTO CITY (VNAME, VSTATE, ID_MUNICIPALITY, DCREATED, DUPDATED) VALUES ('HIGUEROTE', 'MIRANDA', 179, GETDATE(), GETDATE());
INSERT INTO CITY (VNAME, VSTATE, ID_MUNICIPALITY, DCREATED, DUPDATED) VALUES ('MAMPORAL', 'MIRANDA', 180, GETDATE(), GETDATE());
INSERT INTO CITY (VNAME, VSTATE, ID_MUNICIPALITY, DCREATED, DUPDATED) VALUES ('CARRIZAL', 'MIRANDA', 181, GETDATE(), GETDATE());
INSERT INTO CITY (VNAME, VSTATE, ID_MUNICIPALITY, DCREATED, DUPDATED) VALUES ('RIO CHICO', 'MIRANDA', 189, GETDATE(), GETDATE());
INSERT INTO CITY (VNAME, VSTATE, ID_MUNICIPALITY, DCREATED, DUPDATED) VALUES ('CUPIRA', 'MIRANDA', 191, GETDATE(), GETDATE());
INSERT INTO CITY (VNAME, VSTATE, ID_MUNICIPALITY, DCREATED, DUPDATED) VALUES ('SAN FRANCISCO DE YARE', 'MIRANDA', 193, GETDATE(), GETDATE());

--MONAGAS

UPDATE CITY SET ID_MUNICIPALITY = 204 WHERE ID = 61;
UPDATE CITY SET ID_MUNICIPALITY = 202 WHERE ID = 62;

INSERT INTO CITY (VNAME, VSTATE, ID_MUNICIPALITY, DCREATED, DUPDATED) VALUES ('SAN ANTONIO DE MATURIN', 'MONAGAS', 197, GETDATE(), GETDATE());
INSERT INTO CITY (VNAME, VSTATE, ID_MUNICIPALITY, DCREATED, DUPDATED) VALUES ('AGUASAY', 'MONAGAS', 198, GETDATE(), GETDATE());
INSERT INTO CITY (VNAME, VSTATE, ID_MUNICIPALITY, DCREATED, DUPDATED) VALUES ('CARIPITO', 'MONAGAS', 199, GETDATE(), GETDATE());
INSERT INTO CITY (VNAME, VSTATE, ID_MUNICIPALITY, DCREATED, DUPDATED) VALUES ('CARIPE', 'MONAGAS', 200, GETDATE(), GETDATE());
INSERT INTO CITY (VNAME, VSTATE, ID_MUNICIPALITY, DCREATED, DUPDATED) VALUES ('CAICARA DE MATURIN', 'MONAGAS', 201, GETDATE(), GETDATE());
INSERT INTO CITY (VNAME, VSTATE, ID_MUNICIPALITY, DCREATED, DUPDATED) VALUES ('TEMBLADOR', 'MONAGAS', 203, GETDATE(), GETDATE());
INSERT INTO CITY (VNAME, VSTATE, ID_MUNICIPALITY, DCREATED, DUPDATED) VALUES ('ARAGUA DE MATURIN', 'MONAGAS', 205, GETDATE(), GETDATE());
INSERT INTO CITY (VNAME, VSTATE, ID_MUNICIPALITY, DCREATED, DUPDATED) VALUES ('QUIRIQUIRE', 'MONAGAS', 206, GETDATE(), GETDATE());
INSERT INTO CITY (VNAME, VSTATE, ID_MUNICIPALITY, DCREATED, DUPDATED) VALUES ('SANTA BARBARA', 'MONAGAS', 207, GETDATE(), GETDATE());
INSERT INTO CITY (VNAME, VSTATE, ID_MUNICIPALITY, DCREATED, DUPDATED) VALUES ('BARRANCAS DEL ORINOCO', 'MONAGAS', 208, GETDATE(), GETDATE());
INSERT INTO CITY (VNAME, VSTATE, ID_MUNICIPALITY, DCREATED, DUPDATED) VALUES ('URACOA', 'MONAGAS', 209, GETDATE(), GETDATE());	

--NUEVA ESPARTA
UPDATE CITY SET ID_MUNICIPALITY = 217 WHERE ID = 63;
UPDATE CITY SET ID_MUNICIPALITY = 211 WHERE ID = 64;
UPDATE CITY SET ID_MUNICIPALITY = 215 WHERE ID = 65;
UPDATE CITY SET ID_MUNICIPALITY = 214 WHERE ID = 66;
UPDATE CITY SET ID_MUNICIPALITY = 216 WHERE ID = 67;
UPDATE CITY SET ID_MUNICIPALITY = 210 WHERE ID = 68;
UPDATE CITY SET ID_MUNICIPALITY =212  WHERE ID = 69;

INSERT INTO CITY (VNAME, VSTATE, ID_MUNICIPALITY, DCREATED, DUPDATED) VALUES ('EL VALLE DEL ESPIRUTU SANTO', 'NUEVA ESPARTA', 213, GETDATE(), GETDATE());
INSERT INTO CITY (VNAME, VSTATE, ID_MUNICIPALITY, DCREATED, DUPDATED) VALUES ('BOCA DE RIO', 'NUEVA ESPARTA', 218, GETDATE(), GETDATE());
INSERT INTO CITY (VNAME, VSTATE, ID_MUNICIPALITY, DCREATED, DUPDATED) VALUES ('PUNTA DE PIEDRAS', 'NUEVA ESPARTA', 219, GETDATE(), GETDATE());
INSERT INTO CITY (VNAME, VSTATE, ID_MUNICIPALITY, DCREATED, DUPDATED) VALUES ('SAN PEDRO DE COCHE', 'NUEVA ESPARTA', 220, GETDATE(), GETDATE());

--PORTUGUESA
UPDATE CITY SET ID_MUNICIPALITY = 228 WHERE ID = 70;
UPDATE CITY SET ID_MUNICIPALITY = 224 WHERE ID = 71;
UPDATE CITY SET ID_MUNICIPALITY = 222 WHERE ID = 72;

INSERT INTO CITY (VNAME, VSTATE, ID_MUNICIPALITY, DCREATED, DUPDATED) VALUES ('AGUA BLANCA', 'PORTUGUESA', 221, GETDATE(), GETDATE());
INSERT INTO CITY (VNAME, VSTATE, ID_MUNICIPALITY, DCREATED, DUPDATED) VALUES ('PIRITU', 'PORTUGUESA', 223, GETDATE(), GETDATE());
INSERT INTO CITY (VNAME, VSTATE, ID_MUNICIPALITY, DCREATED, DUPDATED) VALUES ('GUANARITO', 'PORTUGUESA', 225, GETDATE(), GETDATE());
INSERT INTO CITY (VNAME, VSTATE, ID_MUNICIPALITY, DCREATED, DUPDATED) VALUES ('PARAISO DE CHABASQUEN', 'PORTUGUESA', 226, GETDATE(), GETDATE());
INSERT INTO CITY (VNAME, VSTATE, ID_MUNICIPALITY, DCREATED, DUPDATED) VALUES ('OSPINO', 'PORTUGUESA', 227, GETDATE(), GETDATE());
INSERT INTO CITY (VNAME, VSTATE, ID_MUNICIPALITY, DCREATED, DUPDATED) VALUES ('PAPELON', 'PORTUGUESA', 229, GETDATE(), GETDATE());
INSERT INTO CITY (VNAME, VSTATE, ID_MUNICIPALITY, DCREATED, DUPDATED) VALUES ('BOCONOITO', 'PORTUGUESA', 230, GETDATE(), GETDATE());
INSERT INTO CITY (VNAME, VSTATE, ID_MUNICIPALITY, DCREATED, DUPDATED) VALUES ('SAN RAFAEL DE ONOTO', 'PORTUGUESA', 231, GETDATE(), GETDATE());
INSERT INTO CITY (VNAME, VSTATE, ID_MUNICIPALITY, DCREATED, DUPDATED) VALUES ('EL PLAYON', 'PORTUGUESA', 232, GETDATE(), GETDATE());
INSERT INTO CITY (VNAME, VSTATE, ID_MUNICIPALITY, DCREATED, DUPDATED) VALUES ('BISCUCUY', 'PORTUGUESA', 233, GETDATE(), GETDATE());
INSERT INTO CITY (VNAME, VSTATE, ID_MUNICIPALITY, DCREATED, DUPDATED) VALUES ('VILLA BRUZUAL', 'PORTUGUESA', 234, GETDATE(), GETDATE());

--SUCRE
UPDATE CITY SET ID_MUNICIPALITY = 248 WHERE ID = 73;
UPDATE CITY SET ID_MUNICIPALITY = 239 WHERE ID = 74;

INSERT INTO CITY (VNAME, VSTATE, ID_MUNICIPALITY, DCREATED, DUPDATED) VALUES ('CASANAY', 'SUCRE', 235, GETDATE(), GETDATE());
INSERT INTO CITY (VNAME, VSTATE, ID_MUNICIPALITY, DCREATED, DUPDATED) VALUES ('SAN JOSE DE AEROCUAR', 'SUCRE', 236, GETDATE(), GETDATE());
INSERT INTO CITY (VNAME, VSTATE, ID_MUNICIPALITY, DCREATED, DUPDATED) VALUES ('RIO CARIBE', 'SUCRE', 237, GETDATE(), GETDATE());
INSERT INTO CITY (VNAME, VSTATE, ID_MUNICIPALITY, DCREATED, DUPDATED) VALUES ('EL PILAR', 'SUCRE', 238, GETDATE(), GETDATE());
INSERT INTO CITY (VNAME, VSTATE, ID_MUNICIPALITY, DCREATED, DUPDATED) VALUES ('MARIGUITAR', 'SUCRE', 240, GETDATE(), GETDATE());
INSERT INTO CITY (VNAME, VSTATE, ID_MUNICIPALITY, DCREATED, DUPDATED) VALUES ('YAGUARAPARO', 'SUCRE', 241, GETDATE(), GETDATE());
INSERT INTO CITY (VNAME, VSTATE, ID_MUNICIPALITY, DCREATED, DUPDATED) VALUES ('ARAYA', 'SUCRE', 242, GETDATE(), GETDATE());
INSERT INTO CITY (VNAME, VSTATE, ID_MUNICIPALITY, DCREATED, DUPDATED) VALUES ('TUNAPUY', 'SUCRE', 243, GETDATE(), GETDATE());
INSERT INTO CITY (VNAME, VSTATE, ID_MUNICIPALITY, DCREATED, DUPDATED) VALUES ('IRAPA', 'SUCRE', 244, GETDATE(), GETDATE());
INSERT INTO CITY (VNAME, VSTATE, ID_MUNICIPALITY, DCREATED, DUPDATED) VALUES ('SAN ANTONIO DEL GOLFO', 'SUCRE', 245, GETDATE(), GETDATE());
INSERT INTO CITY (VNAME, VSTATE, ID_MUNICIPALITY, DCREATED, DUPDATED) VALUES ('CUMANACOA', 'SUCRE', 246, GETDATE(), GETDATE());
INSERT INTO CITY (VNAME, VSTATE, ID_MUNICIPALITY, DCREATED, DUPDATED) VALUES ('CARIACO', 'SUCRE', 247, GETDATE(), GETDATE());
INSERT INTO CITY (VNAME, VSTATE, ID_MUNICIPALITY, DCREATED, DUPDATED) VALUES ('GUIRIA', 'SUCRE', 249, GETDATE(), GETDATE());

--TÁCHIRA
UPDATE CITY SET ID_MUNICIPALITY = 272 WHERE ID = 75;
UPDATE CITY SET ID_MUNICIPALITY = 254 WHERE ID = 76;
UPDATE CITY SET ID_MUNICIPALITY = 259 WHERE ID = 77;
UPDATE CITY SET ID_MUNICIPALITY = 260 WHERE ID = 78;
UPDATE CITY SET ID_MUNICIPALITY = 264 WHERE ID = 79;
UPDATE CITY SET ID_MUNICIPALITY = 253 WHERE ID = 92;

INSERT INTO CITY (VNAME, VSTATE, ID_MUNICIPALITY, DCREATED, DUPDATED) VALUES ('CORDERO', 'TÁCHIRA', 250, GETDATE(), GETDATE());
INSERT INTO CITY (VNAME, VSTATE, ID_MUNICIPALITY, DCREATED, DUPDATED) VALUES ('LAS MESAS', 'TÁCHIRA', 251, GETDATE(), GETDATE());
INSERT INTO CITY (VNAME, VSTATE, ID_MUNICIPALITY, DCREATED, DUPDATED) VALUES ('COLON', 'TÁCHIRA', 252, GETDATE(), GETDATE());
INSERT INTO CITY (VNAME, VSTATE, ID_MUNICIPALITY, DCREATED, DUPDATED) VALUES ('SANTA ANA', 'TÁCHIRA', 255, GETDATE(), GETDATE());
INSERT INTO CITY (VNAME, VSTATE, ID_MUNICIPALITY, DCREATED, DUPDATED) VALUES ('SAN RAFAEL DEL PIÑAL', 'TÁCHIRA', 256, GETDATE(), GETDATE());
INSERT INTO CITY (VNAME, VSTATE, ID_MUNICIPALITY, DCREATED, DUPDATED) VALUES ('SAN JOSE DE BOLIVAR', 'TÁCHIRA', 257, GETDATE(), GETDATE());
INSERT INTO CITY (VNAME, VSTATE, ID_MUNICIPALITY, DCREATED, DUPDATED) VALUES ('LA FRIA', 'TÁCHIRA', 258, GETDATE(), GETDATE());
INSERT INTO CITY (VNAME, VSTATE, ID_MUNICIPALITY, DCREATED, DUPDATED) VALUES ('LA GRITA', 'TÁCHIRA', 261, GETDATE(), GETDATE());
INSERT INTO CITY (VNAME, VSTATE, ID_MUNICIPALITY, DCREATED, DUPDATED) VALUES ('EL COBRE', 'TÁCHIRA', 262, GETDATE(), GETDATE());
INSERT INTO CITY (VNAME, VSTATE, ID_MUNICIPALITY, DCREATED, DUPDATED) VALUES ('RUBIO', 'TÁCHIRA', 263, GETDATE(), GETDATE());
INSERT INTO CITY (VNAME, VSTATE, ID_MUNICIPALITY, DCREATED, DUPDATED) VALUES ('ABEJALES', 'TÁCHIRA', 265, GETDATE(), GETDATE());
INSERT INTO CITY (VNAME, VSTATE, ID_MUNICIPALITY, DCREATED, DUPDATED) VALUES ('LOBATERA', 'TÁCHIRA', 266, GETDATE(), GETDATE());
INSERT INTO CITY (VNAME, VSTATE, ID_MUNICIPALITY, DCREATED, DUPDATED) VALUES ('MICHELENA', 'TÁCHIRA', 267, GETDATE(), GETDATE());
INSERT INTO CITY (VNAME, VSTATE, ID_MUNICIPALITY, DCREATED, DUPDATED) VALUES ('COLONCITO', 'TÁCHIRA', 268, GETDATE(), GETDATE());
INSERT INTO CITY (VNAME, VSTATE, ID_MUNICIPALITY, DCREATED, DUPDATED) VALUES ('UREÑA', 'TÁCHIRA', 269, GETDATE(), GETDATE());
INSERT INTO CITY (VNAME, VSTATE, ID_MUNICIPALITY, DCREATED, DUPDATED) VALUES ('DELICIAS', 'TÁCHIRA', 270, GETDATE(), GETDATE());
INSERT INTO CITY (VNAME, VSTATE, ID_MUNICIPALITY, DCREATED, DUPDATED) VALUES ('LA TENDIDA', 'TÁCHIRA', 271, GETDATE(), GETDATE());
INSERT INTO CITY (VNAME, VSTATE, ID_MUNICIPALITY, DCREATED, DUPDATED) VALUES ('UMUQUENA', 'TÁCHIRA', 273, GETDATE(), GETDATE());
INSERT INTO CITY (VNAME, VSTATE, ID_MUNICIPALITY, DCREATED, DUPDATED) VALUES ('SEBORUCO', 'TÁCHIRA', 274, GETDATE(), GETDATE());
INSERT INTO CITY (VNAME, VSTATE, ID_MUNICIPALITY, DCREATED, DUPDATED) VALUES ('SAN SIMON', 'TÁCHIRA',275 , GETDATE(), GETDATE());
INSERT INTO CITY (VNAME, VSTATE, ID_MUNICIPALITY, DCREATED, DUPDATED) VALUES ('QUENIQUEA', 'TÁCHIRA', 276, GETDATE(), GETDATE());
INSERT INTO CITY (VNAME, VSTATE, ID_MUNICIPALITY, DCREATED, DUPDATED) VALUES ('SAN JOSEITO', 'TÁCHIRA', 277, GETDATE(), GETDATE());
INSERT INTO CITY (VNAME, VSTATE, ID_MUNICIPALITY, DCREATED, DUPDATED) VALUES ('PREGONERO', 'TÁCHIRA', 278, GETDATE(), GETDATE());

--TRUJILLO
UPDATE CITY SET ID_MUNICIPALITY = 298 WHERE ID = 80;
UPDATE CITY SET ID_MUNICIPALITY = 280 WHERE ID = 81;
UPDATE CITY SET ID_MUNICIPALITY = 294 WHERE ID = 82;
UPDATE CITY SET ID_MUNICIPALITY = 296 WHERE ID = 83;

INSERT INTO CITY (VNAME, VSTATE, ID_MUNICIPALITY, DCREATED, DUPDATED) VALUES ('SANTA ISABEL', 'TRUJILLO', 279, GETDATE(), GETDATE());
INSERT INTO CITY (VNAME, VSTATE, ID_MUNICIPALITY, DCREATED, DUPDATED) VALUES ('SABANA GRANDE', 'TRUJILLO', 281, GETDATE(), GETDATE());
INSERT INTO CITY (VNAME, VSTATE, ID_MUNICIPALITY, DCREATED, DUPDATED) VALUES ('CHEJENDE', 'TRUJILLO', 282, GETDATE(), GETDATE());
INSERT INTO CITY (VNAME, VSTATE, ID_MUNICIPALITY, DCREATED, DUPDATED) VALUES ('CARACHE', 'TRUJILLO', 283, GETDATE(), GETDATE());
INSERT INTO CITY (VNAME, VSTATE, ID_MUNICIPALITY, DCREATED, DUPDATED) VALUES ('ESCUCHE', 'TRUJILLO', 284, GETDATE(), GETDATE());
INSERT INTO CITY (VNAME, VSTATE, ID_MUNICIPALITY, DCREATED, DUPDATED) VALUES ('EL PARADERO', 'TRUJILLO', 285, GETDATE(), GETDATE());
INSERT INTO CITY (VNAME, VSTATE, ID_MUNICIPALITY, DCREATED, DUPDATED) VALUES ('CAMPO ELIAS', 'TRUJILLO', 286, GETDATE(), GETDATE());
INSERT INTO CITY (VNAME, VSTATE, ID_MUNICIPALITY, DCREATED, DUPDATED) VALUES ('SANTA APOLONIA', 'TRUJILLO', 287, GETDATE(), GETDATE());
INSERT INTO CITY (VNAME, VSTATE, ID_MUNICIPALITY, DCREATED, DUPDATED) VALUES ('EL DIVIDIVE', 'TRUJILLO', 288, GETDATE(), GETDATE());
INSERT INTO CITY (VNAME, VSTATE, ID_MUNICIPALITY, DCREATED, DUPDATED) VALUES ('MONTE CARMELO', 'TRUJILLO', 289, GETDATE(), GETDATE());
INSERT INTO CITY (VNAME, VSTATE, ID_MUNICIPALITY, DCREATED, DUPDATED) VALUES ('MOTATAN', 'TRUJILLO', 290, GETDATE(), GETDATE());
INSERT INTO CITY (VNAME, VSTATE, ID_MUNICIPALITY, DCREATED, DUPDATED) VALUES ('PAMPAN', 'TRUJILLO', 291, GETDATE(), GETDATE());
INSERT INTO CITY (VNAME, VSTATE, ID_MUNICIPALITY, DCREATED, DUPDATED) VALUES ('PAMPANITO', 'TRUJILLO', 292, GETDATE(), GETDATE());
INSERT INTO CITY (VNAME, VSTATE, ID_MUNICIPALITY, DCREATED, DUPDATED) VALUES ('BETIJOQUE', 'TRUJILLO', 293, GETDATE(), GETDATE());
INSERT INTO CITY (VNAME, VSTATE, ID_MUNICIPALITY, DCREATED, DUPDATED) VALUES ('SABANA DE MENDOZA', 'TRUJILLO', 295, GETDATE(), GETDATE());
INSERT INTO CITY (VNAME, VSTATE, ID_MUNICIPALITY, DCREATED, DUPDATED) VALUES ('LA QUEBRADA', 'TRUJILLO', 297, GETDATE(), GETDATE());

--YARACUY
UPDATE CITY SET ID_MUNICIPALITY = 309 WHERE ID = 84;
UPDATE CITY SET ID_MUNICIPALITY = 308 WHERE ID = 85;
UPDATE CITY SET ID_MUNICIPALITY = 306 WHERE ID = 94;

INSERT INTO CITY (VNAME, VSTATE, ID_MUNICIPALITY, DCREATED, DUPDATED) VALUES ('SAN PABLO', 'YARACUY', 299, GETDATE(), GETDATE());
INSERT INTO CITY (VNAME, VSTATE, ID_MUNICIPALITY, DCREATED, DUPDATED) VALUES ('AROA', 'YARACUY', 300, GETDATE(), GETDATE());
INSERT INTO CITY (VNAME, VSTATE, ID_MUNICIPALITY, DCREATED, DUPDATED) VALUES ('CHIVACOA', 'YARACUY', 301, GETDATE(), GETDATE());
INSERT INTO CITY (VNAME, VSTATE, ID_MUNICIPALITY, DCREATED, DUPDATED) VALUES ('COCOROTE', 'YARACUY', 302, GETDATE(), GETDATE());
INSERT INTO CITY (VNAME, VSTATE, ID_MUNICIPALITY, DCREATED, DUPDATED) VALUES ('INDEPENDENCIA', 'YARACUY', 303, GETDATE(), GETDATE());
INSERT INTO CITY (VNAME, VSTATE, ID_MUNICIPALITY, DCREATED, DUPDATED) VALUES ('SABABA DE PARRA', 'YARACUY', 304, GETDATE(), GETDATE());
INSERT INTO CITY (VNAME, VSTATE, ID_MUNICIPALITY, DCREATED, DUPDATED) VALUES ('BARAURE', 'YARACUY', 305, GETDATE(), GETDATE());
INSERT INTO CITY (VNAME, VSTATE, ID_MUNICIPALITY, DCREATED, DUPDATED) VALUES ('NIRGUA', 'YARACUY', 307, GETDATE(), GETDATE());
INSERT INTO CITY (VNAME, VSTATE, ID_MUNICIPALITY, DCREATED, DUPDATED) VALUES ('GUAMA', 'YARACUY', 310, GETDATE(), GETDATE());
INSERT INTO CITY (VNAME, VSTATE, ID_MUNICIPALITY, DCREATED, DUPDATED) VALUES ('URACHICHE', 'YARACUY', 311, GETDATE(), GETDATE());
INSERT INTO CITY (VNAME, VSTATE, ID_MUNICIPALITY, DCREATED, DUPDATED) VALUES ('FARRIAR', 'YARACUY', 312, GETDATE(), GETDATE());

--ZULIA

UPDATE CITY SET ID_MUNICIPALITY = 326 WHERE ID = 86;
UPDATE CITY SET ID_MUNICIPALITY = 315 WHERE ID = 87;
UPDATE CITY SET ID_MUNICIPALITY = 324 WHERE ID = 88;
UPDATE CITY SET ID_MUNICIPALITY = 323 WHERE ID = 89;

INSERT INTO CITY (VNAME, VSTATE, ID_MUNICIPALITY, DCREATED, DUPDATED) VALUES ('EL TORO', 'ZULIA', 313, GETDATE(), GETDATE());
INSERT INTO CITY (VNAME, VSTATE, ID_MUNICIPALITY, DCREATED, DUPDATED) VALUES ('SAN TIMOTEO', 'ZULIA', 314, GETDATE(), GETDATE());
INSERT INTO CITY (VNAME, VSTATE, ID_MUNICIPALITY, DCREATED, DUPDATED) VALUES ('ENCONTRADOS', 'ZULIA', 316, GETDATE(), GETDATE());
INSERT INTO CITY (VNAME, VSTATE, ID_MUNICIPALITY, DCREATED, DUPDATED) VALUES ('SAN CARLOS DEL ZULIA', 'ZULIA', 317, GETDATE(), GETDATE());
INSERT INTO CITY (VNAME, VSTATE, ID_MUNICIPALITY, DCREATED, DUPDATED) VALUES ('PUEBLO NUEVO', 'ZULIA', 318, GETDATE(), GETDATE());
INSERT INTO CITY (VNAME, VSTATE, ID_MUNICIPALITY, DCREATED, DUPDATED) VALUES ('SINAMAICA', 'ZULIA', 319, GETDATE(), GETDATE());
INSERT INTO CITY (VNAME, VSTATE, ID_MUNICIPALITY, DCREATED, DUPDATED) VALUES ('LA CONCEPCION', 'ZULIA', 320, GETDATE(), GETDATE());
INSERT INTO CITY (VNAME, VSTATE, ID_MUNICIPALITY, DCREATED, DUPDATED) VALUES ('CASIGUA EL CUBO', 'ZULIA', 321, GETDATE(), GETDATE());
INSERT INTO CITY (VNAME, VSTATE, ID_MUNICIPALITY, DCREATED, DUPDATED) VALUES ('CONCEPCION', 'ZULIA', 322, GETDATE(), GETDATE());
INSERT INTO CITY (VNAME, VSTATE, ID_MUNICIPALITY, DCREATED, DUPDATED) VALUES ('SAN RAFAEL DEL MOJAN', 'ZULIA', 325, GETDATE(), GETDATE());
INSERT INTO CITY (VNAME, VSTATE, ID_MUNICIPALITY, DCREATED, DUPDATED) VALUES ('ALTAGRACIA', 'ZULIA', 327, GETDATE(), GETDATE());
INSERT INTO CITY (VNAME, VSTATE, ID_MUNICIPALITY, DCREATED, DUPDATED) VALUES ('LA VILLA DEL ROSARIO', 'ZULIA', 328, GETDATE(), GETDATE());
INSERT INTO CITY (VNAME, VSTATE, ID_MUNICIPALITY, DCREATED, DUPDATED) VALUES ('SAN FRANCISCO', 'ZULIA', 329, GETDATE(), GETDATE());
INSERT INTO CITY (VNAME, VSTATE, ID_MUNICIPALITY, DCREATED, DUPDATED) VALUES ('SANTA RITA', 'ZULIA', 330, GETDATE(), GETDATE());
INSERT INTO CITY (VNAME, VSTATE, ID_MUNICIPALITY, DCREATED, DUPDATED) VALUES ('TIA JUANA', 'ZULIA', 331, GETDATE(), GETDATE());
INSERT INTO CITY (VNAME, VSTATE, ID_MUNICIPALITY, DCREATED, DUPDATED) VALUES ('BOBURES', 'ZULIA', 332, GETDATE(), GETDATE());
INSERT INTO CITY (VNAME, VSTATE, ID_MUNICIPALITY, DCREATED, DUPDATED) VALUES ('BACHAQUERO', 'ZULIA', 333, GETDATE(), GETDATE());

--VARGAS
UPDATE CITY SET ID_MUNICIPALITY = 334 WHERE ID = 40;
UPDATE CITY SET ID_MUNICIPALITY = 334 WHERE ID = 41;

INSERT INTO CITY (VNAME, VSTATE, ID_MUNICIPALITY, DCREATED, DUPDATED) VALUES ('MAIQUETIA', 'VARGAS', 334, GETDATE(), GETDATE());

--DISTRITO CAPITAL 
UPDATE CITY SET ID_MUNICIPALITY = 335 WHERE ID = 34;














