ALTER TABLE SALEORDER ADD BPARALYZED BIT DEFAULT(0);
ALTER TABLE SALEORDER ADD IDVEHICLE INT;
ALTER TABLE SALEORDER 
ADD CONSTRAINT FK_SALEORDER_VEHICLE 
FOREIGN KEY (IDVEHICLE) REFERENCES VEHICLE(ID);