CREATE NONCLUSTERED INDEX [IX_CONTACT_BSUPPLIER_BUSER] 
ON [dbo].[CONTACT] ([BSUPPLIER], [BUSER])

CREATE NONCLUSTERED INDEX [IX_POLICYDETAILS_IDMAINTENANCE]
ON [dbo].[POLICYDETAILS] ([IDMAINTENANCE]);

CREATE NONCLUSTERED INDEX [IX_POLICY_IDVEHICLE_INCL]
ON [dbo].[POLICY] ([IDVEHICLE])
INCLUDE ([DINVOICEDATE], [VNUMBER]);


CREATE NONCLUSTERED INDEX [IX_MAINTENANCE_IDSERVICETYPE_INCL]
ON [dbo].[MAINTENANCE] ([IDSERVICETYPE])
INCLUDE (
    [IDREPORTTYPE],
    [IESTATUS],
    [IDDEALER],
    [IDVEHICLE],
    [IDCUSTOMER],
    [VSRGNUMBER],
    [DCREATED],
    [VSERVICENUMBER]
);


