USE [SODA]
GO

/****** Object:  Table [dbo].[ACCOUNTRECEIVABLE]    Script Date: 14/05/2026 8:45:10 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[ACCOUNTRECEIVABLE](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[IDSUPPLIER] [int] NULL,
	[IDDEALER] [int] NULL,
	[VTYPE] [varchar](1) NULL,
	[VCONCEPT] [varchar](1) NULL,
	[VNUMBER] [varchar](15) NULL,
	[VREFERENCE] [varchar](15) NULL,
	[DDATE] [datetime] NULL,
	[DDUEDATE] [datetime] NULL,
	[NAMOUNT] [numeric](18, 2) NULL,
	[NAMOUNTFULL] [numeric](18, 2) NULL,
	[NBALANCE] [numeric](18, 2) NULL,
	[NRATE] [numeric](18, 2) NULL,
	[DCREATED] [datetime] NULL,
	[IDSTATUS] [int] NULL,
	[IDTRANSACTIONSTATUS] [int] NULL,
 CONSTRAINT [PK_ACCOUNTRECEIVABLE] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[ACCOUNTRECEIVABLE] ADD  CONSTRAINT [DF__ACCOUNTRE__DCREA__2C7E77EA]  DEFAULT (getdate()) FOR [DCREATED]
GO


