CREATE TABLE PAYMENT
(
	ID INT PRIMARY KEY IDENTITY,
	NAMOUNT NUMERIC (18,2),
	DCREATED DATETIME,
	VUPDATEDBY VARCHAR (12),
	IDSUPPLIER INT,
	IDDEALER INT,
	NRATE INT,
	DDATERATE DATETIME,
	BASINC BIT
);

CREATE TABLE PAYMENTDETAILS
(
	ID INT PRIMARY KEY IDENTITY,
	DDATE DATETIME,
	IDCURRENCY INT,
	IDTYPE INT,
	VREFERENCE VARCHAR (15),
	NAMOUNT NUMERIC (18,2),
	IDSTATUS INT,
	IDBANKACOUNT INT,
	IDPAYMENT INT,
	VUPDATEDBY VARCHAR (12),
	DCREATED DATETIME,
	DUPDATED DATETIME
	FOREIGN KEY (IDPAYMENT) REFERENCES PAYMENT(ID),
	FOREIGN KEY (IDTYPE) REFERENCES PAYMENTTYPE(ID),
	FOREIGN KEY (IDSTATUS) REFERENCES ACTION(ID),
);


CREATE TABLE SETTLEMENTS (
    ID INT PRIMARY KEY IDENTITY(1,1),
    IDACCOUNTRECEIVABLE INT,
    IDPAYMENT INT,
    FOREIGN KEY (IDACCOUNTRECEIVABLE) REFERENCES ACCOUNTRECEIVABLE(ID),
    FOREIGN KEY (IDPAYMENT) REFERENCES PAYMENT(ID)
);

INSERT INTO ACTION(ID,VNAME,VDISPLAY,VDISPLAYESTATUS)
VALUES (31,'TRANSIT','Transito','Transito')

