
UPDATE ACCOUNTRECEIVABLE
SET IDSTATUS=CASE WHEN DDUEDATE<GETDATE() THEN  DBO.UFN_GET_ISTATUS('OVERDUE') ELSE DBO.UFN_GET_ISTATUS('OPEN') END
WHERE IDSTATUS<>DBO.UFN_GET_ISTATUS('PAID')

UPDATE PAYMENTDETAILS
SET IDSTATUS=DBO.UFN_GET_ISTATUS('TOAPPROVE')
WHERE IDSTATUS IN (DBO.UFN_GET_ISTATUS('TOVALIDATE'),DBO.UFN_GET_ISTATUS('TOVALIDATE'))

