USE [SODA]
GO

/****** Object:  View [dbo].[V_POLICY]    Script Date: 04/02/2026 9:58:26 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO






CREATE VIEW [dbo].[V_POLICY]
AS

	SELECT 
	    ISNULL(P.VNUMBER,'') AS [NUMERO DE POLIZA],
		PT.VDESCRIPTION AS [TIPO DE POLIZA],
		V.VVIN AS [VIN],
		V.VPLATE AS [PLACA],
		v.VENGINESERIAL AS [SERIAL DE MOTOR],
		L.VDESCRIPTION AS [MODELO],
	    cr.VNAME COLOR,
		P.DACTIVATIONDATE AS [FECHA DE ACTIVACION],
		P.DLOCKDATE AS [FECHA DE BLOQUEO],
		P.DEXPIRATIONDATE AS [FECHA DE EXPIRACION],
		P.DCREATED AS [FECHA CREACION POLIZA],
		P.VINVOICENUMBER AS [NUMERO DE FACTURA],
		P.NINVOICEAMOUNT AS [MONTO DE VENTA],
		P.DINVOICEDATE AS [FECHA FACTURACION],
		C.VVAT AS [DOCUMENTO CLIENTE],
		(C.VFIRSTNAME+' '+ISNULL(C.VLASTNAME,'')) AS [NOMBRE CLIENTE],
		C.VEMAIL AS [CORREO ELECTRONICO],
		C.VPHONE1 AS [NUMERO DE TELEFONO],
		ISNULL (X.VREFERENCE,'') AS [CODIGO DE CONCESIONARIO],
		ISNULL (X.VFIRSTNAME,'') AS [CONCESIONARIO],
		ISNULL (Z.VREFERENCE,'') AS [CODIGO DE PLANTA],
		A.VDISPLAYESTATUS AS ESTATUS,
		(CU.VFIRSTNAME+' '+ISNULL(CU.VLASTNAME,'')) AS VENDEDOR,
		CI.VNAME AS [CIUDAD CONCESIONARIO],
		CY.VNAME AS [CIUDAD CLIENTE],
		V.IDSUPPLIER,
		V.IDDEALER,
		P.IESTATUS
       	FROM POLICY P WITH (NOLOCK)
       	INNER JOIN VEHICLE V WITH (NOLOCK )ON P.IDVEHICLE = V.ID
       	INNER JOIN CONTACT C  WITH (NOLOCK) ON V.IDCUSTOMER = C.ID
       	INNER JOIN CONTACT X  WITH (NOLOCK) ON V.IDDEALER = X.ID
		INNER JOIN CONTACT Z  WITH (NOLOCK) ON V.IDSUPPLIER = Z.ID
       	INNER JOIN POLICYTYPE PT  WITH (NOLOCK) ON P.IDPOLICYTYPE = PT.ID
       	INNER JOIN ACTION A  WITH (NOLOCK) ON P.IESTATUS = A.ID
		INNER JOIN MODEL L  WITH (NOLOCK) ON V.IDMODEL= L.ID
		INNER JOIN COLOR CR WITH (NOLOCK) ON V.IDCOLOR =CR.ID
		LEFT JOIN INFOUSER US WITH (NOLOCK) ON  P.VUPDATEDBY= US.VLOGIN
		LEFT JOIN CONTACT CU WITH (NOLOCK) ON US.IDUSER=CU.ID
		LEFT JOIN CITY CI WITH (NOLOCK) ON X.IDCITY=CI.ID
		LEFT JOIN CITY CY WITH (NOLOCK) ON C.IDCITY=CY.ID
	
	
GO


