 
GO

/****** Object:  View [dbo].[V_BACKORDER]    Script Date: 9/24/2025 1:16:44 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO








CREATE  VIEW [dbo].[V_BACKORDER]

AS


SELECT A.ID AS IDBACKORDER,
A.IDSUPPLIER,A.IBACKORDER,A.DCREATED,A.IDSTATUS, A.DARRIVAL,
B.IDSALEORDER,C.IDDEALER,C.IDTYPE,D.VNAME AS VTYPE,F.VDISPLAYESTATUS,G.DEALER, G.VREFERENCEDEALER, G.VREFERENCESUPPLIER,  
H.VINNERCODE,H.VDESCRIPTION,
CAST (B.IDSALEORDER AS VARCHAR(10)) AS VIDSALEORDER
FROM BACKORDER A WITH (NOLOCK)
INNER JOIN SALEORDERDETAIL B WITH (NOLOCK) ON B.ID=A.IDSALEORDERDETAIL
INNER JOIN SALEORDER C WITH (NOLOCK) ON C.ID=B.IDSALEORDER
INNER JOIN SALEORDERTYPE D WITH (NOLOCK) ON D.ID=C.IDTYPE
INNER JOIN ACTION F WITH (NOLOCK) ON F.ID=A.IDSTATUS
INNER JOIN V_DEALERS G ON G.IDDEALER=C.IDDEALER 
INNER JOIN PART H WITH (NOLOCK) ON H.ID=B.IDPART 
GO


