USE OASIS
GO

/****** Object:  View [dbo].[V_DISPATCHEDCONTROLUNPACKAGED]    Script Date: 2/2/2026 10:55:47 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


alter VIEW [dbo].[V_DISPATCHEDCONTROLUNPACKAGED]
AS

SELECT X.IDSUPPLIER,X.DEALER,X.IDSALEORDER ,X.IDPART,X.VINNERCODE,X.VDESCRIPTION,
SUM(X.IDISPATCHED) AS IDISPATCHED,DCONTROLDATE,IDCONTROL,IDINVOICE
FROM 
(
	SELECT A.IDSUPPLIER, V.DEALER,A.IDSALEORDER ,A.IDPART,P.VINNERCODE,P.VDESCRIPTION,
	SUM(isnull(A.IDISPATCHED,0)) IDISPATCHED,MIN(DCONTROLDATE)  DCONTROLDATE,A.IDCONTROL,ISNULL(A.IDINVOICE,0) IDINVOICE
	FROM DISPATCHEDCONTROL A WITH (NOLOCK)
	INNER JOIN V_DEALERS V ON V.IDDEALER=A.IDCUSTOMER
	INNER JOIN PART P WITH (NOLOCK) ON P.ID=A.IDPART
	WHERE ISNULl(A.IINVOICED,0)=0
	and NOT EXISTS (SELECT * FROM MOVEMENTDETAILSPACKAGED X WITH (NOLOCK) WHERE X.IDMOVEMENTDETAIL=A.IDMOVEMENTDETAIL)
	GROUP BY A.IDSUPPLIER,V.DEALER,A.IDSALEORDER,A.IDPART,P.VINNERCODE,P.VDESCRIPTION,A.IDMOVEMENTDETAIL,A.IDCONTROL,A.IDINVOICE
	UNION
	SELECT A.IDSUPPLIER, V.DEALER,A.IDSALEORDER ,A.IDPART,P.VINNERCODE,P.VDESCRIPTION,
	SUM(isnull(A.IINVOICED,0)) IDISPATCHED,MIN(DCONTROLDATE)  DCONTROLDATE ,A.IDCONTROL,ISNULL(A.IDINVOICE,0) IDINVOICE
	FROM DISPATCHEDCONTROL A WITH (NOLOCK)
	INNER JOIN V_DEALERS V ON V.IDDEALER=A.IDCUSTOMER
	INNER JOIN PART P WITH (NOLOCK) ON P.ID=A.IDPART
	WHERE ISNULl(A.IINVOICED,0)>0
	and NOT EXISTS (SELECT * FROM MOVEMENTDETAILSPACKAGED X WITH (NOLOCK) WHERE X.IDMOVEMENTDETAIL=A.IDMOVEMENTDETAIL)
	GROUP BY A.IDSUPPLIER,V.DEALER,A.IDSALEORDER,A.IDPART,P.VINNERCODE,P.VDESCRIPTION,A.IDMOVEMENTDETAIL,A.IDCONTROL,A.IDINVOICE
) X 
GROUP BY IDSUPPLIER,X.DEALER,X.IDSALEORDER ,X.IDPART,X.VINNERCODE,X.VDESCRIPTION,DCONTROLDATE,IDCONTROL,IDINVOICE
GO


