USE OASIS
GO

/****** Object:  View [dbo].[V_GUIDE_RESUME]    Script Date: 2/2/2026 11:03:01 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


alter VIEW [dbo].[V_GUIDE_RESUME]
AS

SELECT 
A.VINNERCODE,A.VDESCRIPTION,A.IQUANTITY,A.IRECEIVED,A.VPACKAGECODE,A.IDSALEORDER,A.IDGUIDE,G.DCREATEDDATE,
V.DEALER,G.VDISPLAYESTATUS
FROM GUIDEDETAILS A WITH (NOLOCK)
INNER JOIN V_GUIDE G WITH (NOLOCK) ON G.ID=A.IDGUIDE
INNER JOIN V_DEALERS V ON V.IDDEALER=G.IDCUSTOMER
WHERE G.VDISPLAYESTATUS<>'BORRADOR'


GO


