USE [SODA]
GO

/****** Object:  View [dbo].[V_GUIDE]    Script Date: 31/01/2026 13:49:42 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO




ALTER VIEW [dbo].[V_GUIDE]
AS

		SELECT 
		G.ID,
		CAST(G.ID AS VARCHAR(10)) AS VID,
		G.IDSUPPLIER,
		S.VSUPPLIER,	
		G.IDCUSTOMER,
		C.VFIRSTNAME AS VCUSTOMER,
		ISNULL(G.IDPROVIDER,0) AS IDPROVIDER,
		ISNULL(P.VFIRSTNAME,0) AS VPROVIDER,
		ISNULL(G.VNUMBER,'') VNUMBER,
		ISNULL(PK.NWEIGHT,0) as NWEITH,
		G.DCREATEDDATE,
		G.DDELIVERYDATE,
		CASE WHEN A.VDISPLAYESTATUS = 'Procesado' THEN 'Enviado' ELSE A.VDISPLAYESTATUS END VDISPLAYESTATUS,
		A.ID AS IESTATUS
		 FROM GUIDE G
		 INNER JOIN V_SUPPLIERS S on S.IDSUPPLIER = G.IDSUPPLIER
		 INNER JOIN V_CONTACTS C ON C.ID = G.IDCUSTOMER
		 left Join ( 
					SELECT IDGUIDE,SUM(NWEIGHT) NWEIGHT
					 FROM PACKAGE pk WITH (NOLOCK)
					 GROUP BY IDGUIDE
					 ) PK on pk.IDGUIDE = g.ID 
		 Left JOIN V_PROVIDER P ON P.ID = G.IDPROVIDER
		 INNER JOIN [ACTION] A ON G.ISTATUS = A.ID
GO


