USE [SODA]
GO

/****** Object:  View [dbo].[V_MOVEMENTDETAILS]    Script Date: 1/8/2026 12:05:32 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO




ALTER VIEW [dbo].[V_MOVEMENTDETAILS]
AS

	SELECT 
	D.ID,
	D.IDMOVEMENT,
	D.IDPART,
	P.VINNERCODE VCODEPART, P.VDESCRIPTION AS VPART,
	ISNULL(P.VBARCODE,'') VBARCODE,
	ISNULL(D.VSERIAL,'') VSERIAL,
	P.VSIZE AS VPARTSIZE,
	D.VLOCATIONTYPE,
	ISNULL(D.IDLOCATION,0) IDLOCATION,
	ISNULL(L.VNAME,'') AS VLOCATION, 
	ISNULL(D.IDDESTINATION,0) IDDESTINATION,
	ISNULL(L2.VNAME,'') AS VDESTINATION,
	D.IREQUIRED,
	D.IREAL,
	D.VTYPE,
	CASE WHEN D.VTYPE = 'P' THEN 'Picking' ELSE 'Entrega' END VTYPEMOVEMENT,
	M.VTYPE AS VMOVEMENTTYPE,
	D.VTYPE AS VMOVEMENTTYPEDETAIL,
	D.BPROCESSED,
	--D.DCREATED,
	--D.DUPDATED,
	D.VUPDATEDBY,
	D.IDPARTIALTYPE,
	ISNULL(D.IDUSER,0) IDUSER,
	D.NCOST,
	CONVERT(VARCHAR(20),D.DUPDATED,120) AS VUPDATED,
	ISNULL(C.VLOGIN,'') VLOGIN,
	ISNULL(L.IMAPPING,0) IMAPPING,
	D.IREQUIRED * CASE WHEN D.VTYPE='P' THEN D.NCOST ELSE 0 END AS NSUBTOTAL,
	CASE WHEN M.VTYPE = 'P' THEN P.BSERIALIZABLE ELSE CAST (0 AS BIT) END BSERIALIZABLE,
	--M.IESTATUS,
	M.IDCONTACT,
	ISNULL(D.IDGROUP,0) IDGROUP,
	M.IDSUPPLIER,
	ISNULL(D.IDBACKORDER,0) IDBACKORDER,
	D.IPRIORITY,
	D.IDSTATUS,
	A.VDISPLAYESTATUS,
	M.DGENERATED
	FROM MOVEMENTDETAILS D WITH (NOLOCK)
	INNER JOIN MOVEMENT M WITH (NOLOCK) ON M.ID=D.IDMOVEMENT
	INNER JOIN PART P WITH (NOLOCK) ON P.ID=D.IDPART
	INNER JOIN ACTION A WITH (NOLOCK) ON A.ID=D.IDSTATUS
	LEFT JOIN LOCATION L WITH (NOLOCK) ON L.ID=D.IDLOCATION
	LEFT JOIN INFOUSER C WITH (NOLOCK) ON C.IDUSER=D.IDUSER
	LEFT JOIN LOCATION L2 WITH (NOLOCK) ON L2.ID=D.IDDESTINATION 


GO


