USE [SODA]
GO

/****** Object:  View [dbo].[V_MOVEMENTDETAILS_TOGROUP]    Script Date: 12/11/2025 9:39:24 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO



ALTER VIEW [dbo].[V_MOVEMENTDETAILS_TOGROUP]
AS

SELECT VMOVEMENTTYPE,VTYPE,IDLOCATION,IMAPPING,IDPART,IDUSER,
MIN(ID) AS IDGRUPO,SUM(IREQUIRED) IREQUIRED,IDSUPPLIER,MAX(IPRIORITY) IPRIORITY
FROM V_MOVEMENTDETAILS
WHERE 
IESTATUS=DBO.UFN_GET_ISTATUS('ASSIGN')
AND BPROCESSED = 0
AND IDUSER>0
AND ISNULL(IDGROUP,0)=0
GROUP BY VMOVEMENTTYPE,VTYPE,IDLOCATION,IMAPPING,IDPART,IDUSER,IDSUPPLIER
GO


