USE [SODA]
GO

/****** Object:  View [dbo].[V_MOVEMENTDETAILS_GROUPED]    Script Date: 1/8/2026 12:04:53 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO



ALTER VIEW [dbo].[V_MOVEMENTDETAILS_GROUPED]
AS

SELECT  IDGROUP AS ID,0 IDMOVEMENT,
VMOVEMENTTYPE,VTYPEMOVEMENT,VTYPE,
IDLOCATION,VLOCATIONTYPE,VLOCATION,IMAPPING,
IDPART,'' VSERIAL,VCODEPART,VPART,VBARCODE,BSERIALIZABLE,BPROCESSED,
IDGROUP,IDUSER,VLOGIN,IDSUPPLIER,
SUM(IREQUIRED) IREQUIRED,0 IREAL
FROM V_MOVEMENTDETAILS
WHERE IDSTATUS=DBO.UFN_GET_ISTATUS('ASSIGN')
AND BPROCESSED = 0
AND ISNULL(IDGROUP,0)>0
GROUP BY VMOVEMENTTYPE,VTYPEMOVEMENT,VTYPE,
IDLOCATION,VLOCATIONTYPE,VLOCATION,IMAPPING,
IDPART,VCODEPART,VPART,VBARCODE,BSERIALIZABLE,BPROCESSED,
IDGROUP,IDUSER,VLOGIN,IDSUPPLIER

GO


