USE [ZEPPELIN]
GO

/****** Object:  View [dbo].[V_PACKAGEDETAIL]    Script Date: 1/5/2026 3:17:57 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO



ALTER VIEW [dbo].[V_PACKAGEDETAIL]  
AS  
  
--SELECT   
--D.ID,D.IDPACKAGE,PP.VCODE AS VPACKAGECODE, D.IDPART,D.IQUANTITY,  
--P.VINNERCODE,P.VDESCRIPTION,P.VBARCODE ,X.IDSALEORDER 
--from PACKAGEDETAIL D WITH (NOLOCK)  
--INNER JOIN PART P WITH (NOLOCK) ON P.ID=D.IDPART  
--INNER JOIN PACKAGE PP WITH (NOLOCK) ON PP.ID=D.IDPACKAGE  
--INNER JOIN (
--			SELECT X.IDPACKAGEDETAIL,Z.IDSALEORDER,X.IQUANTITY
--			FROM MOVEMENTDETAILSPACKAGED X WITH (NOLOCK)
--			INNER JOIN MOVEMENTDETAILS Y WITH (NOLOCK) ON Y.ID=X.IDMOVEMENTDETAIL
--			INNER JOIN PACKAGEDETAIL P WITH (NOLOCK) ON P.ID=X.IDPACKAGEDETAIL
--			INNER JOIN BACKORDER Z WITH (NOLOCK) ON Z.ID=Y.IDBACKORDER
--			WHERE X.IDPACKAGEDETAIL=1543
--			GROUP BY X.IDPACKAGEDETAIL,Z.IDSALEORDER,X.IQUANTITY
--			) X ON X.IDPACKAGEDETAIL=D.ID

SELECT P.ID,P.IDPACKAGE,PP.VCODE AS VPACKAGECODE, X.IDPACKAGEDETAIL,
P.IDPART,P2.VINNERCODE,P2.VDESCRIPTION,P2.VBARCODE ,
Z.IDSALEORDER,X.IQUANTITY
FROM MOVEMENTDETAILSPACKAGED X WITH (NOLOCK)
INNER JOIN MOVEMENTDETAILS Y WITH (NOLOCK) ON Y.ID=X.IDMOVEMENTDETAIL
INNER JOIN PACKAGEDETAIL P WITH (NOLOCK) ON P.ID=X.IDPACKAGEDETAIL
INNER JOIN PACKAGE PP (NOLOCK) ON PP.ID=P.IDPACKAGE
INNER JOIN BACKORDER Z WITH (NOLOCK) ON Z.ID=Y.IDBACKORDER
INNER JOIN PART P2 WITH (NOLOCK)  ON P2.ID=P.IDPART
WHERE X.IQUANTITY>0
GROUP BY P.ID,P.IDPACKAGE,PP.VCODE, X.IDPACKAGEDETAIL,
P.IDPART,P2.VINNERCODE,P2.VDESCRIPTION,P2.VBARCODE ,
Z.IDSALEORDER,X.IQUANTITY


GO


