USE [SODA]
GO

/****** Object:  View [dbo].[V_POLICY]    Script Date: 29/12/2025 8:48:06 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


ALTER VIEW [dbo].[V_POLICY]
AS

	SELECT 
	P.ID,
		P.IDPOLICYTYPE,
		v.VENGINESERIAL,
		P.IDVEHICLE,
		P.DACTIVATIONDATE,
		P.DLOCKDATE,
		P.DEXPIRATIONDATE,
		P.DCREATED,
		P.VINVOICENUMBER,
		P.NINVOICEAMOUNT,
		P.DINVOICEDATE,
		P.IDPAYMETHOD,
		P.IESTATUS,
		ISNULL(P.VNUMBER,'') VNUMBER,
		P.BACTIVE,
	     PT.VDESCRIPTION,
		 V.VVIN,
		 V.VPLATE,
		 L.VDESCRIPTION MODELNAME,
		 C.VVAT,
		 C.VFIRSTNAME,
		 C.VEMAIL,
		 C.VPHONE1,
		 ISNULL(C.VLASTNAME,'') VLASTNAME,
		 ISNULL (X.VREFERENCE,'') AS CODDEALER,
		 ISNULL (X.VFIRSTNAME,'') AS VDEALER,
		 ISNULL (Z.VREFERENCE,'') AS CODSUPPLIER ,
		 A.VDISPLAYESTATUS AS ESTATUSNAME,
		 V.IDCUSTOMER,
		 V.IDDEALER,
		 (CU.VFIRSTNAME+' '+ISNULL(CU.VLASTNAME,'')) AS VSELLER,
		 CI.VNAME AS VCITYDEALER,
		 CY.VNAME AS VCITYCUSTOMER,
		 cr.VNAME VCOLOR,
		 V.IDSUPPLIER
        FROM POLICY P WITH (NOLOCK)
        INNER JOIN VEHICLE V WITH (NOLOCK )ON P.IDVEHICLE = V.ID
        INNER JOIN CONTACT C  WITH (NOLOCK) ON V.IDCUSTOMER = C.ID
        INNER JOIN CONTACT X  WITH (NOLOCK) ON V.IDDEALER = X.ID
        INNER JOIN CONTACT Z  WITH (NOLOCK) ON V.IDSUPPLIER = Z.ID
        INNER JOIN POLICYTYPE PT  WITH (NOLOCK) ON P.IDPOLICYTYPE = PT.ID
        INNER JOIN ACTION A  WITH (NOLOCK) ON P.IESTATUS = A.ID
        INNER JOIN MODEL L  WITH (NOLOCK) ON V.IDMODEL= L.ID
		INNER JOIN COLOR CR WITH (NOLOCK) ON V.IDCOLOR =CR.ID
		LEFT JOIN INFOUSER US WITH (NOLOCK) ON  P.VUPDATEDBY= US.VLOGIN
		LEFT JOIN CONTACT CU WITH (NOLOCK) ON US.IDUSER=CU.ID
		LEFT JOIN CITY CI WITH (NOLOCK) ON X.IDCITY=CI.ID
		LEFT JOIN CITY CY WITH (NOLOCK) ON C.IDCITY=CY.ID
	
	
GO


