USE [OASIS]
GO

/****** Object:  View [dbo].[V_SALEORDERVSINVOICED]    Script Date: 1/8/2026 3:43:57 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE VIEW [dbo].[V_SALEORDERVSINVOICED] 
AS

SELECT V.DEALER,A.IDSALEORDER ,A.IDPART,P.VINNERCODE,P.VDESCRIPTION,SUM(isnull(A.IINVOICED,0)) IINVOICED 
FROM DISPATCHEDCONTROL A WITH (NOLOCK)
INNER JOIN V_DEALERS V ON V.IDDEALER=A.IDCUSTOMER
INNER JOIN PART P WITH (NOLOCK) ON P.ID=A.IDPART
WHERE A.IDINVOICE>0
GROUP BY V.DEALER,A.IDSALEORDER,A.IDPART,P.VINNERCODE,P.VDESCRIPTION
GO


