USE [OASIS]
GO

/****** Object:  View [dbo].[V_SALEORDERVSINVOICE]    Script Date: 1/8/2026 3:43:37 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE VIEW [dbo].[V_SALEORDERVSINVOICE] 
AS

SELECT V.DEALER,A.IDSALEORDER ,A.IDPART,P.VINNERCODE,P.VDESCRIPTION, 
isnull(A.IDINVOICE,0) IDINVOICE,SUM(isnull(A.IINVOICED,0)) IINVOICED 
FROM DISPATCHEDCONTROL A WITH (NOLOCK)
INNER JOIN V_DEALERS V ON V.IDDEALER=A.IDCUSTOMER
INNER JOIN PART P WITH (NOLOCK) ON P.ID=A.IDPART
WHERE A.IDINVOICE>0
GROUP BY V.DEALER,A.IDSALEORDER,A.IDPART,P.VINNERCODE,P.VDESCRIPTION ,A.IDINVOICE
GO


