USE SODA
GO

/****** Object:  View [dbo].[V_SALEORDERVSBACKORDER]    Script Date: 2/2/2026 10:56:26 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


CREATE VIEW [dbo].[V_SALEORDERVSBACKORDER]
AS

SELECT S.*,
ISNULL(B.IBACKORDER,0) IBACKORDER,
ISNULL(B2.IBACKORDER,0) IDISMISSED
FROM 
(
SELECT SO.IDSUPPLIER,SO.ID AS IDSALEORDER,ST.VNAME, SO.DCREATED,D.DEALER,
SD.IDPART,
P.VINNERCODE,
P.VDESCRIPTION,
SD.IREQUIRED,
SD.ID AS IDSALEORDERDETAIL
FROM SALEORDER SO WITH (NOLOCK)
INNER JOIN V_DEALERS D ON D.IDDEALER=SO.IDDEALER
INNER JOIN SALEORDERDETAIL SD WITH (NOLOCK) ON SD.IDSALEORDER=SO.ID
INNER JOIN PART P WITH (NOLOCK) ON P.ID=SD.IDPART
INNER JOIN SALEORDERTYPE ST WITH (NOLOCK) ON ST.ID=SO.IDTYPE
WHERE SO.IDESTATUS<>2

) S
LEFT JOIN (
			SELECT  
			BO.IDSALEORDERDETAIL,
			SUM(BO.IBACKORDER) IBACKORDER
			FROM BACKORDER BO WITH (NOLOCK)
			WHERE BO.IDSTATUS=2
			GROUP BY BO.IDSALEORDERDETAIL
			) B ON B.IDSALEORDERDETAIL=S.IDSALEORDERDETAIL
LEFT JOIN (
			SELECT  
			BO.IDSALEORDERDETAIL,
			SUM(BO.IBACKORDER) IBACKORDER
			FROM BACKORDER BO WITH (NOLOCK)
			WHERE BO.IDSTATUS=19
			GROUP BY BO.IDSALEORDERDETAIL
			) B2 ON B2.IDSALEORDERDETAIL=S.IDSALEORDERDETAIL

GO


