USE [OASIS]
GO

/****** Object:  View [dbo].[V_SALEORDERVSDISPATCHED]    Script Date: 1/8/2026 3:42:53 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE VIEW [dbo].[V_SALEORDERVSDISPATCHED]  
AS  
  
SELECT X.DEALER,X.IDSALEORDER ,X.IDPART,X.VINNERCODE,X.VDESCRIPTION,  
SUM(X.IDISPATCHED) AS IDISPATCHED  
FROM   
(  
 SELECT V.DEALER,A.IDSALEORDER ,A.IDPART,P.VINNERCODE,P.VDESCRIPTION,  
 SUM(isnull(A.IDISPATCHED,0)) IDISPATCHED   
 FROM DISPATCHEDCONTROL A WITH (NOLOCK)  
 INNER JOIN V_DEALERS V ON V.IDDEALER=A.IDCUSTOMER  
 INNER JOIN PART P WITH (NOLOCK) ON P.ID=A.IDPART  
 WHERE ISNULl(A.IINVOICED,0)=0  
 GROUP BY V.DEALER,A.IDSALEORDER,A.IDPART,P.VINNERCODE,P.VDESCRIPTION,A.IDMOVEMENTDETAIL  
 UNION  ALL
 SELECT V.DEALER,A.IDSALEORDER ,A.IDPART,P.VINNERCODE,P.VDESCRIPTION,  
 SUM(isnull(A.IINVOICED,0)) IDISPATCHED   
 FROM DISPATCHEDCONTROL A WITH (NOLOCK)  
 INNER JOIN V_DEALERS V ON V.IDDEALER=A.IDCUSTOMER  
 INNER JOIN PART P WITH (NOLOCK) ON P.ID=A.IDPART  
 WHERE ISNULl(A.IINVOICED,0)>0  
 GROUP BY V.DEALER,A.IDSALEORDER,A.IDPART,P.VINNERCODE,P.VDESCRIPTION,A.IDMOVEMENTDETAIL  
) X   
GROUP BY X.DEALER,X.IDSALEORDER ,X.IDPART,X.VINNERCODE,X.VDESCRIPTION
GO


