USE SODA
GO

/****** Object:  View [dbo].[V_SALEORDERVSRECEIVED]    Script Date: 2/2/2026 10:58:17 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

ALTER VIEW [dbo].[V_SALEORDERVSRECEIVED]
AS

SELECT V.DEALER,D.IDSALEORDER ,D.IDPART,P.VINNERCODE,P.VDESCRIPTION,
SUM(D.IRECEIVED) IRECEIVED
FROM GUIDEDETAILS D WITH (NOLOCK)
INNER JOIN GUIDE G WITH (NOLOCK) ON G.ID=D.IDGUIDE
INNER JOIN V_DEALERS V ON V.IDDEALER=G.IDCUSTOMER
INNER JOIN PART P WITH (NOLOCK) ON P.ID=D.IDPART
WHERE D.BCONFIRMED=1
AND G.ISTATUS = 12
GROUP BY V.DEALER,D.IDSALEORDER ,D.IDPART,P.VINNERCODE,P.VDESCRIPTION
GO


