USE [OASIS]
GO

/****** Object:  View [dbo].[V_SALEORDERVSPICKING]    Script Date: 1/8/2026 3:44:13 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


CREATE VIEW [dbo].[V_SALEORDERVSPICKING]
AS
SELECT V.DEALER,C.IDSALEORDER ,A.IDPART,P.VINNERCODE,P.VDESCRIPTION,
SUM(A.IREQUIRED) AS IQUANTITY
FROM MOVEMENTDETAILS A
INNER JOIN MOVEMENT B ON B.ID=A.IDMOVEMENT
INNER JOIN BACKORDER C ON C.ID=A.IDBACKORDER
INNER JOIN V_DEALERS V ON V.IDDEALER=C.IDDEALER
INNER JOIN PART P WITH (NOLOCK) ON P.ID=A.IDPART
WHERE B.VTYPE='P'
AND A.VTYPE='P'
AND BPROCESSED=0
GROUP BY V.DEALER,C.IDSALEORDER ,A.IDPART,P.VINNERCODE,P.VDESCRIPTION
UNION
SELECT V.DEALER,C.IDSALEORDER ,A.IDPART,P.VINNERCODE,P.VDESCRIPTION,
SUM(A.IREQUIRED) AS IQUANTITY
FROM MOVEMENTDETAILS A
INNER JOIN MOVEMENT B ON B.ID=A.IDMOVEMENT
INNER JOIN BACKORDER C ON C.ID=A.IDBACKORDER
INNER JOIN V_DEALERS V ON V.IDDEALER=C.IDDEALER
INNER JOIN PART P WITH (NOLOCK) ON P.ID=A.IDPART
WHERE B.VTYPE='P'
AND A.VTYPE='D'
AND BPROCESSED=0
GROUP BY V.DEALER,C.IDSALEORDER ,A.IDPART,P.VINNERCODE,P.VDESCRIPTION
GO


