
GO

/****** Object:  View [dbo].[V_SALEORDER]    Script Date: 9/24/2025 1:16:53 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO







CREATE   VIEW [dbo].[V_SALEORDER]
AS


SELECT 
S.ID,
CAST ( S.ID AS VARCHAR(10)) AS VID,
S.IDDEALER,
S.IDSUPPLIER,
S.IDESTATUS,
ISNULL(S.VREFERENCE,'') VREFERENCE,
ISNULL(S.VCOMMENT,'') VCOMMENT,
CONVERT(VARCHAR(20),S.DCREATED,120) VCREATED,
S.DUPDATED,
ISNULL(S.VCREATEDBY,'') VCREATEDBY,
S.VUPDATEDBY,
ISNULL(S.IDTYPE,0) IDTYPE,
S.BCLAIM,
S.IDVEHICLE,
S.BPARALYZED,
CASE WHEN A.VDISPLAYESTATUS = 'Asignado' THEN 'PREPARACION' 
     WHEN A.VDISPLAYESTATUS = 'Procesado' AND S.BCOMPLETED=0 THEN 'DESPACHO PARCIAL' 
     WHEN A.VDISPLAYESTATUS = 'Procesado' AND S.BCOMPLETED=1 THEN 'DESPACHADO' 
     ELSE A.VDISPLAYESTATUS END
AS VESTATUS, 
ISNULL(T.VNAME,'') AS VTYPE,
D.DEALER AS VDEALER,X.VSUPPLIER
FROM SALEORDER S WITH (NOLOCK)
LEFT JOIN SALEORDERTYPE T WITH (NOLOCK) ON T.ID=S.IDTYPE
INNER JOIN ACTION A WITH (NOLOCK) ON A.ID=S.IDESTATUS
INNER JOIN V_DEALERS D ON D.IDDEALER=S.IDDEALER
INNER JOIN V_SUPPLIERS X ON X.IDSUPPLIER=S.IDSUPPLIER
GO


