CREATE TABLE INSPECTION (
    ID INT IDENTITY(1,1) PRIMARY KEY,
	IDVEHICLE INT NOT NULL,
	IDAREA INT NOT NULL,
	BACTIVE BIT NOT NULL DEFAULT 1,
	
	----- USUARIOS
	ICREATEDBY INT NOT NULL,
	IDINITBY INT,
	IDCLOSEDBY INT,
	IDTRANSPORTER INT,
	IDRECEPBY INT,
	
	------ FECHAS
 	DCREATED DATETIME NOT NULL DEFAULT GETDATE(),
 	DUPDATED DATETIME NOT NULL DEFAULT GETDATE(),
 	DDATEINIT DATETIME,
 	DDATECLOSE DATETIME,
 	DRECEPTION DATETIME,
	-- LLAVES FORANEAS
	FOREIGN KEY (IDVEHICLE) REFERENCES VEHICLE(ID),
	FOREIGN KEY (IDAREA) REFERENCES AREA(ID)
);

CREATE TABLE INSPECTIONDETAIL (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    BVALUE INT,
    VOBSERVATION VARCHAR(500),
    VFILEURL varchar(500),
	BACTIVE BIT NOT NULL DEFAULT 1,
    IDINSPECTION INT NOT NULL,
    IDFEATURE INT NOT NULL,
    
    -- llaves foraneas
    FOREIGN KEY (IDINSPECTION) REFERENCES INSPECTION(ID),
    FOREIGN KEY (IDFEATURE) REFERENCES FEATURE(ID)
);

CREATE TABLE INSPECTIONFASE (
	ID INT IDENTITY(1, 1) PRIMARY KEY,
	IDFASE INT NOT NULL,
	IDINSPECTION INT NOT NULL,
	DCOMPLETED DATETIME,
	
	FOREIGN KEY (IDFASE) REFERENCES FASE(ID),
	FOREIGN KEY (IDINSPECTION) REFERENCES INSPECTION(ID)
);


